### ISSUE TITLE
Two-way data binding and negation expression

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#2162] opened 2015-07-28 16:49 UTC
[Docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#expressions-in-binding-annotations) says that Polymer supports negation expressions:
```hmtl
<template>
  <div hidden="{{!enabled}}"></div>
</template>
``` 

As `{{}}` suggests two-way binding I thought it works both ways. However it seems it doesn't, at least within `dom-bind`.
Am I doing something wrong? Do you have any plans to support binding negated value back?

I found it quite useful, even for some basic cases like: `<input type="checkbox" checked="{{!booleanSwitch::change}}">`

**Comment by kevinpschaaf** [comment] 2015-07-29 19:13
Closing as duplicate of https://github.com/Polymer/polymer/issues/1715.

We are considering supporting this, although there are some corner-cases that need to be evaluated; for example, if you bind `{{!stuff.enabled}}` to `checked` and `stuff.enabled` is `undefined`, negating it will send `true` to the checkbox, which will round-trip back and set `stuff.enabled` to `false` (i.e. changing it from its `undefined` value), and there may be cases where that is undesirable.

In the meantime, you can manually perform the two-way negation as follows:

```html
<input type="checkbox" checked="{{!booleanSwitch}}" on-change="checkedChanged">
```
```js
checkedChanged: function(e) {
  this.booleanSwitch = !e.target.checked;
}
```

**Closed by kevinpschaaf** 2015-07-29 19:13 UTC
