### ISSUE TITLE
class.html:130 behavior is null, check for missing or 404 import Polymer 2 only in Chrome

### ISSUE THREAD

**Issue by Ankita-G-Mudgal** [Polymer/polymer#5082] opened 2018-02-01 08:38 UTC
### Description

If I use async attribute in <link> tag getting behavior null 

#### Steps to Reproduce
1. Create an element which in turn uses some polymer elements app-layout.
2. Import it with async attribute in another element and you will get this error

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2
- webcomponents: v^1.0.0

**Comment by TimvdLippe** [comment] 2018-02-01 12:45
Closing as duplicate of #4443. See https://github.com/Polymer/polymer/issues/4443#issuecomment-329305679 for more information.

**Closed by TimvdLippe** 2018-02-01 12:45 UTC
