### ISSUE TITLE
DOWNLOAD ZIP Button: Not getting saved in zip format (Not User Friendly)

### ISSUE THREAD

**Issue by Srifunction** [Polymer/polymer#3625] opened 2016-04-28 11:11 UTC
### Description

When we click on the Download Zip button file is getting saved without .zip extension. Unable to extract the file.

#### Live Demo

https://www.polymer-project.org/1.0/docs/start/getting-the-code.html

#### Steps to Reproduce
Example:
1. Click on 'DOWNLOAD ZIP'
2. Save the file
3. Try to extract

#### Expected Results
The file should be saved with .zip extension.

#### Actual Results
The file is not save in .zip format.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by arthurevans** [comment] 2016-04-28 15:30
I can't reproduce this. I get an archive.zip (which the download manager immediately expands to a components folder). Are you seeing this consistently on both Chrome and Firefox? What OS?

**Comment by azakus** [comment] 2016-05-23 23:09
Looks like the zip has moved to https://www.polymer-project.org/1.0/start/first-element/intro, which is very much a `zip` to me. Closing this issue.

**Closed by azakus** 2016-05-23 23:09 UTC
Labels: pending-response
