### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by car12o** [Polymer/polymer#4978] opened 2017-12-06 12:05 UTC
### Description
Hi all,
Yesterday's release (2.3.0) broke the element styles process on element-mixin.
We were using 2.2.0 and today we updated to 2.3.0, some components show this error:
`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. (element-mixin.html:429 )
    at processElementStyles (http://localhost:3000/static/bower_components/polymer/lib/mixins/element-mixin.html:429:28)
    at Function._finalizeTemplate (http://localhost:3000/static/bower_components/polymer/lib/mixins/element-mixin.html:646:11)
    at HTMLElement._initializeProperties (http://localhost:3000/static/bower_components/polymer/lib/mixins/element-mixin.html:587:26)
    at new PropertyAccessors (http://localhost:3000/static/bower_components/polymer/lib/mixins/property-accessors.html:147:14)
    at new TemplateStamp (http://localhost:3000/static/bower_components/polymer/lib/mixins/template-stamp.html:121:5)
    at new PropertyEffects (http://localhost:3000/static/bower_components/polymer/lib/mixins/property-effects.html:1134:9)
    at new PolymerElement (http://localhost:3000/static/bower_components/polymer/lib/mixins/element-mixin.html:555:9)
    at new EdiBase (http://localhost:3000/src/elements/edi-base/edi-base.js:4:5)
    at new EdiSectionHeader (http://localhost:3000/src/elements/edi-section-header/edi-section-header.js:6:13)
    at EdiModules (http://localhost:3000/src/elements/edi-section-header/edi-section-header.js:60:20)
    at http://localhost:3000/src/elements/edi-section-header/edi-section-header.js:61:3`

**Weird that only affects some components**

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

Just tested on selected ones.

### Versions

- Polymer: v2.3.0
- webcomponents: v1.0.20

**Comment by TimvdLippe** [comment] 2017-12-06 12:18
Thanks for reporting! This is a duplicate of #4975

**Closed by TimvdLippe** 2017-12-06 12:18 UTC
