### ISSUE TITLE
Missing "paper-behaviors.html"

### ISSUE THREAD

**Issue by JKWA** [Polymer/polymer#2738] opened 2015-11-14 07:54 UTC
"paper-elements.html" imports "paper-behaviors.html", which does not exist.
<link rel="import" href="../paper-behaviors/paper-behaviors.html">

**Comment by fredj** [comment] 2015-11-17 16:26
@JKWA an issue has already been opened in the paper-elements repository, see https://github.com/PolymerElements/paper-elements/issues/54

**Comment by azakus** [comment] 2015-11-18 22:12
Closing as duplicate of PolymerElements/paper-elements#54

**Closed by azakus** 2015-11-18 22:12 UTC
