### ISSUE TITLE
Polymer.updateStyles under SHADY DOM

### ISSUE THREAD

**Issue by summers173** [Polymer/polymer#2301] opened 2015-08-18 17:25 UTC
This instruction behaves as expected on Shadow DOM

```
Polymer.updateStyles({'--accent-color': 'red']});
```

All components change, but in Shady dom, some components as 'paper-button' does not change, I got

```
<style is="custom-style">
    :root {
        --paper-button: {
            background: var(--accent-color);
            color: var(--white);
        }
    }
</style>
```

This and other elements that obey the style rule does not change under SHADY DOM.

**Comment by srijken** [comment] 2017-03-16 10:39
I have a repro based on Polymer 2.0 that demonstrates the same: https://github.com/srijken/polymer-issuerepro

Do you want to track this here or in a new issue?

**Comment by azakus** [comment] 2018-02-21 18:49
Duplicate of #2268

**Closed by azakus** 2018-02-21 18:49 UTC
Labels: 1.x, ie11, p1
