### ISSUE TITLE
template is="dom-if" throws if template contains comment

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2029] opened 2015-07-04 17:16 UTC
Given an dom-if template with a comment:

```
<template is="dom-if" if="{{fetchingMail}}">
  <!-- div class="layout vertical center-center" style="height:100%">
    <paper-spinner active></paper-spinner>
  </div -->
  <div id="refresh" class="fit layout vertical center-center">
    ...
  </div>
</div>
</template>
```
Polymer 1.0.5 throws an error trying to `display: none` it:

<img width="1128" alt="screen shot 2015-07-04 at 12 14 54 pm" src="https://cloud.githubusercontent.com/assets/238208/8508830/524ecf22-2246-11e5-89b1-d5e839d59c24.png">

**Comment by LM450N** [comment] 2015-07-05 09:23
I worked a little bit on the `dom-if` yesterday. This error happens if the dom-if contains a node without style property (like text_node, comment_node). I'll update my pull request for this case. Please, see the PR #2027 .

**Comment by wesleycho** [comment] 2015-07-05 17:56
[Here](http://embed.plnkr.co/PcHoljkmr8izkpwkvyk2/preview) is a simple reproduction (code [here](http://plnkr.co/edit/PcHoljkmr8izkpwkvyk2?p=info).

The `_showHideChildren` method in `dom-if` needs to correctly handle comment nodes - what would the desired behavior be for this situation?

I can file a PR if you like given guidance on the proper implementation here.

**Comment by kevinpschaaf** [comment] 2015-07-06 16:47
This is a dupe of #1786.

This PR will be merged this week: https://github.com/Polymer/polymer/pull/1992

**Closed by kevinpschaaf** 2015-07-06 16:47 UTC

**Comment by LM450N** [comment] 2015-07-06 17:23
Should I make a new PR to keep only the first commit of the PR #2027 who solves the issue #1725 ?
