### ISSUE TITLE
css variables break specificity

### ISSUE THREAD

**Issue by TylerPachal** [Polymer/polymer#2042] opened 2015-07-08 06:15 UTC
I have encountered what I believe to be a bug.

I have a `disabled` property, which I use to style my polymer widget into a disabled state.  This was working fine, until I introduced css variables into my styling.  

Here is a simplified example where I have replicated the bug:

	
	<dom-module id='x-button'>

		<style>
			:host {
				/* This breaks it */
				background-color: var(--x-button-background-color, orange);

				/* Un-comment this code, and remove the previous line of code to fix it */
				/*
				background-color: orange;
				*/
			}

			:host([disabled]) {
				cursor: default;
				background-color: red;
			}

		</style>

		<template>
			<content></content>
		</template>

	</dom-module>

	<script>
		Polymer({
			is:'x-button',

			properties: {
				disabled: {
					type: Boolean,
					value: false
				}
			}
		});
	</script>

And here is my simple test:

	
	<!DOCTYPE html>
	<html>
		<head>
			<link rel="import" href="../bower_components/polymer/polymer.html">
			<link rel="import" href="./x-button.html">
		</head>
		<body>

			<x-button>Hello</x-button>

			<br><br><br>

			<x-button disabled>I should look different</x-button>
			
		</body>
	</html>

Looking in the Chrome inspector, the styling applied by the `disabled` selector is being overwritten by the by the regular host styling, but only when css variables are present.  Without the css variable, the attribute selector is applied correctly, as described [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#Selector_Types).

*This is the first bug I have ever submitted, sorry if I have done something incorrectly.*

**Comment by Pupix** [comment] 2015-07-08 09:15
#1873 
This is the very same problem. That's the way custom styles actually work (for the moment), overwriting all the native CSS that comes after or before them, because the `<style>` stack in the `<head>` that polymer adds, creates the variables `<style>` after the native one.

```html
<head>
    <style scope="my-element">native css rules</style> <!-- native css -->
    <style scope="my-element-0">css rules from variables</style> <!-- if any rule is repeated, this will overwrite the native css -->
</head>
````

**Comment by kevinpschaaf** [comment] 2015-07-09 19:52
Closing as a duplicate of #1873 (which is a P1 issue that is slated for fixing/improvement).  @TylerPachal  please watch that issue for resolution.  Thanks.

**Closed by kevinpschaaf** 2015-07-09 19:52 UTC
