### ISSUE TITLE
ImportHref() doesn't play nice with firebase serve

### ISSUE THREAD

**Issue by xelra** [Polymer/polymer#5001] opened 2017-12-20 00:58 UTC
This is a cross-post, because I didn't know whether it's a Polymer or a Firebase CLI issue.

I'm using Polymer and Firebase and while developing, I noticed that I'm getting errors in the Chrome console when I try to navigate to a non-existing url/file and the whole app breaks.

Upon a whole day of investigating, I figured out that the issue is between the Firebase CLI and probably `importHref()`.

I managed to reproduce the issue with a fresh init of Firebase and a fresh init of the Polymer Starter Kit.

Steps to reproduce:
- Run `firebase init`
- Choose "Hosting", select project, default directory `public/`, "yes" single page app.
- `cd public/`
- `polymer init`
- Create a Polymer Starter Kit application, the one with the drawer, header and the 3 views
- `cd ..`
- `firebase serve`

Now navigate to a non-existing url and you'll see the following error:
![image](https://user-images.githubusercontent.com/908568/34185912-9b424112-e528-11e7-8271-b61b96e9cd31.png)
Click somewhere in the app and there will be more errors. From here on out the whole app is broken until reload:
![image](https://user-images.githubusercontent.com/908568/34185935-bf10a016-e528-11e7-828e-b18705b12f63.png)

This problem does not appear when serving with `polymer serve`. It will properly call `onerror` and redirect to 404.

I didn't test any more variations, but it can probably be reproduced in other ways too.

I want to emphasize that this problem does **not** appear when navigating to **existing** urls/files.

**Comment by xelra** [comment] 2017-12-20 01:01
This is the reference for the cross-post:
https://github.com/firebase/firebase-tools/issues/574

**Comment by jsilvermist** [comment] 2017-12-20 02:44
The issue is that when you hit a missing file you're redirecting to `index.html` and causing duplicate imports.

You need to add an exclusion for the redirections to allow for proper 404 errors in the dynamic imports.

For an example of a working `firebase.json`, see [deploy-with-firebase](https://www.polymer-project.org/2.0/start/toolbox/deploy#deploy-with-firebase).

**Comment by xelra** [comment] 2017-12-20 19:26
Thank you very much. That works, partially. 

It's not rewriting the url for any suffix that has a `.`, meaning a file extension. But `polymer serve` has the same behavior. Ideally one would expect a 404 for **any** invalid suffix. At least the app doesn't break anymore due to duplicate imports.

I'm going to ask for an added option to create a `firebase.json` that is compatible with Polymer, because this is not an obvious error.

If you don't have anything to add, please feel free to close this, since I think this is a matter concerning the Firebase CLI.

Unless `.` in the suffix is something that requires fixing.

**Comment by TimvdLippe** [comment] 2018-01-06 16:24
This appears to be a duplicate of https://github.com/PolymerElements/polymer-starter-kit/issues/1061 @xelra could you follow the instructions there, primarily the updated guide at https://www.polymer-project.org/2.0/start/toolbox/deploy#deploy-with-firebase Feel free to open an issue on the PSK if you remain having issues with Firebose hosting.

Thanks @jsilvermist for the quick response (also in the other issue)!

**Closed by TimvdLippe** 2018-01-06 16:24 UTC
