### ISSUE TITLE
[0.5.5] 80 - 100% CPU taken up in Chrome when clicking paper menu button

### ISSUE THREAD

**Issue by johnohara** [Polymer/polymer#1413] opened 2015-04-14 20:48 UTC
I'm creating a website using c#.

I have developed a page that includes a paper-menu-button - nothing fantastic just the basic stuff as per the demo. All worked fine until I put something else on the page.

When I navigate across my site, I get nothing untoward - an initial spurt of CPU that settles quickly. However, when I click the icon button used for the the paper menu, in Chrome, the CPU immediate shoots to 70% then steadily rises to 85/95% where it stays. This occurs in Chrome  41.0.2272.118 m, and not in Firefox 37.0.1.

I stripped the page back to an htm, dropping the aspx stuff, javascript and css with no success. I then copied your demo html (apart from the CSS). Again, this This works fine on its own, but as soon as I add an article (my terms and conditions), the problem reoccurs. The arcticle is pure html which has been validated - it is 4500 characters (around 600 words), which is not big in at all.

I've now exhausted all my own answers - the code runs on Chrome without the additional text, it runs with the text on Firefox, but it chews the CPU everytime on Chrome after I hit the button.

Any help or advice would be appreciated.

I'm using Visual Studio 2010 on XP, with the dev environment running IIS Express 7.5.
Polymer has been installed through nuget and seems to work ok otherwise.

**Comment by ebidel** [comment] 2015-04-14 21:40
Can you post a link to your stripped down test page?

**Comment by johnohara** [comment] 2015-04-14 22:47
Hi,

I don't have a staging machine at the moment so ots not easy to get to a web link. Is there any other way I can provide the information?

**Comment by ebidel** [comment] 2015-04-15 18:23
Do you have an index.html file you can post with the bower.json of files you're using. Just need something in order to be helpful :)

**Comment by johnohara** [comment] 2015-04-15 18:37
Eric,
Polymer is brand new to me so you'll have to give me a little guidance. Sure I can sort out an index.html file, but where do I get the bower.json for all the files I'm using?

**Comment by johnohara** [comment] 2015-04-15 19:01
Eric, I have an html file that I've tested which causes the error, but how do I get it to you? I cannot  find where its possible to upload an html file.

**Comment by johnohara** [comment] 2015-04-15 19:12
Eric,

Here's the files you requested (I think) - hope they get to you via this method.

Thanks

John
  ----- Original Message -----

**Comment by miztroh** [comment] 2015-04-15 19:22
You might consider creating a simple test case showing your issue using a service like codepen.io.  For example, here's one I created recently for an issue I reported for the paper-dropdown-menu.

http://codepen.io/anon/pen/vEMOKO

**Comment by ebidel** [comment] 2015-04-15 19:36
Thanks for that. I'm not seeing the CPU fire up on http://codepen.io/anon/pen/vEMOKO. The tab stays around 7%. I'm on a MacBook Pro.

**Comment by miztroh** [comment] 2015-04-15 19:38
@ebidel To clarify, that wasn't meant to be a test case for this issue.  I was just showing how he could go about creating his own test case.

**Comment by ebidel** [comment] 2015-04-15 19:47
Ah sorry! I didn't realize you were a different poster. Lolz

**Comment by johnohara** [comment] 2015-04-15 20:05
Eric - here's a codepen.

http://codepen.io/anon/pen/zxgJyB

**Comment by miztroh** [comment] 2015-04-15 20:15
@johnohara Do you experience the high CPU usage on the codepen example you provided?

**Comment by johnohara** [comment] 2015-04-15 21:19
Actually Johnathan, I'm having trouble getting it to work at all. The word Press should be inside a dropdown menu yet I can see nothing. 

Thanks

John
  ----- Original Message -----

**Comment by miztroh** [comment] 2015-04-15 21:25
@johnohara Looks like the issue is a bad webcomponentsjs path copied from my example.  I didn't notice the issue until now because webcomponentsjs is not required by Chrome.  I copied your example and fixed the path.

http://codepen.io/anon/pen/ogKaey

**Comment by johnohara** [comment] 2015-04-15 21:35
There is no spike when running the page through codepen on my machine. So what does that leave - IIS Express, Firewalls?

Thanks

John
  ----- Original Message -----

**Comment by johnohara** [comment] 2015-04-15 21:41
Actually thinking about it, it doesn't completely elimiate polymer either. We're using elements on the polymer site, where as mine were downloaded from Nuget - there could be a mismatch.

Thanks

John
  ----- Original Message -----

**Comment by miztroh** [comment] 2015-04-15 21:44
I'm not familiar with Nuget.  Does it cache package files or download them directly from GitHub the way bower does?  If the files are coming from GitHub, then the issue is probably somewhere on your end.  You could always use bower to download Polymer, just to be sure.

**Comment by johnohara** [comment] 2015-04-16 10:12
Ok, here's where I'm at.

Paired the page down so it has pure html (no aspx objects). This is identical to the page on codepen.

Result: no change

Removed my polymer components and use links to the external components we know work on cope pen.

Result: no change

Changed IIS express to VS development server

Result: no change

So, its a case of Polymer on Chrome (latest) in my environment.

Next steps: Try and determine whether this only occurs locally or not.

**Comment by johnohara** [comment] 2015-04-16 11:21
Reset Chrome and removed any extensions

Result: slight improvement CPU (60/70%)

Isolated individual polymer components

Result: component causing the issue is core-menu

**Comment by pflannery** [comment] 2015-04-16 13:00
@johnohara have you tried in incognito mode? and have you done a CPU profile snapshot from the chrome profiler tools?

**Comment by johnohara** [comment] 2015-04-16 13:22
Incognito doesn't work.
I couldn't find anything useful from the profiler - I know whats causing it - its that darn core menu when I trigger it from its button - I just don't know why.

**Comment by pflannery** [comment] 2015-04-16 13:33
@johnohara Can you post a gist with a snapshot of the cpu profile? we can use it to find where in the core menu its spending all the time.

**Comment by johnohara** [comment] 2015-04-16 14:51
Hi Peter - welcome to the conversation.

How do I post a .cpuprofile file on gist?

**Comment by pflannery** [comment] 2015-04-16 14:58
@johnohara if there is a problem can you post it via dropbox or similar? thanks

**Comment by johnohara** [comment] 2015-04-17 08:31
https://www.dropbox.com/s/65y5sk15j2ifz2l/CPU-20150416T145745.cpuprofile?dl=0

**Comment by pflannery** [comment] 2015-04-17 12:36
@johnohara thanks for posting the profile. There is no mouse events in that profile to look at. Did you still see the cpu issue when using recording the profile? 

one more thing, is the same issue occurring on the core-menu demo page ? https://www.polymer-project.org/0.5/components/core-menu/demo.html

**Comment by johnohara** [comment] 2015-04-17 14:10
Yes, the CPU issue happened more so when recording the profile.

The issue doesn't happen on the demo page, nor on codepen - it seems that the combination of Polymer + Chrome + IIS Express (or my Visual Studio development environment).

I'm not yet in a position to put in on a proper production box - when i do it will reside on Windows 2012/IIS, so I may get a different result.

The problem I have Peter is that until I know the reason behind the spikes and hopefully supress them, I can't be sure that its not going to crash a production box.

**Comment by johnohara** [comment] 2015-04-21 14:02
Latest update.

I'm confused!

Here's what I have so far.

I'm running a .Net site, so I created a new htm page with no code other than this codepen http://codepen.io/anon/pen/ogKaey.

The codepen does not cause the issue to happen.
The htm page still causes the issue to happen.

I'm testing on a development machine with XP, VisualStudio and IIS Express. I've uploaded the page to a Windows 2012 server running the latest version of IIS, and it still happens when I view the page here.

I've no doubt that Chrome is at the heart of this issue but canot work out why the codepen version works without consuming 100%, and my page does.

Any new ideas?

**Comment by johnohara** [comment] 2015-04-21 14:25
Ok, I have an answer!!!

Having isolated all of the above - the only difference between the codepen and my page was the fact that the paper-menu-button on codepen was immediately bounded by a div, wheras mine wasn't. The parent container contained a further 5000 characters of text.

I made the changes and reuploaded the htm page to the server which had previously resulted in a failed test, and bingo, the CPU was constrained and went to an idle state very quickly.

So it looks as though this is a polymer issue after all, which only shows itself when its parent contains lots of other content, and only on Chrome, not Firefox, but it could also be the case on other browsers too.

**Comment by tjsavage** [comment] 2015-10-23 23:58
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:58 UTC
Labels: 0.5
