### ISSUE TITLE
In-source version is out of date

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer#1085] opened 2015-01-09 17:36 UTC
Looks like we missed a spot w/ the release automation

**Comment by nazar-pc** [comment] 2015-01-12 00:38
Duplicate of #1033?

**Comment by tjsavage** [comment] 2015-10-23 23:26
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:26 UTC
Labels: 0.5
