### ISSUE TITLE
Get the original DOM event from track gesture event

### ISSUE THREAD

**Issue by pomber** [Polymer/polymer#4076] opened 2016-10-19 01:38 UTC
Any reason why the original DOM event is not included in the track gesture event while it is included in `up`, `down` and `tap` events (`sourceEvent` property)?   

I need to call `preventDefault` on the original event to stop the mobile browser refreshing the page when dragging an element to the bottom of the screen.  

My current workaround is to also listen to `touchmove` and call `preventDefault` there.

Here are the docs:
https://www.polymer-project.org/1.0/docs/devguide/gesture-events  

And here (I think) is the source code:
https://github.com/Polymer/polymer/blob/80640c81ed66e320b96c51c7729b8a0792ce95ad/src/standard/gestures.html#L591

**Comment by TimvdLippe** [comment] 2018-02-10 16:10
Closing this as duplicate of #4472 (which contains a little bit more information).

**Closed by TimvdLippe** 2018-02-10 16:10 UTC
Labels: 1.x
