### ISSUE TITLE
Applied CSS mixin as variable cannot be changed using updateStyles

### ISSUE THREAD

**Issue by sz332** [Polymer/polymer#4882] opened 2017-10-12 09:15 UTC
### Description

When creating a two css mixins, then creating a css variable pointing to one mixin, applying this to a div element, and changing it dynamically using updateStyles does not work.

#### Steps to Reproduce
```
    <dom-module id="test-bug">
        <template>
            <style>
                 :host {
                    --my-color: grey;

                    --my-blue-color: blue;

                    --my-simple-setting: {
                        width: 200px;
                        height: 200px;
                        background-color: yellow;
                    }

                    --my-complex-setting: {
                        background-color: green;
                        width: 500px;
                        height: 500px;
                    }

                    --my-setting: var(--my-simple-setting);
                }
                
                #myDiv {
                    @apply --my-setting;
                    background-color: var(--my-color);
                }
            </style>

            <div id="myDiv">

            </div>
        </template>
    </dom-module>

    <script>
        HTMLImports.whenReady(function() {
            class TestBug extends Polymer.Element {

                static get is() {
                    return 'test-bug';
                }

                static get properties() {
                    return {
                        value: {
                            type: Number,
                            value: undefined,
                            observer: "_valueChanged"
                        }
                    }
                }

                _valueChanged(newValue) {
                    this.updateStyles({
                        '--my-setting': 'var(--my-complex-setting)',
                        '--my-color': 'var(--my-blue-color)'
                    });
                }


            }

            window.customElements.define(TestBug.is, TestBug);
        });
    </script>

    <test-bug value="23"></test-bug>
```

#### Expected Results

Width and height values of the div should change to 500px.

#### Actual Results

Width and height values of the div remains 200px after updateStyles() is called. The background color (to blue) is however taken over as expected.

### Browsers Affected
- [X ] Chrome
- [X] Firefox
- [X] Edge
- [?] Safari 9
- [?] Safari 8
- [?] IE 11

### Versions
 Polymer 2 latest

**Comment by azakus** [comment] 2017-10-14 00:15
Updating CSS mixins with `updateStyles` is not supported. I'll make a note to update the docs.

**Comment by TimvdLippe** [comment] 2018-02-20 19:17
This appears to be a duplicate of https://github.com/Polymer/polymer/issues/4159#issuecomment-282443798 We will update the docs to clarify this behavior.

**Closed** 2018-02-26 23:54 UTC
Labels: apply-shim, docs, p2
