### ISSUE TITLE
Support elements defining custom properties values for light dom nodes

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2328] opened 2015-08-20 16:05 UTC
For example, an element that defines color values for its light dom paper-radio-buttons:
```
#container ::content paper-radio-button {
   --paper-radio-button-checked-ink-color: red;
   --paper-radio-button-checked-color: red;
  --paper-radio-button-unchecked-color: red;
}
```

**Comment by miztroh** [comment] 2015-08-20 16:11
@ebidel Duplicate of https://github.com/Polymer/polymer/issues/2188.

**Comment by sorvell** [comment] 2015-08-20 21:46
Good call @miztroh, closing in favor of https://github.com/Polymer/polymer/issues/2188.

**Closed by sorvell** 2015-08-20 21:46 UTC
Labels: enhancement, p2
