### ISSUE TITLE
IE 11 - custom styles not rendering

### ISSUE THREAD

**Issue by mcarey1590** [Polymer/polymer#2467] opened 2015-09-22 14:43 UTC
many of the custom styles (@apply, var) are not being rendered in IE11 until either a few minutes have passed or by resizing the browser. This includes custom styles in polymer elements.

**Comment by azakus** [comment] 2015-11-10 01:36
Do you have a handy reproduction to test? I haven't seen anything crazy myself.

**Comment by azakus** [comment] 2016-01-28 20:19
Closing due to age, please reopen if this is still an issue.

**Closed by azakus** 2016-01-28 20:19 UTC
Labels: css, pending-response
