### ISSUE TITLE
[bug] path.html split error with undefined path

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer#5166] opened 2018-03-28 06:45 UTC
### Description

We got error on `this.get(path)` when `path` is `undefined`

![screen shot 2018-03-28 at 11 00 28 am](https://user-images.githubusercontent.com/697913/38013107-21b7ae24-3279-11e8-9b5d-3f7801a77f15.png)

#### Live Demo
![screen shot 2018-03-28 at 11 01 06 am](https://user-images.githubusercontent.com/697913/38013093-16804764-3279-11e8-99dc-3123620173ee.png)

http://jsbin.com/fipavab/edit?html,console

**Comment by AliMD** [comment] 2018-03-28 07:08
same issue with `this.get(null)`

**Comment by TimvdLippe** [comment] 2018-03-28 09:11
I would consider this an issue in the user code, rather than an issue in the library code. These APIs should not be called with non-{strings,arrays}.

**Comment by TimvdLippe** [comment] 2018-04-03 18:30
We have discussed this issue and concluded that this is working as intended. Mostly because we see no sensible return value in the case of `null` and `undefined`. Returning either case would very likely propagate the actual error to a different part of the application, which would make it significantly harder to debug. Therefore I am closing this issue.

**Closed by TimvdLippe** 2018-04-03 18:30 UTC
Labels: 2.x, api-feedback, enhancement, p2
