### ISSUE TITLE
Dynamically loaded Polymer elements are not shown in Firefox and Safari

### ISSUE THREAD

**Issue by antonmoiseev** [Polymer/polymer#2085] opened 2015-07-15 17:22 UTC
I'm trying to load a Polymer element dynamically with `Polymer.Base.importHref()` and put it on the page. The HTML file containing the element is successfully downloaded, but when I create and insert the element into the page it's not displayed in Firefox and Safari. However `ready()` callback is always invoked and a test log message is printed to the console. Here is a [tiny app](https://github.com/antonmoiseev/polymer-dynamic-loading) that reproduces the issue. I create and insert the element dynamically, but even if I add `<custom-element></custom-element>` to _index.html_ the behavior is identical.

Polymer 1.0.6
Firefox 39.0
Safari 8.0.7

**Comment by sorvell** [comment] 2015-07-16 18:02
It looks like using the `is` attribute on your `dom-module` is not working. If you change this to `id` then it should work. Using `is` is supported so we'll investigate why this isn't working.

**Comment by sorvell** [comment] 2015-07-16 19:47
The root cause is a problem in the custom elements polyfill. Closing this issue in favor of:

https://github.com/webcomponents/webcomponentsjs/issues/351

**Closed by sorvell** 2015-07-16 19:47 UTC
Labels: p1

**Comment by antonmoiseev** [comment] 2015-07-20 13:59
@sorvell thank you. Actually it wasn't intentionally, I mistyped it. `id` works perfectly fine for me.

**Comment by rozzamozza** [comment] 2017-07-20 15:08
I had exactly this issue on Polymer 1.8.0.
The issue was that one of my deep down components was importing itself!
No errors on firefox or on Safari. Just none of the elements were replaced!

removed the import and all was fine

All works fine on chrome but not on Firefox or Safari

**Comment by rozzamozza** [comment] 2017-07-20 15:08
You get the same with IE if you forget to include an import. Chrome is more lax and will use imports from parents
