### ISSUE TITLE
paper-toggle-button on-tap event handler reveals breaking change 

### ISSUE THREAD

**Issue by thomasvogel** [Polymer/polymer#5137] opened 2018-03-02 09:36 UTC
I try this once more. I saw, that my last entry was corrupted somehow :-(

use a paper-toggle-button like this:

1. &lt;paper-toggle-button id="frontToBack" on-tap="_frontToBack"&gt;
2. use the eventhandler for on-tap like this:
        _frontToBack() {
           console.log(!this.$.frontToBack.checked);
        }
3. click on the toggle button

#### Expected Results
With polymer 2.3.x, the console showed 'false' (the value of 'checked' before the click was handled)

#### Actual Results
With polymer 2.4+, the console shows 'true' (the value of 'checked' after the facts)

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 9
- [ x] Safari 8
- [x ] IE 11

### Versions

- Polymer: v2.4.0, v2.5.0
- webcomponents: v1.1.0

**Comment by dimassrio** [comment] 2018-03-04 03:10
Its expected behaviour, the checked attributes when you tap the button is false, use on-checked-changed event instead.

**Comment by TimvdLippe** [comment] 2018-03-06 19:52
Runnable JSBin: http://jsbin.com/rilubipebi/edit?html,console,output While it is a change in behavior, I would actually say the "new" behavior is correct. @azakus WDYT?

**Comment by thomasvogel** [comment] 2018-03-07 07:50
For me, it would be ok to close the issue. I can of course live with the new behavior, if you say that it is correct.

**Comment by TimvdLippe** [comment] 2018-07-31 16:13
I am closing this as working as intended. Thanks for your consideration!

**Closed by TimvdLippe** 2018-07-31 16:14 UTC
Labels: 2.x, needs investigation, p2, regression
