### ISSUE TITLE
restamp is not destroying async loaded light dom element

### ISSUE THREAD

**Issue by ansarizafar** [Polymer/polymer#3893] opened 2016-09-01 07:50 UTC
restamp is not destroying async loaded light dom element even If it is wrapped in a container. Is it a bug or normal behavior. If its a bug, is there any workaround? here is my code

```
  <template is="dom-if" if="{{isAllowed(role)}}" id="page" restamp="true">
        <paper-spinner class="spinner" id="spinner" active="[[isLoading]]" hidden$="[[!isLoading]]"></paper-spinner>
        <div><content></content></div> 
      </template>
```

**Comment by TimvdLippe** [comment] 2017-11-28 19:35
We have analyzed this usecase and concluded that this is working as intended. Since the elements are distributed from the light dom in to the `<dom-if>`, the user of your element is the one managing the node. As such, `<dom-if>` is not allowed to remove (and thus restamp) this node. If you want `<dom-if>` to manage the nodes, you will need to directly add the elements in the dom of `<dom-if>`.

Therefore I am closing this issue as working as intended.

**Closed by TimvdLippe** 2017-11-28 19:35 UTC
Labels: 1.x, dom-if
