### ISSUE TITLE
sinonjs: repository not found

### ISSUE THREAD

**Issue by matheus-pantoja-ir** [Polymer/polymer#5627] opened 2020-02-10 19:03 UTC
### Description
I have Polymer 1.x project, when run `bower install` or `bower update`. [blittle/sinonjs](https://github.com/blittle/sinon.js) dependencie has a problem, repository not found. Apparently the project has moved to other user/repository, [sinonjs/sinonjs](https://github.com/sinonjs/sinon). `bower.json` of polymer will be updated ?

![unnamed](https://user-images.githubusercontent.com/56881415/74180293-0849b700-4c1e-11ea-9928-cb2cc2371d46.png)

### Versions
- Polymer: v1.11.0
- webcomponents: v1.2.7

**Comment by web-padawan** [comment] 2020-02-10 19:06
Duplicate of https://github.com/Polymer/tools/issues/3488

As a workaround, add the following to the `devDependencies` in `bower.json`:

```js
"sinonjs": "Polymer/sinon.js#~1.17.1"
```

**Comment by chiquitoir** [comment] 2020-02-10 19:39
THANK YOU!!!!!!!!!!!!!!!

**Comment by usergenic** [comment] 2020-02-11 21:50
FYI I updated bower.json to point to Polymer/sinon.js and tagged/"released" WCT v 6.5.1 so that `bower install web-component-tester` should work again.

**Comment by arthurevans** [comment] 2020-03-13 21:26
Closing this as a duplicate.

**Closed by arthurevans** 2020-03-13 21:26 UTC
Labels: duplicate
