### ISSUE TITLE
Two polymer instances causes customElementsRegistry to fail

### ISSUE THREAD

**Issue by eavichay** [Polymer/polymer#5283] opened 2018-07-05 08:53 UTC
#### Steps to Reproduce
Create two polymer projects, one is a library, the other is a polymer app
During runtime polymer will define dom-module as custom element. When an external polymer asset is loaded, another instance of polymer (same version, different locations) will also try to define dom-module as a custom element, which will cause an exception.

#### Expected Results
Polymer should auto-detect whether another polymer instance was loaded, If so, should console-warn and abort mounting itself.

#### Actual Results
customElementsRegistry: "dom-module" already defined

### Browsers Affected
Tested on crhome

### Versions
- Polymer: v3.0.2
- webcomponents: none, using chrome

**Comment by eavichay** [comment] 2018-07-05 09:03
Now I See #5095

**Comment by TimvdLippe** [comment] 2018-07-05 10:05
Yes this will be addressed by #5095. Closing this as duplicate of #4134

**Closed by TimvdLippe** 2018-07-05 10:05 UTC
