### ISSUE TITLE
Shadow DOM missing when element is inserted as BackboneJS view

### ISSUE THREAD

**Issue by jfaganUK** [Polymer/polymer#2603] opened 2015-10-21 12:05 UTC
I'm trying to figure out what's going on here. I've been writing a project that uses [Jeremy Fairbank's two-way data binding between Backbone views and Polymer webcomponents](http://blog.jeremyfairbank.com/javascript/polymer-web-components-with-marionette-js/). It has been working really well, until I started upgrading to Polymer 1.0.

Consider this example. When the component is declared in the html it works as it should. When it's part of the Backbone view it does not work. Any thoughts as to what's going on here?

[JS Fiddle example](https://jsfiddle.net/aftersox/3ddj3yL2/1/)

HTML

```
    <link rel="import" href="https://raw.githubusercontent.com/Polymer/polymer/master/polymer.html">
<dom-module id='test-component'>
    <template>
        <h3>Name</h3>
        <div>Hello, my name is {{name}}</div>
    </template>
    <style>
        :host {
            display: block;
            border: 1px solid red;
            padding: 5px;
        }
    </style>
</dom-module>

    <script id="template-test-layout" type="text/template">
        <div id="spot1">spot1</div>
        <div id="spot2">spot2</div>
    </script>

    <script id="template-test-view" type="text/template">
    </script>

    <test-component name="George Washington"></test-component>

    <div id="app-space"></div>
```

JS

```
// The test component
Polymer({
    is: 'test-component'
});

var TestLayout = Marionette.LayoutView.extend({
    el: "#app-space",
    template: "#template-test-layout",
    regions: {
        spot1: "#spot1",
        spot2: "#spot2"
    }
});

var TestView1 = Marionette.ItemView.extend({
    template: "#template-test-view",
    tagName: "test-component"
});

var layout = new TestLayout();
layout.render();

var testView1 = new TestView1();
layout.getRegion('spot1').show(testView1);
```

**Comment by ebidel** [comment] 2015-10-21 19:20
I found an older 0.5 Polymer post on using marionette with polymer elements: http://blog.jeremyfairbank.com/javascript/polymer-web-components-with-marionette-js/

But the root cause, looks to be shady dom. If I force SD before the polymer.html import, it works.

``` js
<script>
    window.Polymer = window.Polymer || {dom: 'shadow'};
</script>```

You may want to try our experimental patch-dom.html library, which teaches frameworks about `Polymer.dom()`: https://github.com/Polymer/polymer/blob/master/src/lib/experimental/patch-dom.html

**Comment by jfaganUK** [comment] 2015-10-25 02:36
This snipped worked like a charm. Thanks.

**Comment by TimvdLippe** [comment] 2017-08-22 07:22
Closing this per above comment. I am unable to run the provided snippet. If you could post a JSBin based on http://jsbin.com/luhaxab/edit?html,output to show the problem we can reopen this issue.

**Closed by TimvdLippe** 2017-08-22 07:22 UTC
Labels: 1.x, interop, p2
