### ISSUE TITLE
PSK's vulcanize incorrectly rendering menu

### ISSUE THREAD

**Issue by felipealbertao** [Polymer/polymer#3152] opened 2015-12-03 19:53 UTC
Left-side menu is shown incorrectly on PSK built app. See screenshot:

<img width="221" alt="screen shot 2015-12-03 at 2 48 04 pm" src="https://cloud.githubusercontent.com/assets/1444489/11571961/f174da62-99cc-11e5-95da-2a780b4ed46c.png">

How to reproduce:

1. Follow the "Build an app" tutorial to build the sample PSK app
2. Run the app with `gulp serve`. The menu will be shown correctly.
3. Run the app with `gulp serve:dist` or deploy it to Firebase as instructed in the tutorial. The menu will appear "broken", as seen in the screenshot above.
4. Comment-out the `vulcanize` task under the `default` task in the `gulpfile.js` file. 
5. Rebuild the app with `gulp` and then `gulp serve:dist` (or redeploy the app to Firebase). Now the menu will be shown correctly.

**Comment by azakus** [comment] 2015-12-04 18:54
Duplicate of https://github.com/PolymerElements/polymer-starter-kit/issues/564

**Closed by azakus** 2015-12-04 18:54 UTC
