### ISSUE TITLE
[0.8] Nested insertion points lose elements after distributeContent

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1480] opened 2015-05-03 17:11 UTC
In the following scenario, ```Polymer.dom(this).children``` returns the ```<content>``` element.
Is this intended? If so, is going through the ```_distributedNodes``` property the correct way to get the *real* children or is there another api call I should be using?

http://jsbin.com/bixero/3/edit?html,output

**Comment by sorvell** [comment] 2015-05-05 13:29
Yes, if I read the example correctly, this is intended behavior. Shady DOM and Shadow DOM share the same design. The distribution of nodes changes rendering but not dom structure. In this case the `<content>` element is a child of the `<x-inner>`. The children of `<x-outer>` get distributed such that they  render in place of the insertion point where they get selected. 

To see nodes distributed to an insertion point, Polymer.dom provides `Polymer.dom(node).getDistributedNodes()`. 

Fwiw, you can also see to which insertion point a given element has been distributed (generally this is not needed too much) using `Polymer.dom(node).getDestinationInsertionPoints()`.

**Comment by Sleeckx** [comment] 2015-05-05 13:45
Thanks Steve, this was exactly what I was looking for. I somehow overlooked this from the primer.

**Comment by Sleeckx** [comment] 2015-05-05 14:32
The reason I bumped on the above question is for the following scenario where somehow the insertion point loses elements after distributeContent: http://jsbin.com/qoputoralu/2/edit

Could this be related to this issue? #1394

**Comment by sorvell** [comment] 2015-05-05 15:15
Definitely looks like a bug or 2 here. I'll investigate. Thanks for the detailed test case.

**Comment by Sleeckx** [comment] 2015-05-06 08:57
Thanks, I also updated the sample case to reflect the latest changes.

**Comment by sorvell** [comment] 2015-05-06 17:13
Currently, `distributeContent` is not smart enough to deal with redistribution. We'll fix it so it does.

In addition, we're planning on adding node mutation api (probably setAttribute and classList) to Polymer.dom so you should only rarely need to provoke distribution manually.

**Comment by sorvell** [comment] 2015-05-06 22:15
Actually, you are right that the precise problem you noted is related to #1394. What I said is also true... fixes for both are on the way.

**Comment by Sleeckx** [comment] 2015-05-07 08:25
Awesome, thanks!

Just to add some context to all of the above, this is the mock-up code of the real-world scenario we've build: http://jsbin.com/tireqatehe/1/edit?html

Adding the Polymer.dom API for adding/removing the attribute in this case and distributing immediately, will indeed eliminate the need to call distributeContent ourselves. Like you said.

**Comment by sorvell** [comment] 2015-05-12 19:18
Fixed via https://github.com/Polymer/polymer/commit/d5070c511ead59311985854f2c06c4148c3925f4

**Closed by sorvell** 2015-05-12 19:18 UTC
