### ISSUE TITLE
shadowRoot.getElementById doesn't seem to work in Safari 10 (Polymer 2.0)

### ISSUE THREAD

**Issue by pghalliday** [Polymer/polymer#4414] opened 2017-03-11 15:55 UTC
### Description

In my units tests when I call `myElement.shadowRoot.getElementById` in chrome it works fine but in Safari 10 it always returns `null`. As a workaround I have found that `myElement.shadowRoot.querySelector` works on all browsers I tested

#### Live Demo

Couldn't get a live demo to work with Polymer 2.0 :(

#### Steps to Reproduce

- `polymer init` a new `polymer-2-application`
- Create the following `src/list.html`

```html
<link rel="import" href="../../../bower_components/polymer/polymer.html">

<dom-module id="my-list">
  <template>
    <template is="dom-repeat" items="[[items]]">
      <div id="[[_itemId(item)]]">[[item.value]]</div>
    </template>
  </template>
  <script>
    class MyList extends Polymer.Element {
      static get is() {
        return 'my-list';
      }

      static get properties() {
        return {
          items: Array,
        };
      }

      _itemId(item) {
        return 'item' + item.id;
      }
    }
    customElements.define(MyList.is, MyList);
  </script>
</dom-module>
```

- Create the following `test/list.html`

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

    <title>my-list test</title>

    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
    <script src="../../web-component-tester/browser.js"></script>

    <link rel="import" href="../src/list.html">
  </head>
  <body>
    <test-fixture id="myList">
      <template>
        <my-list></my-list>
      </template>
    </test-fixture>
    <script>
      describe('my-list', function() {
        var myList;

        beforeEach(function(done) {
          myList = fixture('myList');
          myList.items = [{
            id: 1,
            value: 'item 1',
          }, {
            id: 2,
            value: 'item 2',
          }, {
            id: 3,
            value: 'item 3',
          }];
          flush(done);
        });

        it('should display the items (querySelector)', function() {
          expect(myList.shadowRoot.querySelector('#item1').textContent).to.eql('item 1');
          expect(myList.shadowRoot.querySelector('#item2').textContent).to.eql('item 2');
          expect(myList.shadowRoot.querySelector('#item3').textContent).to.eql('item 3');
        });

        it('should display the items (getElementById)', function() {
          expect(myList.shadowRoot.getElementById('item1').textContent).to.eql('item 1');
          expect(myList.shadowRoot.getElementById('item2').textContent).to.eql('item 2');
          expect(myList.shadowRoot.getElementById('item3').textContent).to.eql('item 3');
        });
      });
    </script>
  </body>
</html>
```
- Run `polymer test` (I have chrome and safari 10 installed so both browsers run tests)

#### Expected Results

Both tests pass in chrome and safari

#### Actual Results

Both tests pass in chrome but the second test fails in safari as `getElementById` always return `null`

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer CLI: v0.18.0-pre.13
- Polymer: v2.0.0-rc.2
- webcomponents: v1.0.0-rc.5

**Comment by kevinpschaaf** [comment] 2017-03-12 11:36
Thanks for the report, closing as dupe of https://github.com/webcomponents/shadydom/issues/52.

**Closed by kevinpschaaf** 2017-03-12 11:36 UTC
