### ISSUE TITLE
dom-repeat.set does not work properly with previously used array

### ISSUE THREAD

**Issue by miyconst** [Polymer/polymer#2424] opened 2015-09-08 12:34 UTC
I have array of objects with arrays which can be modified outside of Polymer by third party library. I don't want to observe changes in the object, instead I want to refresh entire template. For this purpose I try the following code:

``` js
var items = this.items;
this.set("items", []);

setTimeout(function () {
    this.set("items", items);
}.bind(this));
```

But this does not work. `dom-repeat` does not reflect changes in the array.
Here is a demonstration: https://jsfiddle.net/g1L1r2Lm/1/

Is there a way to force full template refresh/restamp?

**Comment by warpech** [comment] 2015-09-09 10:46
+1

**Comment by tylerl0706** [comment] 2015-11-20 22:47
instead of doing

`var items = this.items;`

try:

`var items = this.get("items");`

here's a fiddle:
https://jsfiddle.net/g1L1r2Lm/2/

:) let me know if that's what you're looking for!

**Comment by danostrowski** [comment] 2016-01-20 00:37
I think this is also the problem I'm having.

Here is a jsfiddle of a simplification of what I'm doing: https://jsfiddle.net/1x1mxrze/

I have a master data model with an array of objects. I want my component to be able to display these objects. (In my case, this array is a property of a larger object, but not in this example.)

You'll note if you inspect that even though I keep setting `this.systems` to a larger and larger array of objects, the template stays the same. (And if you break after `this.set('systems', [])` the template has updated to NOT render any nodes.)

Interestingly, on my version of Polymer (1.2.3 according to it's bower.json) locally, I get an error because in _applyFullRefresh the `keys` array ends up having keys (such as `#0`) for the original objects that I set in there, but `undefined` for any additional objects. (It looked to me like the `WeakMap` in `Polymer.Collection` was not being fed the objects that the collection hadn't seen before? I'm not sure.)

I don't know if this jsfiddle will help highlight this issue, but I thought I'd add it.

**Comment by TimvdLippe** [comment] 2017-08-21 15:06
I think this is fixed in Polymer 2: http://jsbin.com/maluxinara/edit?html,console,output The initial state is 1,2,3,4, after 1 second it changes to 2,3,4,5 but memoizes the previous array. Then another second later the original array is assigned again. Therefore I am closing this issue. If I missed a step in the reproduction case, please let us know!

**Closed by TimvdLippe** 2017-08-21 15:06 UTC
Labels: 1.x, databinding, enhancement, p2
