### ISSUE TITLE
Bindings on a child element's sub-property is not setup if a parent creates a binding from a non-existing sub-property to the child's property

### ISSUE THREAD

**Issue by justincy** [Polymer/polymer#3300] opened 2016-01-15 22:13 UTC
I discovered some strange behavior regarding data bindings of sub-properties. It occurs when a parent element binds a sub-property to the property of a child. If the parent's sub-property does not initially exist but the main property does (i.e. `data` exists but not `data.prop`) and the child also binds to a sub-property of the non-existing value then bindings never get setup properly in the child.

Look at this example: http://jsbin.com/nuqujedivu/edit?html,console,output

I have a sub-property of a child bound to the value of an input element. Typing in the input element doesn't update the sub-property or send any notifications (you should see console statements from an observer in the child). To make it work you just have to comment out the default value of the `data` property on the parent element.

The work-around is unexpected because in both cases the sub-property does not exist.

I believe this only happens if both the parent and child are using sub-properties.

I don't know if it ought to be considered a bug. I mostly want to know if there's a workaround for my use case. I have nested data from an API that I pass to nested Polymer elements. I want elements to be instantiated and bindings to work even if their respective properties do not exist in the data returned by the API.

**Comment by miztroh** [comment] 2016-01-15 22:17
This might be related to https://github.com/Polymer/polymer/issues/2360.

**Comment by justincy** [comment] 2016-01-15 22:32
@miztroh I think you're right. @sjmiles summarizes the issue well:

>  leading to an inconsistency (and scenarios where it's impossible to control an element value with defaulting

That's exactly what I'm struggling with.

**Comment by TimvdLippe** [comment] 2018-02-06 23:27
This appears to be a duplicate of #2360 which has been fixed in Polymer 2. For more information see https://github.com/Polymer/polymer/issues/2360#issuecomment-363534542

**Closed by TimvdLippe** 2018-02-06 23:27 UTC
Labels: 1.x, databinding
