### ISSUE TITLE
Polymer 3 preview should not reference webcomponents with relative path

### ISSUE THREAD

**Issue by obany** [Polymer/polymer#4904] opened 2017-10-26 11:33 UTC
### Description
The code at line 1 of https://github.com/Polymer/polymer/blob/3.0-preview/lib/legacy/legacy-element-mixin.js#L1 import webcomponents using a relative path

`import '../../../../@webcomponents/shadycss/entrypoints/apply-shim.js';`

This should really let module resolver handler this for you, in case your webcomponents are somewhere else.

`import '@webcomponents/shadycss/entrypoints/apply-shim.js';`

### Versions
v3 preview

**Comment by TimvdLippe** [comment] 2017-10-26 11:35
Named imports can not be loaded in the browser, as the browser does not know where the path links to. You would need to rewrite the named path to the relative path if you want to load this file. Since Polymer should be loadable with transpilations, named paths would not work.

**Comment by obany** [comment] 2017-10-26 11:41
That's true it just looks like a step backwards in creating a deep dependency from one library to another.

**Comment by TimvdLippe** [comment] 2017-10-26 11:48
3.0-preview is auto upgraded from the 2.0 version. In https://github.com/Polymer/polymer/blob/master/lib/legacy/legacy-element-mixin.html there is already a deep dependency to the apply-shim, but this time as html import. In that sense, there is no functional difference between 2 and 3 other than the syntactic notation.

**Comment by justinfagnani** [comment] 2017-11-07 18:54
Since this is how the web platform works, I'm going to close this as working as intended (or needed). We're looking at ways to make imports more ergonomic as a separate effort.

**Closed by justinfagnani** 2017-11-07 18:54 UTC
