### ISSUE TITLE
upward binding inside repeat template - read-only and read-write

### ISSUE THREAD

**Issue by d1manson** [Polymer/polymer#2278] opened 2015-08-14 18:17 UTC
**Originally posted on SO [here](http://stackoverflow.com/q/32012789/2399799)**.

Suppose I have a custom `x-child` element with the following properties:

```
properties: {
    prop_read_write: {type: Number, value: 1, notify: true},
    prop_read_only: {type: Number, value: 101, notify: true, readOnly: true}
}
```

If I put that inside a custom `x-parent` in the following way...

```
<x-child prop_read_write="{{parent_a}}" prop_read_only="{{parent_b}}"></x-child>
```

...I get what I expect, which is that the default values are bound upward.  However if I do something similar within a repeat I can't work out how to get that same behavior.

```
<template is="dom-repeat" items="{{kids}}">    
  <x-child prop_read_write="{{item.a}}" prop_read_only="{{item.b}}"></x-child>
</template>
```

I've fleshed this out a bit further in a proper test page - see gist [test.html](https://gist.github.com/d1manson/a8858a9f8b230c3b8eaa).

The output looks like this:

[![rendered output](http://i.stack.imgur.com/Dn2g0.png)](http://i.stack.imgur.com/Dn2g0.png)

**Comment by azakus** [comment] 2016-01-28 00:07
There's two reasons why this behavior happens:

1. Default values in the `properties` object are only applied if there is no incoming state from property bindings or attributes
1. When a property is set to an object, the any bindings to the subproperties of that object are set at that time.

There is no good workaround for the behavior right now, other than using the `readOnly` metadata property, which is why `prop_read_only` isn't affected.

We are considering ways of improving this behavior.

**Comment by sorvell** [comment] 2017-11-29 03:00
Sorry for the long delay on this. I believe this behavior is working as intended so we're going to close this issue.

Polymer's data binding system works on a "push" model. When data is pushed to elements, they react. Any data bound into an element overrides an element's default property value.

By design a path binding (e.g. `{{item.a}}`) receives data when the root `item` property changes.  This means a binding to `{{parent_a}}` behaves differently than a binding to `{{item.a}}`.

*What you can do instead in this case...* We recommend avoiding a 2-way binding when you need to populate repeated data via a default property generated within an element. Instead, add an event listener to the element and set the data yourself (e.g. something like `on-prop_read_write-changed="_popuplateItemA"`). Hope that helps.

**Closed by sorvell** 2017-11-29 03:00 UTC
Labels: 1.x, databinding, dom-repeat, p1
