### ISSUE TITLE
dom-repeat errors when source data updated via splice (polymer version)

### ISSUE THREAD

**Issue by mfrost66** [Polymer/polymer#2064] opened 2015-07-10 16:26 UTC
Using splice to update source data for a dom-repeat causes polymer error/fail (_applySplicesArraySort)

See [plunker](http://plnkr.co/edit/K9JbrOiCWHAKxGGXGVUA) for example

Edit: replaced description with example

**Comment by kevinpschaaf** [comment] 2015-07-13 16:46
This looks like a duplicate of #2009, which is a P1 issue we're working to resolve.

**Closed by kevinpschaaf** 2015-07-13 16:46 UTC
