### ISSUE TITLE
Angular binding does not work in shady dom.

### ISSUE THREAD

**Issue by jacobclevenger** [Polymer/polymer#1722] opened 2015-06-02 15:49 UTC
The angular curly braces delimiter does not seem to work inside of Polymer elements.

Here is some sample code.

``` html
<section ng-controller="appCtrl">
    <paper-material elevation="1" ng-repeat="video in videos">{{video.title}}</paper-material>
</section>
```

This should output the videos title in the paper material elemtn, but instead it outputs "{{video.title}}". I have tried changing the angular delimiters to "[[ ]]", but still get the same result. Using "ng-bind" seems to work though.

``` html
<section ng-controller="appCtrl">
    <paper-material elevation="1" ng-repeat="video in videos" ng-bind="video.title"></paper-material>
</section>
```

This will output the videos title. 

This only seems to happen if the angular controller is declared outside of the polymer element and then the binding used inside an element. This worked before in Polymer 0.5, so I am guessing that it has something to do with shady dom.

**Comment by zishanj** [comment] 2015-06-02 17:51
I guess you should use some other delimiter like `## ##`, because both brackets delimiter are used by Polymer.

**Comment by Wheately** [comment] 2015-06-02 18:09
The output is the same either way. I wasn't very clear on the output when I posted this, so I will clarify real quick. 

When I use curly braces, it outputs the title and the delimiter, so it looks like this: 
```Video Title{{video.title}}```

When I change it to using ```## ##```, the output looks like this:
```Video Title##video.title##```

So it still outputs the right value, but it also appends the delimiter and variable.

**Comment by justinfagnani** [comment] 2015-06-02 21:08
@Wheately I suspect Shady DOM is the culprit, but I would have thought the symptom would be just a little different. So to check my assumptions, can you create a minimal reproduction I can look at? Either Bower installable, or a .zip with dependencies (dev versions) included. Thanks!

**Comment by Wheately** [comment] 2015-06-02 21:55
@justinfagnani I created a minimal reproduction, here is the link: https://drive.google.com/file/d/0ByZ5z4vVbzCRYkJldHUxQXQtY1E/view?usp=sharing

**Comment by TimvdLippe** [comment] 2017-08-03 04:00
@robdodson do you know if this has been fixed since?

**Comment by robdodson** [comment] 2017-08-04 02:42
I don't know about Angular 1 but Angular 2.x seems to work fine.

**Comment by TimvdLippe** [comment] 2017-08-20 15:52
Closing per above comment. Please let us know if you are still running into issues with interopability with Angular.

**Closed by TimvdLippe** 2017-08-20 15:52 UTC
Labels: 1.x, interop, p3
