### ISSUE TITLE
Ripple effects get stuck

### ISSUE THREAD

**Issue by dheera** [Polymer/polymer#2538] opened 2015-10-07 14:44 UTC
Occasionally the ripple effect on paper elements get stuck before the animation finishes.
Observed on Chrome/Android, does not occur on Chrome/Linux.

Occurs on both my own creations with 1.1.4 as well as Polymer's official website, screenshot below.

This may appear to be a duplicate of
https://github.com/Polymer/paper-ripple/issues/16
but it seems that Polymer/paper-ripple is no longer being used so I'm not sure if this issue is being tracked?

![2015-10-07 05 47 12](https://cloud.githubusercontent.com/assets/1786477/10340890/bf50fa0e-6d01-11e5-80da-059a6d5b0ad1.png)

**Comment by ebidel** [comment] 2015-10-07 16:40
This is a really common problem, I'd love us to come up with a way to fix it.

The problem comes up when the browser's main thread gets eaten up during the animation. An example is a page navigation or some other JS that needs to run during the animation. It causes the jank.

I covered one way to handle this in our [Polymer Summit Performance Patterns talk](https://youtu.be/Yr84DpNaMfk?t=17m52s).

**Comment by ebidel** [comment] 2015-10-07 16:41
Reading your post again, it looks like a slightly different issue and a dupe of https://github.com/Polymer/paper-ripple/issues/16

**Closed by ebidel** 2015-10-07 16:41 UTC
