### ISSUE TITLE
Adding passive event listeners

### ISSUE THREAD

**Issue by a1626** [Polymer/polymer#4393] opened 2017-03-08 06:43 UTC
### Description

DevTool of chrome canary in `verbose` mode gives a violation

>[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

This violation comes for `touchstart` and `mousewheel` events

#### Steps to Reproduce

1. Create a small demo application using Polymer
2. Open the application in `chrome canary`
3. In `console` of `devTool` switch level to verbose.

### Versions

- Polymer: v1.X.X
- webcomponents: vX.X.X

**Comment by khammami** [comment] 2017-03-10 10:48
I analyzed my app with [Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) 
![2017-03-10_113815](https://cloud.githubusercontent.com/assets/297917/23792495/667a081a-0587-11e7-9ae4-5e53d0582322.png)

it suggest to uses passive listeners to improve scrolling performance.

**Comment by wingliu0** [comment] 2017-03-14 17:25
@khammami I got the same warning too. But the one adding non-passive listeners is polymer itself.. and some iron component. How should we replace that?

**Comment by khammami** [comment] 2017-03-14 18:08
Hi @wingliu0, here what I found about [passive events](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md). touch listeners should be annotated with {passive: true}. I believe the best way to replace them is by reporting each non passive listener you find to the team.

**Comment by wingliu0** [comment] 2017-03-14 18:46
@khammami  true, but will they still maintain the polymer 1.x?

**Comment by khammami** [comment] 2017-03-15 07:46
@wingliu0 I think so, at least till the final release of v2

**Comment by ebidel** [comment] 2017-03-22 17:47
Dupe of https://github.com/Polymer/polymer/issues/3604

**Closed by ebidel** 2017-03-22 17:47 UTC
