### ISSUE TITLE
Template with dom-if chokes on HTML comments

### ISSUE THREAD

**Issue by SoftMemes** [Polymer/polymer#1982] opened 2015-06-29 13:30 UTC
Having a HTML comment inside a dom-if leads to an attempt to set "display" on undefined resulting in an uncaught exception at line 3672 of polymer.html (v1.0.5).

**Comment by kevinpschaaf** [comment] 2015-06-29 21:33
Closing as duplicate of https://github.com/Polymer/polymer/issues/1786

**Closed by kevinpschaaf** 2015-06-29 21:33 UTC
