### ISSUE TITLE
Dom-if inside an app-grid: Unexpected gap 

### ISSUE THREAD

**Issue by santanubasu** [Polymer/polymer#4820] opened 2017-08-29 18:43 UTC
Unclear if this is a bug or the expected behaviour, but here it is.  Take this simple example:

```
<base href="http://polygit.org/polymer+:master/components/">

<script>
    ShadyDOM = {
        force: true
    }

</script>
<script src="webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="polymer/polymer-element.html">
<link rel="import" href="app-layout/app-grid/app-grid-style.html">
<link rel="import" href="polymer/lib/elements/dom-if.html">

<my-element>
</my-element>


<dom-module id="my-element">
    <template>
        <style is="custom-style" include="app-grid-style">
            :host {
                --app-grid-columns: 10;
                --app-grid-gutter: 10px;
                --app-grid-expandible-item-columns: 2;
            }

            .item {
                border:1px solid black;
            }
        </style>
        <div class="app-grid">
            <template is="dom-if" if="[[!display]]" restamp=true>
                <div class="item">Hello</div>
            </template>
            <div class="item">World</div>
        </div>
    </template>
</dom-module>

<script>
    class MyElement extends Polymer.Element {
        static get is() {
            return 'my-element';
        }

        static get properties() {
            return {
                display:{
                    type:Boolean,
                    value:false,
                    notify:true
                }
            }
        }
        constructor() {
            super();
        }

        connectedCallback() {
            super.connectedCallback();
        }
    }

    customElements.define(MyElement.is, MyElement);

</script>
```

(JSFiddle is giving me some issues running this, but if you simply drop it into a browser directly it behaves in the expected unexpected way)

I expect to see two grid cells, side by side, one with Hello, and the other with World.

What I actually see is the cell with Hello, followed by an empty cell that contains the dom-if element, followed by the cell with World.

It appears the content inside the dom-if has been lifted out of it, placed in the layout, and then the dom-if has been retained as a distinct element in its own cell, which is not what I expect.

Either I'm using dom-if incorrectly, or I don't understand the expected behaviour, or there's a bug somewhere.  I'm not sure yet which it is, but if anyone can chime in that'd be great, thanks

Tested on Chrome 55.  Polymer 2.

**Comment by web-padawan** [comment] 2017-08-29 20:13
Should be the same as #4773

**Comment by arthurevans** [comment] 2017-08-29 20:25
Closing as duplicate of #4773.

**Closed by arthurevans** 2017-08-29 20:25 UTC
Labels: duplicate
