### ISSUE TITLE
Styling master document from stylesheets defined in html is deprecated (bug)

### ISSUE THREAD

**Issue by touseefbsb** [Polymer/polymer#4867] opened 2017-10-05 14:05 UTC
I create a polymer 2 starter kit project from polymer cli and after running I checked the console on opera and found following error, 

![console2](https://user-images.githubusercontent.com/11542189/31231330-02fb4a24-aa00-11e7-9903-c298577329b2.PNG)

app seems to work fine but I thought this error/warning might be worth considering for the polymer team :)

**Comment by web-padawan** [comment] 2017-10-05 16:15
Duplicate of #4679. Fixed by #4849

See [this comment](https://github.com/Polymer/polymer/issues/4679#issuecomment-333187751) explaining why this warning appears regardless of the fix.

**Closed** 2017-10-14 00:16 UTC
