### ISSUE TITLE
Polymer 3 build define method does not respect absolute urls

### ISSUE THREAD

**Issue by rdehuyss** [Polymer/polymer#5316] opened 2018-08-09 10:26 UTC
### Description
When building for production and creating a bundle where inlineScripts is set to false, the bundle is loaded using this method `<script>define(['shared_bundle_1.js']);</script>`

If one integrates a webcomponent with for example Drupal, the shared_bundle_1.js is located on a fixed url (e.g. /sites/subs/themes/psp/components/month-picker/shared_bundle_1.js) for browser caching.

If you then set the shared_bundle_1.js url thus `<script>define(['/sites/subs/themes/psp/components/month-picker/shared_bundle_1.js']);</script>`, to an absolute path and the browser navigates to a page /node/14/..., the browser requests the following url: `https://blabla.com/node//sites/subs/themes/psp/components/month-picker/shared_bundle_1.js`

This returns a 404. The correct url would be `https://blabla.com/sites/subs/themes/psp/components/month-picker/shared_bundle_1.js`

#### Steps to Reproduce
1. Create a polymer 3 app
2. Use the following polymer.json

```    
    {
        "npm": true,
        "moduleResolution": "node",  
        "builds": [
            { 
            "name": "es6prod",	  
            "preset": "es6-bundled",
            "addServiceWorker": false,
            "bundle": {
                "inlineCss": true,          
                "inlineScripts": false,      
                "rewriteUrlsInTemplates": true, 
                "sourcemaps": true,     
                "stripComments": true
            }
            }
        ]
    }
```
3. run polymer build
4. navigate to build\es6prod folder
5. create any new folder (e.g. node)
6. copy the index.html file to the node folder
7. edit the copied index.html and change  `<script>define(['shared_bundle_1.js']);</script>` to  `<script>define(['/shared_bundle_1.js']);</script>` (thus creating an absolute link)
8. start simple http-server in build\es6prod folder
9. go in a browser to http://localhost:8080/index.html => all is ok
10. go in a browser to http://localhost:8080/node/index.html => :-(

#### Expected Results
I expect the define method to follow http standards. Other types of navigation work (e.g. ../).

#### Actual Results
See above

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 11
- [ x] Safari 10
- [ x] IE 11

### Versions
- Polymer: v3.0.2
- webcomponents: v2.0.2

**Comment by TimvdLippe** [comment] 2018-08-09 12:56
@jsilvermist is correct. This is a duplicate of https://github.com/Polymer/tools/issues/532

**Closed by TimvdLippe** 2018-08-09 12:56 UTC
