### ISSUE TITLE
Elements get attached several times with webcomponents-lite.js

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/polymer#2702] opened 2015-11-09 12:48 UTC
Check out www.pigments.io, I'm using webcomponents-lite.js here. It's built in combination with meteor (though I'm barely using any meteor features here as of yet) and as you can see in the console the console log for 'attached' get's called three times for my element. This happens with any element that I am using on my site. With shadow dom/webcomponents.js this does not happen.

**Comment by azakus** [comment] 2015-11-09 18:10
@sorvel This looks like a shadowdom vs shadydom issue. With `?dom=shadow` flag, attached is only fired once in Chrome as well.

**Comment by AndreasGalster** [comment] 2015-11-09 18:15
A few hints that I can give here: I've tested it out with removed the meteor router. When using no router and just having a standard template rendered the meteor way, the element gets initialized just once (but not properly it seems).

If you do the following after the page has loaded:
FlowRouter.go('/emailtoshop');

And then: 
FlowRouter.go('/landing'); 

You will see it only initializes the event once when it switches routes and attaches new DOM/the custom element to the page. Hope this might be useful for the investigation.

**Comment by ebidel** [comment] 2015-11-09 19:01
This doesn't explain the difference between navtive sd and shady, but http://jsbin.com/yisidutafu/edit?html,output only attaches once for me. It makes me wonder what your app/meteor is doing.

**Comment by AndreasGalster** [comment] 2015-11-10 04:32
The meteor app is pretty bare bones, I'm pretty sure it's related to whatever the router is doing.

https://github.com/AndreasGalster/PolymerFlowrouter

Here's a repo to reproduce. You'll need meteor installed, then run meteor in the root directory. I've posted my observations in the linked issue.

**Comment by kevinpschaaf** [comment] 2016-02-18 20:38
@AndreasGalster Can you host a runnable reproduction case so we can take a look?  Sorry for the delay.

**Comment by TimvdLippe** [comment] 2017-08-11 02:12
Closing as we don't have a runnable JSBin. Please reopen if you can reproduce it in JSBin.

**Closed by TimvdLippe** 2017-08-11 02:12 UTC
Labels: 1.x, needs investigation, p1, pending-response
