### ISSUE TITLE
Arrays: multiple calls to 'set' or 'splice' messes up Collection keys

### ISSUE THREAD

**Issue by robrez** [Polymer/polymer#2667] opened 2015-11-02 16:36 UTC
There was a question today in the Polymer G+ community page...

[How do I swap two elements in an array](https://plus.google.com/u/0/+DanielToussaint/posts/bEjZYmqBxpr)

It appears that multiple sets or splices causes some problems w/ Collection keys. Eg: 1st `set` or `splice` works okay, 2nd fails.

Here is a jsbin:  http://jsbin.com/rupati/edit?html,output

Maybe this is related to / the same as:  https://github.com/Polymer/polymer/issues/2248

The console shows this error:

```
TypeError: Cannot read property '0' of undefined
    at Polymer.Collection._parseKey 
```

**Comment by azakus** [comment] 2015-11-05 18:58
The errors with the splice & set cases are a side effect of https://github.com/Polymer/polymer/issues/1913 (dom-repeat: Duplicate values result in unsynchronized data).  Since there is a point in time where one item is duplicated in the array (before the 2nd item overwrites the first), the collection can get out of sync.

Workaround is to ensure there are never duplicate items. e.g. splice both out, splice both back in.

**Comment by rogerta** [comment] 2015-12-29 20:52
@azakus : your workaround assumes duplicate items in an array is an error, which is not always true (for example, the user sets the values of the array).  In this example:

https://jsbin.com/qixufahego/edit?html,output

the javascript console shows:
```
Key for array[0] key=#1
Key for array[1] key=#1
setItem(key0, "toto")
Key for array[1] key=undefined
```
and the first and last lines are wrong.

The problem seems to be that keys in ```pmap``` are compared by value instead of by reference.  If array items are wrapped in objects though they would be compared by references.  This seems to do the trick:

http://jsbin.com/wubarenufi/edit?html,output

The javascript console now shows:

```
Key for array[0] key=#0
Key for array[1] key=#1
setItem(key0, "toto")
Key for array[1] key=#1
```

So another workaround if duplicate primitives are required is to wrap them in objects.

This wrapping could be done inside Collections.  In the ctor, instead of:
```
this.store = userArray.slice();
```
do:
```
this.store = [];
for (var i = 0; i < userArray.length; ++i) {
  store.push({value: userArray[i]});
}
```
However, methods like ```getKey()``` and ```removeKey()``` become O(n) running time.  It also requires that calls to ```remove()``` and ```getKey()``` be passed items in the array and not copies.  Functions like ```Polymer.set()``` and ```Polymer.notifyPath()``` seem to do that already.

**Comment by ergo** [comment] 2016-12-16 15:41
Leaving this as an example that worked for me for function that moves elements up/down by an index:

            columnPosition: function (event) {
                var ix = event.detail.index;
                if (event.type === 'column-position-minus') {
                    if (ix > 0) {
                        var left = this.splice('columns', ix - 1, 1)[0];
                        var right = this.splice('columns', ix - 1, 1)[0];
                        this.splice('columns', ix - 1, 0, right);
                        this.splice('columns', ix, 0, left);
                    }
                }
                else if (ix < this.columns.length - 1) {
                    var left = this.splice('columns', ix, 1)[0];
                    var right = this.splice('columns', ix - 1, 1)[0];
                    this.splice('columns', ix, 0, right);
                    this.splice('columns', ix + 1, 0, left);
                }
            },

**Comment by arthurevans** [comment] 2016-12-19 19:41
@rogerta This is a documented limitation of the data binding system in 1.x: we don't support duplicate array items (and by extension, arrays of primitives are not well-supported). The recommendation here is to wrap primitives into objects so they're unique.

https://www.polymer-project.org/1.0/docs/devguide/model-data#work-with-arrays

**Comment by arthurevans** [comment] 2016-12-19 19:42
(Looks like you already updated your jsbin, but I'm leaving the comment here for other folks who may come across this issue.)

**Comment by TimvdLippe** [comment] 2017-08-22 13:24
Closing this issue as the original JSBin shows that it is working as intended. `Polymer.Collection` was removed, which was the root cause for this issue 🎉

**Closed by TimvdLippe** 2017-08-22 13:24 UTC
Labels: 1.x, p1
