### ISSUE TITLE
Double observer call with same property values

### ISSUE THREAD

**Issue by Yavanosta** [Polymer/polymer#4989] opened 2017-12-12 14:47 UTC
### Description
In some observers configuration, observer will be called twice with same property values.

#### Live Demo
https://jsfiddle.net/dw5n0n6o/3/

#### Steps to Reproduce
1. Open fiddle
2. Open console
3. You will see that `setPropC` method called twice with same prop values.

#### Expected Results
Observer should be called only once for each property set.

#### Actual Results
Observer called twice with same properties.

### Browsers Affected

- [V] Chrome
- [V] Firefox
- [V] Edge
- [V] Safari 9
- [V] Safari 8
- [V] IE 11

### Versions

- Polymer: v2.3.1

**Comment by luochenhuan** [comment] 2017-12-14 03:07
(claim: I don't work in Polymer team)
_Observer called twice_ is the expected behavior.

`setPropC(propA, propB)` will be called whenever propA **OR** probB is changed. 
The first `setPropC` is invoked when propA is set by `this.propA = 'a';`
The second `setPropC` is invoked when propB is set by `func setPropB(propA)`. 

But I don't understand why the first console output is not 

> setPropC a undefined

JS or Polymer must have some underlying mechanism to figure out the dependency relationships and set `propB` before printing to console.

[this demo](https://jsfiddle.net/luochenhuan/f9e2hag2/) explains clearly.

**Comment by romulocintra** [comment] 2018-01-11 21:15
@TimvdLippe  this looks like outdated could be closed no !?

**Comment by TimvdLippe** [comment] 2018-01-15 13:50
After re-evaluating https://github.com/Polymer/polymer/issues/4989#issuecomment-351595419 this behavior is as expected. The reason you receive the same value twice is because we re-fetch the most up-to-date value every time we invoke observers. Since the order of effects is strict, at the point in time the value has been updated to `setPropC` and that is passed on twice.

Since changing this behavior would be a major breaking change, I am closing this issue as working as intended.

**Closed by TimvdLippe** 2018-01-15 13:50 UTC
Labels: 2.x, bug, p2
