### ISSUE TITLE
Style is lost if parent element wraps content of children

### ISSUE THREAD

**Issue by steren** [Polymer/polymer#1087] opened 2015-01-10 23:47 UTC
Have a  look to this Plunker:
http://plnkr.co/edit/g4wXPXuH9J3ZKD4QTJor?p=preview

If in an element, I use this template:
```
  <template>
    <div>
      <content></content>
    </div>
  </template>
```
and in an element that extends it, I style some part:
```
  <template>
    <style>
    polyfill-next-selector { content: 'h2'; }
    ::content h2 { color: red; }
    </style>
    <shadow>
      <content select="h2"></content>
    </shadow>
  </template>
```
The `h2` is not appearing with the style that the children element should give.
It appears correctly if I remove the `<div>` around the `<content>` in the parent template.

Am I doing something wrong? Is this intended behavior? a bug ?

**Comment by zoechi** [comment] 2015-01-12 09:35
Can you please edit your post and wrap inline code with backticks (`` `code here` ``) to ensure that they are shown.

**Comment by steren** [comment] 2015-01-12 11:48
Sorry about that. Done.

**Comment by Nevraeka** [comment] 2015-01-12 12:32
@steren - Here is a fixed (as far as I can see) solution for this. This is not a bug. You had wrapped these inside `<shadow>` tags but you don't need too. I removed those and added the div to your name-tag template (as in your code). 

One other thing is I am unsure why you are extending your elements. Custom elements will only inherit prototypes. HTML view code will not be inherited. Let me know if I got your example correct (as you were thinking it should work). Thanks.  

http://plnkr.co/edit/49EcSGaBiOsDcbD4doXy?p=preview

**Comment by steren** [comment] 2015-01-12 14:50
@Nevraeka Thanks for the feedback.

My use case was this one:
I wanted to create a component that added a basic "card" style + methods.
Then I wanted to create specific components, that would inherit from the style and methods of my card component but have more specific DOM structure and methods.

In your example, you removed the `<shadow>` tags, as we can see, we don't see the `<hr>` added by the parents anymore. This means that the DOM introduced by the parent cannot be used in the child. I would expect to be able to use it as described in [the doc](https://www.polymer-project.org/docs/polymer/polymer.html#extending-other-elements)

**Comment by Nevraeka** [comment] 2015-01-12 15:26
@steren - I see what you mean now. `<shadow>` does add some interesting additional use cases for extending. Take a look at this and tell me if this works for you. - 
http://plnkr.co/edit/49EcSGaBiOsDcbD4doXy?p=preview

**Comment by steren** [comment] 2015-01-12 21:28
Indeed, things could get quite interesting, but also rather complex with imbricated shadow doms.

I added a `<p>Pre</p>` and `<p>Post</p>` tag to illustrate why I think your solution is not enough:
I would like that any content declared inside the `<shadow> ` tag of the children appear between the `Pre` and `Post`. Also, I want that any `<h2>` content to be red.
If the parent content is surrounded by `<div>`s, I cannot color it in red, without me understanding why.

Have a look: http://plnkr.co/edit/HzLS0XroCizdBAb0Uu3B?p=preview

**Comment by arthurevans** [comment] 2015-01-13 00:53
The actual issue you're seeing with the <div> in the parent may well be a Chrome bug. I can't see why it's happening.

Note that the `<content>` tags inside your `<shadow>` tags are ignored. The `<shadow>` tag is an insertion point for the older shadow tree -- just like the `<content>` tag, any tags inside `<shadow>` are ignored, and you see the older shadow tree instead.

If you use `<content select="h2">` outside of the `<shadow>` tag, you can cherry-pick the `h2` before it gets distributed into the parent shadow tree. However, you can't pick and choose what gets distributed inside the parent tree by adding `<content select>` tags inside the `<shadow>` tag.

**Comment by steren** [comment] 2015-01-13 09:30
Interesting. I will then file a bug for Chrome for further investigation.

You are right, I realize that if I remove things inside the `<shadow>` tags, I still have the same result. Good to know.

I would advise to detail that it is just an insertion point in the [doc](https://www.polymer-project.org/docs/polymer/polymer.html#extending-other-elements)

Also, if we cannot put anything inside `<shadow>`, would it make sense for it to not have an end tag? (like the `<br>` tag), it would prevent from such mistake.

**Comment by tjsavage** [comment] 2015-10-23 23:26
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:26 UTC
Labels: 0.5
