### ISSUE TITLE
Clicking link outside of shady dom throws error in polyfill

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3958] opened 2016-09-14 23:53 UTC
In FF, clicking a link throws an error in the shady dom retargeting:

<img width="1251" alt="screen shot 2016-09-14 at 4 43 57 pm" src="https://cloud.githubusercontent.com/assets/238208/18533936/a5c8e30a-7a9b-11e6-8049-eddae45f3dc8.png">

Try clicking the links (1, 2, 3, 4, 5) in FF: http://jsbin.com/tuwubijofi/edit?html,output

**Comment by azakus** [comment] 2016-09-15 22:41
Duplicate of https://github.com/webcomponents/shadydom/issues/9

**Closed by azakus** 2016-09-15 22:41 UTC
Labels: 2.x
