### ISSUE TITLE
Polymer.Base.unshift breaks notify paths on all other elements.

### ISSUE THREAD

**Issue by birkir** [Polymer/polymer#2139] opened 2015-07-23 11:49 UTC
I have two Polymer elements that represent array of items defined as a property.

Now, when I use the notify path's `unshift` method in one element to append item in top of the array, it breaks the other element's notify path/splice (so all elements don't get updated anymore).

Other notify path's functions work (`push`, `pop`, `splice`, and even `shift`).

While investigating, I did not see anything else being done in the feature itself for `unshift` vs `shift`.

**Comment by kevinpschaaf** [comment] 2015-07-23 21:11
It would help to understand your use case better, and what exactly breaks in reference to "it breaks the other element's notify path/splice".  Are you using `dom-repeat` in the elements?  Can you create/share a repro case?

I created a jsBin here that has two elements that display array contents using a `dom-repeat`, and `unshift`/`splice` do the right thing.  Can you try forking the jsBin to match your use case?
http://jsbin.com/beninuy/edit?html,output

The one thing to be aware of is that path notifications for array changes use unique _keys_ (rather than array index) in the path, to ensure path linkage between objects in arrays despite possible insertions or deletions in the array.  However, there is currently an [open issue (see here)](https://github.com/Polymer/polymer/issues/2007#issuecomment-119305600) regarding the fact that there is a discrepancy in the API re: paths you give to 'set' (which accept array _index_) vs. paths you receive from `.*` wildcard observers (which use _keys_), and the plan is to disambiguate those.

**Comment by birkir** [comment] 2015-07-24 00:04
Ok, you got me there. Once I investigated this better (while working on the jsbin you provided, towards something similar I have in my app), I discovered that the problem really was with those indexes of the arrays you mentioned in your comment.

http://jsbin.com/gaduqujowa/1/edit?html,output 

^^ So here I have element A and element B, each with their unique array of items.
I then unshift an object into A items array, and update both A and B first object in each array and get the results above.

So the index on the B array get's weird. Item zero in B array get's unaccessible.

**Comment by kevinpschaaf** [comment] 2015-07-24 22:22
Ok, I root caused this to a bug related to incorrectly shared object in `iron-list`.

I opened https://github.com/PolymerElements/iron-list/issues/41 on that element to track the issue.

Since this looks like a bug on a specific element as opposed to the core, I'll close this.  Feel free to re-open if you find something else in your use case that's not specific to `iron-list`.  Thanks!

**Closed by kevinpschaaf** 2015-07-24 22:22 UTC
Labels: pending-response

**Comment by birkir** [comment] 2015-07-27 10:23
Good work Kevin.
I'll keep track of the bug on the iron-list project.
