### ISSUE TITLE
Simple observer on array property receives 'length' values

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4072] opened 2016-10-15 15:41 UTC
### Description

Given a simple observer on an array: 

```
prop1: {
  type: Array,
  value: function() {
    return ['one', 'two', 'three'];
  },
  observer: '_propChanged'
}
```

This now fires for array mutations, which is awesome. But it also appears to fire for .length changes, which is not awesome.
#### Live Demo

http://jsbin.com/gawegag/6/edit?html,console,output
#### Steps to Reproduce

Run demo. Note that some of the values passed to the simple observer are the array itself (which we expect) while others are the current length of the array (which we do _not_ expect).
### Versions
- Polymer: 2.0-preview branch
- webcomponents: v1 branch

**Comment by zinkkrysty** [comment] 2016-11-08 21:52
Strange enough this only happens when you push using this syntax:

```js
this.push('prop1', 'four');
```

If you however push directly on the property and then notify the path it works as expected:

```js
this.prop1.push('four');
this.notifyPath('prop1');
// `_propChanged` gets called once with `["one", "two", "three", "four"]`
```

It all boils down to what this method is doing:
https://github.com/Polymer/polymer/blob/2.0-preview/src/properties/property-effects.html#L910

The question is, is it intended behavior? I would argue for not, since it's not consistent with the combination of `prop.push` and `notifyPath`

**Comment by zinkkrysty** [comment] 2016-11-08 22:34
Found another interesting thing:

https://github.com/Polymer/polymer/blob/2.0-preview/src/utils/path.html#L47

```js
    matches: function(base, path) {
      return (base === path) ||
             this.isAncestor(base, path) ||
             this.isDescendant(base, path);
    },
```

When deciding to notify the observers, Polymer calls for `Polymer.Path.matches` with the `prop1` (base) and `prop1.length` (path that changed), and yes, it tells the observer that it can be called because `prop1` is an ancestor of `prop1.length` when the length changes. 

I guess it will be reasonable to only fire observer for `prop1` **once** when any descendant changes - in this case the descendant could be either one of `length`, `splices`, etc.

**Comment by zinkkrysty** [comment] 2016-11-09 06:58
Oh it seems people know about this:

https://github.com/Polymer/polymer/blob/2.0-preview/test/unit/notify-path.html#L55

```js
  function verifyObserverOutput(nestingLevel, nested) {
    assert.equal(el.nestedSubpathChanged.callCount, 1);
    // TODO/BREAKME(kschaaf): non-wildcard object observers now called
    // for deep path changes
```

**Comment by mkazlauskas** [comment] 2016-11-11 13:34
Probably related:

```javascript
prop: { observer: '_propChanged(prop)' }
...
_propChanged(newValue) {
  if (newValue === 'a') {
    throw "expected newValue { a: 'a' }"
  }
}
...
this.set('prop.a', 'a');
```

**Comment by kevinpschaaf** [comment] 2017-02-25 00:02
Resolved via https://github.com/Polymer/polymer/pull/4304.

**Closed by kevinpschaaf** 2017-02-25 00:02 UTC
Labels: 2.x
