### ISSUE TITLE
PaperToggleButtonElement addEventListener

### ISSUE THREAD

**Issue by Fritz75** [Polymer/polymer#3389] opened 2016-02-08 15:33 UTC
I'm using UiBinder and want to add a PaperToggleButtonElement and then add an event:

XML:
<p:PaperToggleButton ui:field="myToggle"></p:PaperToggleButton>

Java class:
  @UiField
  public PaperToggleButtonElement myToggle;

myToggle.addEventListener("iron-change", new EventListener() {
      @Override
      public void handleEvent(Event event) {
       //doSomething
      }
    });
in developer console I get this.myToggle_1_g$.addEventListener is not a function

Please, can you help me in any way?

**Comment by azakus** [comment] 2016-02-10 01:00
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by timeu** [comment] 2016-02-10 09:00
I think is is probably more a `GWT` issue than a `Polymer` one. 
The right place for the issue is probably the [vaadin's gwt-polymer-elements repo](https://github.com/vaadin/gwt-polymer-elements) 
Could be a [timing issue](https://github.com/vaadin/gwt-polymer-elements#asynchronous-issues)

**Comment by Fritz75** [comment] 2016-02-10 13:12
https://github.com/vaadin/gwt-polymer-elements/issues/108

**Comment by azakus** [comment] 2016-02-10 19:44
Ok, I'll close this then.

**Closed by azakus** 2016-02-10 19:44 UTC
Labels: pending-response
