### ISSUE TITLE
www.polymer-project.org is fail.

### ISSUE THREAD

**Issue by pongpanot-t** [Polymer/polymer#4264] opened 2017-01-19 02:01 UTC
1 week ago...     Many thai people have this problem.
![screen shot 2560-01-19 at 08 58 00](https://cloud.githubusercontent.com/assets/13883955/22090656/b9c0ee50-de25-11e6-86fb-a2f8ffe01fba.png)

**Comment by arthurevans** [comment] 2017-01-19 02:15
Thanks for the report. We think this is related to the hosting service and we're following up with them. Can you tell me what browser and version you're using?

This can usually be resolved by doing a full reload of the page (shift+reload). Please let me know if that doesn't resolve it for you.

**Comment by pongpanot-t** [comment] 2017-01-19 04:36
Chrome V.55.0.2883.87 m (64-bit)
-------------------------------------------
My solving problems : Open "Inspect element" then reload web..

**Comment by tonsai-j** [comment] 2017-01-19 04:41
i likewise. 
![chrome](https://cloud.githubusercontent.com/assets/20677235/22093858/ad2214b0-de3b-11e6-881b-c3d82f7ea2fc.PNG)
Chrome V.55.0.2883.87 m (64-bit)

![ie](https://cloud.githubusercontent.com/assets/20677235/22093857/ad20c970-de3b-11e6-8501-bd4ce24c6606.PNG)
Microsoft Edge 38.14393.0.0

**Comment by coding2012** [comment] 2017-01-19 16:48
Works fine in Firefox for me, but same SPDY protocol errors for me in Chrome.

**Comment by majorbuild** [comment] 2017-01-22 07:42
I believe the site is hosted in Google Cloud, my site using App Engine also go the similar issue when http push is used, I had opened an issue here: https://code.google.com/p/googleappengine/issues/detail?id=13502

**Comment by ernsheong** [comment] 2017-01-23 13:57
Malaysia too! I had to reload 4 times to get it working.

**Comment by majorbuild** [comment] 2017-01-23 22:10
And I'm from Hong Kong

**Comment by tony19** [comment] 2017-01-24 02:07
FYI, issue should be fixed now. Give it a try, and let @notwaldorf and @arthurevans know your results :)

![screen shot 2017-01-23 at 8 03 04 pm](https://cloud.githubusercontent.com/assets/26580/22231104/fe16b876-e1a6-11e6-9c30-35d9e4b387df.png)

**Comment by coding2012** [comment] 2017-01-24 02:23
@tony19 @notwaldorf @arthurevans It is working for me now 👍  in Chrome.

**Comment by pongpanot-t** [comment] 2017-01-24 04:03
It is working for me now too.

**Closed** 2017-01-24 04:04 UTC

**Comment by majorbuild** [comment] 2017-01-24 04:15
works, can you share how you managed to fix that?

**Comment by arthurevans** [comment] 2017-01-24 07:28
Hi @majorbuild. We temporarily disabled server push, which seemed to be causing the issues. Will continue trying to chase down the root cause so we can re-enable it.

**Comment by devilbags** [comment] 2017-01-24 14:52
@arthurevans it worked for a while. But then this happened, haven't been able to access https://www.polymer-project.org/ for a month now
<img width="743" alt="screen shot 2017-01-24 at 9 50 29 am" src="https://cloud.githubusercontent.com/assets/11239869/22252011/c8ee4b68-e21a-11e6-9cdf-1c39922fad35.png">
It appears that the site's HTTPS is messed up?

**Comment by arthurevans** [comment] 2017-01-24 20:57
@devilbags The certificate appears to be fine on our end. 

There's a list of troubleshooting steps for certificate errors here: 

https://support.google.com/chrome/answer/6098869#connection

Can you try  those out and see if they help?

**Comment by arthurevans** [comment] 2017-01-24 21:30
@devilbags If you're still having problems after going through those steps, please open a new ticket for the certificate issue  you're seeing. It doesn't appear to be related to either this bug or #4237.
