### ISSUE TITLE
 CSS include="shared-style" warnings of missing style under async imports

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2380] opened 2015-08-27 00:39 UTC
Given an async import on the main page, followed by a custom-style, Polymer warnings of a missing shared style:

<img width="819" alt="screen shot 2015-08-26 at 5 38 24 pm" src="https://cloud.githubusercontent.com/assets/238208/9509840/5255b056-4c19-11e5-8df0-a59fba839fa8.png">
 
```html
<link rel="import" href="elements.html" onload="onImportsLoaded(event)" async>
<style is="custom-style" include="shared-style"></style>
```

`shared-style` is in an import within elements.html:

elements.html:

```html
<link rel="import" href="shared-style.html">
```

shared-style.html:

```html
<dom-module id="shared-style">
  <template>
    <style>
      ...
    </style>
  </template>
</dom-module>
```

**Comment by sorvell** [comment] 2015-08-27 21:13
This is by design. The notion is that the include is a dependency of the `custom-style` so it should be loaded first.

What's the use case prompting this? I'd be inclined to say that the `custom-style` here should go in the async import.

**Comment by ebidel** [comment] 2015-08-27 21:35
Hmm, ok. I would have thought `include="shared-style"` mixes in styles rather than it being a dependency but now I'm realizing that its `dom-module` needs to be defined first. Same as any other custom element.

We can try moving `custom-style` into the elements.html import. I have to look at if/where elements.html is shared across pages.

**Comment by ebidel** [comment] 2015-08-27 22:29
Moving the custom-style in the async import doesn't work. In elements.html:

```
<link rel="import" href="../bower_components/google-codelab-elements/shared-style.html">
<style is="custom-style" include="shared-style"></style>
```

Won't this also break when styles in import documents no longer apply to the main page?

**Comment by sorvell** [comment] 2015-08-28 16:59
We'll make sure `custom-style` in an import applies to the main document
after that change. Does it not work other than that concern?

**Comment by ebidel** [comment] 2015-09-25 18:00
@sorvell I think there's a bigger issue. See https://github.com/Polymer/polymer/issues/2481

**Comment by sorvell** [comment] 2016-01-28 23:09
Closed in favor of https://github.com/Polymer/polymer/issues/2481.

**Closed by sorvell** 2016-01-28 23:09 UTC
Labels: async, summit
