### ISSUE TITLE
HTML comments inside of nested templates, breaks the templates

### ISSUE THREAD

**Issue by faGH** [Polymer/polymer#1995] opened 2015-07-01 08:02 UTC
HTML comments inside of nested templates, breaks the templates with Polymer 1.0 (Latest version to this date). E.g.

## HTML
```
<!-- HTML comment one -->
<template is="dom-if" if="{{condishIsTrue}}">
    <!-- HTML comment two -->
    <template is="dom-if" if="{{!anotherCondishIsTrue}}">
        This text still gets shown despite the error that occurs in the console.
    </template>
</template>
```
## Console Error

"Uncaught TypeError: Cannot set property 'display' of undefined" (polymer.html:3677)

## Call stack:
Polymer._hideChildren	@	polymer.html:3677
Polymer.Templatizer._hideTemplateChildrenChanged	@	polymer.html:2883
Polymer.Base.extend._observerEffect	@	polymer.html:1162
(anonymous function)	@	polymer.html:1020
Polymer.Bind._modelApi._effectEffects	@	polymer.html:1017
Polymer.Bind._modelApi._propertySet	@	polymer.html:1011
setter	@	polymer.html:1078
Polymer._render	@	polymer.html:3630
Polymer.Templatizer._flushTemplates	@	polymer.html:2897
Polymer.Debounce.Debouncer.complete	@	polymer.html:844
atEndOfMicrotask	@	polymer.html:805

**Comment by arthurevans** [comment] 2015-07-01 12:15
Duplicate of https://github.com/Polymer/polymer/issues/1786.
This is fixed in master, as of yesterday, I believe. So the fix should be in the next release.

**Closed by arthurevans** 2015-07-01 12:15 UTC
Labels: duplicate

**Comment by dman777** [comment] 2015-08-16 03:06
Actually, this comment is breaking `paper-toolbar` or me, inner contents  of `paper-header-panel` won't show:

```html
   <paper-header-panel mode="waterfall-tall" class="flex">
      <paper-toolbar>
        <!-- Filler to make paper-tab end justified -->
        <div class='title'></div>
        <!-- Filler end -- >
```
