### ISSUE TITLE
Use of Style Module Causes Script Tag Content to Render

### ISSUE THREAD

**Issue by w-p** [Polymer/polymer#2437] opened 2015-09-14 20:48 UTC
I just upgraded Polymer (bower says 1.1.3) and when using the 'style module' approach, the contents of the `<script>` tags that are inserted into `<head>` are rendered to the page just above `<body>`.  Only by setting head's style to `display: none` can I make it go away.  Style's are applied appropriately, there's just a litany of CSS flooding the top of the page.  This wasn't an issue under 1.0.0.

**Comment by azakus** [comment] 2015-11-11 01:40
Sorry, I can't reproduce that behavior with this JSBin that uses Polymer 1.1.3: http://jsbin.com/hupinu/edit?html,output

**Comment by azakus** [comment] 2016-01-28 20:18
Closing due to age, please reopen if this is still an issue.

**Closed by azakus** 2016-01-28 20:18 UTC
Labels: pending-response

**Comment by w-p** [comment] 2016-02-02 17:07
I found the problem a while ago and should've closed this out.  Apologies.  Put the below style inside head and you'll see what I was referencing. However, this little gem shouldn't be there anyway so... not an issue.
```
<style>
    * {
      display: inline-block;
    }
</style>
```
