### ISSUE TITLE
Instantiating a template with `Polymer.Templatize.templatize` as per API reference throws

### ISSUE THREAD

**Issue by doplumi** [Polymer/polymer#4908] opened 2017-10-31 17:49 UTC
### Description
Error when calling Polymer.Templatize.templatize(template) as per the [first snippet](https://www.polymer-project.org/2.0/docs/api/namespaces/Polymer.Templatize) of the API reference.

#### Live Demo
http://jsbin.com/tunize/1/edit?html,output

#### Expected Results
No error is throw

#### Actual Results
templatize.html:453 Uncaught TypeError: Cannot read property 'constructor' of undefined
    at Object.templatize (templatize.html:453)
    at HTMLElement.ready (runner:16)
    at HTMLElement._enableProperties (property-accessors.html:531)
    at HTMLElement.connectedCallback (element-mixin.html:638)

BTW, it works when calling `Polymer.Templatize.templatize(template, this)`.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 8
- [x] Safari 9
- [x] IE 11

### Versions
- Polymer: last master

**Comment by doplumi** [comment] 2017-10-31 17:53
As an additional note, even if you pass `this` as the second argument, the data passed in to the resulting class doesn't seem to be attached to the template.

As a temp workaround for people bumping into this, `Object.assign(instance, data)` after `.appendChild(...)` seems to work.

**Comment by web-padawan** [comment] 2017-10-31 18:30
See also [this comment](https://github.com/Polymer/docs/issues/1428#issuecomment-333427685)

/cc @arthurevans

**Comment by yveslange** [comment] 2017-11-09 16:21
Same bug

**Comment by TimvdLippe** [comment] 2017-11-15 23:21
Closing this as duplicate of https://github.com/Polymer/docs/issues/1428 Hopefully we can update the full documentation soon to clarify this example.

**Closed by TimvdLippe** 2017-11-15 23:21 UTC
