### ISSUE TITLE
Property not updated at time of notification

### ISSUE THREAD

**Issue by fejesjoco** [Polymer/polymer#4028] opened 2016-10-01 08:25 UTC
Consider this code:

```
observers: ['test(someProperty)'],
...
test(someProperty) {
  if (this.someProperty !== someProperty) fail();
}
```

This works, the passed argument and the property under this are equal. This is overly simplified, but this does matter when you have more complex scenarios. Eg. using deep property observers and you are working with a type-safe JS eg. JSCompiler. Or when you want to work around quirks of undefined in the notification system, so you do `observe(x1), observe(x2)` instead of `observe(x1,x2)`. In many cases, using the property instead of the argument is much much easier.

Except there's one tricky case where that fails, when a deep property observation happens inside a template: http://jsbin.com/fewinofipa/1/edit?html,output . If you move the `<y-foo>` line just above the template, the code works, but in its current form, `this.property` contains the old value while the observer method argument contains the new one.

**Comment by kevinpschaaf** [comment] 2016-10-05 17:44
The technical reason is that the property change has not propagated from `dom-if`'s template instance to the `x-foo` host yet (despite the fact that the computing function used in the template instance is called in the context of the host).  Having the computed binding inside the `dom-if` vs. outside is different in this regard, although it looks very similar.

A change we're vetting out right now in the 2.0 codebase is to notify changes to hosts before running effects, which ensures that changes bubble to the top-most host and then propagate down in a deterministic order, ensuring that host properties are updated before their children.  I confirmed that this approach does indeed address the issue you had.

However, since that's a pretty significant breaking change, it's not easily applied to the 1.x codebase.  We consider it a best practice to write computing functions as pure functions that don't access their context anyway, to avoid the temptation to rely on undeclared dependencies.  So for now I'd recommend just sticking with computing functions that only reference arguments in 1.x (although I do acknowledge the lack of consistency this may introduce in your code given that there are cases you raised where you can't use arguments).  FWIW we're also making changes in 2.0 to avoid the (annoying) multi-property `undefined` rough edges that can necessitate needing to use single-property observers for multi-property computations where some arguments may be undefined, which should make it easier to enforce the rule of writing pure computing functions).

**Comment by jfrazzano** [comment] 2016-10-06 18:40
How would you manage an interface that lays out some unknown number of inputs related to some set of data determined properties. 

I was using a repeater that would be fed Json from deconstructed constructor functions 

A person constructor would have its properties turned into inputs, the inputs names "names of the properties" would become properties on a value object held by the form interface 

The properties would be dynamically created based on inputs in the view fed to an iterated define own properties that bound the object interface properties via the getters to the inputs presented on screen 

Page turns created new interface objects that represented the page but inherited the previous properties from the last prototype. 

I have it running in native without elements but had the same sort of chained factory running in 1.0

Only way I can figure to "elementize" it is to go directly to the prototype on the window and monkey such there.

**Comment by fejesjoco** [comment] 2016-10-10 14:46
@jfrazzano I think you sent this to the wrong thread?

@kevinpschaaf Are you basically saying that the computation in the host takes the value from the child directly? I would expect that when I bind the observer to this.someProperty, it indeed comes from this, and some other component (which just happens to be writing to the same value). I don't expect major refactorings like you mentioned, but the straightforward way would be: 1. notify the observers of the changed property in the child 2. propagate the binding from child to host 3. notify the observers of the changed property in the host. Notifying the host when a property in the child changes seems rather broken, and I would expect that it should be simple to change how the dependencies of the computation function are wired.

**Comment by mgiuffrida** [comment] 2016-11-17 20:39
@kevinpschaaf @bicknellr @danbeam Not mentioned in this issue, but apparently this happens *within a single element* as well, when inside a `dom-if`:

https://jsfiddle.net/g54Lxf5n/1/

Is this indeed a simpler example of the same problem? My team has always operated under the assumption that `this.foo` and the argument `foo` were always equal in a computed binding function call.

**Comment by kevinpschaaf** [comment] 2016-11-28 17:49
@mgiuffrida Yes, your jsBin suffers from the same problem.  The argument is always equal except in this specific case -- using computed bindings inside template elements which have their own scope that "inherit" any outer properties used in the template from the outer scope.  The computed binding's method is called with `this` of the element (as opposed to the `dom-if` scope) so that you can e.g. call `this.otherMethod` on the element, but this means that any values that have not propagated to the outer element will not match.  No questions this is unexpected, however a fix in 1.0 that avoids other problems is hard to thread...

**Comment by mgiuffrida** [comment] 2017-01-05 18:22
@kevinpschaaf Well that really sucks.

**Comment by kevinpschaaf** [comment] 2017-12-14 01:20
> A change we're vetting out right now in the 2.0 codebase is to notify changes to hosts before running effects

In 2.0 we did not end up going with the potential change discussed in the comment above, as it ended up being too large of a breaking change.

So this issue basically still stands in 2.0.  However the changes to `undefined` handling in 2.0 should make it easier to write pure computing functions that only depend on their arguments (i.e. @fejesjoco's example of wanting to do `observe(x1, x2)` no longer has the `undefined` problems).  I'll also point out that (although we didn't remove 2-way binding in 2.0), it is also avoided by using unidirectional/one-way data binding.

Due to those two workarounds, I'm going to go ahead and close this since there is not a viable, non-breaking solution we can make, and instead recommend one of the workarounds (pure computing functions or unidirectional data flow).

**Closed by kevinpschaaf** 2017-12-14 01:20 UTC
Labels: 1.x, source: hooli

**Comment by freshp86** [comment] 2017-12-14 01:33
Is this behavior mentioned in the official docs? It would probably save some time and confusion to whoever encounters this issue in the future.
