### ISSUE TITLE
Polymer.templatize creates HTMLElement instances which can't be removed from Polymer.dom

### ISSUE THREAD

**Issue by jahglow** [Polymer/polymer#3533] opened 2016-03-25 09:31 UTC
### Description

When Polymer.Templatize behavior is used, and template instances are stamped into the page, One cannot really remove those elements and event listeners attached to them completely. This doensn't happen when elements are created and removed via `Polymer.dom().appendChild/removeChild`, only when templatize is used, and I assume because it doesn't clean up the anonymopus Polymer.Base instance when stamps of that instance are removed.
#### Steps to Reproduce

Example: 

``` html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../paper-input/paper-input.html">
<dom-module id="ex-ample">
  <template>
    <div id="container"></div>

    <template id="stringTemplate">
      <paper-input type="text" value="[[data.value]]" label="[[data.label]]" prop="[[data.label]]"></paper-input>
    </template>

  </template>
</dom-module>
<script>

  Polymer({

    is: 'ex-ample',
    behaviors:[Polymer.Templatizer],

    ready:function(){
      var i=500;
      while (i--){
        this.templatize(this.$.stringTemplate);
        Polymer.dom(this.$.container).appendChild(this.stamp({data:{label: 'label', value:'value'}}).root);
      }
      var nodesL = Polymer.dom(this.$.container).childNodes.length;
      if(nodesL>0){
        while(nodesL--) Polymer.dom(this.$.container).removeChild(Polymer.dom(this.$.container).childNodes[nodesL]);
      }

    }
  });
</script>
```
#### Expected Results

In DevTools>Timeline The number of listeners should go down as well as the number of nodes while Polymer.dom() is removing children from the container
#### Actual Results

In fact the graph doesnt reflect any decrease in either nodes or listeners
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by kaste** [comment] 2016-03-30 22:26
Cannot reproduce. Did you click 

![image](https://cloud.githubusercontent.com/assets/8558/14159597/e66ef5b4-f6d6-11e5-8e78-8c2e59f2915a.png)

Be aware that you should `this.templatize(this.$.stringTemplate)` only once. T.i. `templatize` once, `stamp` often.

**Comment by TimvdLippe** [comment] 2017-08-15 00:33
`Polymer.dom` is now legacy due to issues like this one. Therefore closing this issue.

**Closed by TimvdLippe** 2017-08-15 00:33 UTC
Labels: 1.x, review then close
