### ISSUE TITLE
Undefined array causes error in Polymer push method

### ISSUE THREAD

**Issue by Alos** [Polymer/polymer#3263] opened 2016-01-03 01:24 UTC
Hello!

It looks like if there might be an error in the push method in the notify-path.html (Not really sure if this is intended), in the current implementation it looks like this:
```javascript
push: function(path) {
        var info = {};
        var array = this._get(path, this, info);
        var args = Array.prototype.slice.call(arguments, 1);
        var len = array.length; // BOOM!
        var ret = array.push.apply(array, args);
        if (args.length) {
          this._notifySplice(array, info.path, len, args.length, []);
        }
        return ret;
      }
```

If the array is null then we get a "Cannot read property 'length' of undefined". It should look like this?

```javascript
push: function(path) {
        var info = {};
        var array = this._get(path, this, info);
        var args = Array.prototype.slice.call(arguments, 1);
        var ret = array.push.apply(array, args);
        if (args.length) {
          var len = array.length; // No BOOM!
          this._notifySplice(array, info.path, len, args.length, []);
        }
        return ret;
      }
```

Or is it expected that the array will always be defined at this point of the code?

**Comment by kevinpschaaf** [comment] 2016-01-05 04:59
With your change, `array.push.apply(array, args)` would still fail...  The whole point of the function is to operate on the array at that path.

You should think of `this.push('path.to.array', obj)` just like `this.path.to.array.push(obj)`.  The latter would throw if `this.path.to.array` was `undefined`, as does the former.

I'm going to go ahead and close this as "works as intended" -- let me know if I missed a point you were trying to make.

**Closed by kevinpschaaf** 2016-01-05 04:59 UTC

**Comment by Alos** [comment] 2016-01-07 23:49
Understood! Thanks! =)
