### ISSUE TITLE
observerNodes is called one time ?

### ISSUE THREAD

**Issue by RoXuS** [Polymer/polymer#4266] opened 2017-01-20 12:54 UTC
### Description
`observeNodes` on `this.$$('content')` is called only if we add or remove a node.
How to fire the callback when the node change (see live demo).

#### Live Demo
http://jsbin.com/cuzogusoga/1/edit?html,console,output

#### Steps to Reproduce
1. Add observeNodes to a content node
2. The callback is called only if we add or remove a node but not if we update the nodes.

### Browsers Affected

- [x] Chrome

### Versions
- Polymer: v1.7.1

**Comment by TimvdLippe** [comment] 2018-02-06 16:06
This happens because `<dom-repeat>` reuses template instances. If you modify the array to have more/less items, it does trigger the observer: http://jsbin.com/nopabusole/edit?html,console,output
To not reuse templates, `restamp` will be introduced it per #1713. Therefore closing this issue as working as intended (for now), but improvement to be implemented with #1713.

**Closed by TimvdLippe** 2018-02-06 16:06 UTC
Labels: 1.x
