### ISSUE TITLE
dom-if with comments

### ISSUE THREAD

**Issue by dombre** [Polymer/polymer#1926] opened 2015-06-19 23:48 UTC
If I include a comment within a dom-if template and use the component several times, something goes wrong. Here is a simplified example:

    <test-element with-bar></test-element>
    <test-element></test-element>
    <test-element with-bar></test-element>

    <dom-module id="test-element">
      <template>
          Foo<template is="dom-if" if="{{withBar}}"><span>bar</span></template>
      </template>   
    
      <script>
        Polymer({
          is: 'test-element',
        
          properties: {
            withBar: {
              type: Boolean
            }
          }
        });
      </script>
    </dom-module>

Expected output: `Foobar Foo Foobar`
Actual output: `Foobar Foo Foo`

If I remove the comment `<!-- Bug? -->` it works as expected. As you can see in these jsbins:

Works: http://jsbin.com/reqoho/17/edit?html,output
Does not work: http://jsbin.com/reqoho/18/edit?html,output

**Comment by masaoliou** [comment] 2015-06-21 05:44
An earlier report already mentioned this symptom. Somehow I am unable to locate that issue#.

**Comment by kevinpschaaf** [comment] 2015-06-22 20:52
Closing as duplicate of https://github.com/Polymer/polymer/issues/1786.

**Closed by kevinpschaaf** 2015-06-22 20:52 UTC
