### ISSUE TITLE
:host([element-attribute]:host-context([ancestor-attribute])) works in shadow mode only

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#3658] opened 2016-05-16 09:53 UTC
https://jsbin.com/cojopesama/edit?html,output

Three divs (red blue green) when window.Polymer = { dom: 'shadow' }; and (red blue blue) when shadow is false.

is :host([element-attribute]:host-context([ancestor-attribute]))
a polyfill limitation or a bug?
Thank you

**Comment by azakus** [comment] 2016-05-23 23:37
This sounds like a duplicate of #3610 and #1952

**Comment by eeid26** [comment] 2016-06-19 11:25
This issue is not a duplicate of the other issues. It did not get fixed by fixing the other issues.
Please notice the usage of :host-context in :host

**Comment by TimvdLippe** [comment] 2018-01-20 11:09
Closing this as duplicate of https://github.com/webcomponents/shadycss/issues/74#issuecomment-291350193

**Closed by TimvdLippe** 2018-01-20 11:09 UTC
Labels: 1.x, css, duplicate
