### ISSUE TITLE
Notify the user when not calling super

### ISSUE THREAD

**Issue by lastmjs** [Polymer/polymer#4407] opened 2017-03-10 08:23 UTC
As I've been playing around with the Polymer 2.0 preview, something has thrown me off multiple times. I forgot to call `super.ready()` in the `ready` callback, and I think I did the same in the `connectedCallback`. In each case I had no idea what has happening, and it took a while to figure it out. Is there any way to indicate to the user when they have not called `super`?

**Comment by sorvell** [comment] 2017-03-10 19:34
Definitely needs to be added to the linter tool. Closing this issue as a duplicate of #4412.

**Closed by sorvell** 2017-03-10 19:34 UTC
