### ISSUE TITLE
[polymer-3.0-pre12] App starterkit  v4.0.0-pre.2

### ISSUE THREAD

**Issue by yveslange** [Polymer/polymer#5208] opened 2018-04-27 12:29 UTC
### Description
Error when browsing `es5-bundled` build using  application starter kit `v4.0.0-pre.2` and `Polymer 3.0-pre12`

#### Steps to Reproduce
Example:

1. Download the starter kit  v4.0.0-pre.2.zip
2. polymer build
3. polymer serve build/es5-bundled -H 0.0.0.0
4. Browse to http://addr:8081

#### Expected Results
No error in the console

#### Actual Results
```
GET http://addr:8081/node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js 404 (Not Found)      (index:387)
my-app.js:2634 Uncaught ReferenceError: caseMap$1 is not defined
    at Function.attributeNameForProperty (my-app.js:2634)
    at my-app.js:3387
    at Array.map (<anonymous>)
    at Function.get (my-app.js:3386)
    at Object.<anonymous> (my-app.js:5321)
    at Object.execCb ((index):950)
    at M.check ((index):716)
    at M.enable ((index):802)
    at M.init ((index):681)
    at f ((index):609)
```

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 9
- [X] Safari 8
- [X] IE 11

### Versions

- Polymer: v3.0.0-pre12
- webcomponents: v1.2.0
- Polymer-CLI: v1.7.0-pre.15

**Comment by TimvdLippe** [comment] 2018-04-27 14:34
Duplicate of https://github.com/Polymer/tools/issues/253 Should be fixed on master there.

**Closed by TimvdLippe** 2018-04-27 14:34 UTC
