### ISSUE TITLE
Firefox fails to show custom element with properties bound with two-way binding + hostAttributes

### ISSUE THREAD

**Issue by denevell** [Polymer/polymer#2185] opened 2015-08-02 19:28 UTC
If we 

* use Polymer 1.0.8
* have a custom element (either in a separate page or inline as below) with a property
* the property is bound using two way binding
* has a hostAttributes on the element
* we are using Firefox 41.0a2 (not tested on earlier) (it works fine on Chrome Version 42)

Then we encounter the error: 

    TypeError: this.__data__ is undefined. 

The error comes from "var old = this.__data__[property];" line 1153 from polymer.html.js according to the firefox debug tools.

If, however, we remove the hostAttributes, then it displays fine in firefox.

Below is the code that bails in Firefox. 

```
<html>
    <head>
        <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <link rel="import" href="bower_components/polymer/polymer.html">
    </head>

    <body>

        <dom-module id="an-element">
            <template>
                <span>{{thing}}</span>!
            </template>
            <script>
                HTMLImports.whenReady(function() {
                    Polymer({
                        is: "an-element",

                        hostAttributes: {
                            thing: "yeah"
                        },

                        properties: {
                            thing: {
                                type: String,
                            }
                        }
                    });
                });
            </script>
        </dom-module>

        <template is="dom-bind" id="app"> 
                <an-element thing="{{thing}}"></an-element>
        </template>
    </body>

    <script>
        window.addEventListener('WebComponentsReady', function(e) {
            document.querySelector("#app").thing='XXX'; // XXX is only seen in chrome, not firefox.
        });
    </script>
</html>
```

**Comment by kevinpschaaf** [comment] 2015-08-03 23:14
Duplicate of https://github.com/Polymer/polymer/issues/1673

**Closed** 2015-08-04 02:53 UTC
Labels: p1
