### ISSUE TITLE
Error in accessor property: can't redefine non-configurable property 'defaultPrevented'

### ISSUE THREAD

**Issue by liraniom** [Polymer/polymer#2720] opened 2015-11-12 12:07 UTC
Hello, I am getting the following exception In IE 11:
"Error in accessor property: can't redefine non-configurable property 'defaultPrevented'"

This happens after I am trying to use event.preventDefault();

I was able to fix this code by doing the following:

In webcomponents.js there is a polyfill for defaultPrevented:

I have added configurable:true in two places ,inside (!supportsDefaultPrevented) , and inside (!workingDefaultPrevented), and it solved the problem.
```
Event.prototype.preventDefault = function() {
        if (!this.cancelable) return;
        unsafeUnwrap(this).preventDefault();
        Object.defineProperty(this, "defaultPrevented", {
          configurable: true,
          get: function() {
            return true;
          }
        });
      };
```
Can you please include it in your future releases? ,

Thanks.

**Comment by zoechi** [comment] 2015-11-12 12:19
Please enclose source code in triple backticks.

**Comment by azakus** [comment] 2015-11-12 21:54
Duplicate of webcomponents/webcomponentsjs#441

**Closed by azakus** 2015-11-12 21:54 UTC
