### ISSUE TITLE
@apply applies style regardless of media query

### ISSUE THREAD

**Issue by bushuyev** [Polymer/polymer#3093] opened 2015-11-26 11:04 UTC
Please have a look at: http://plnkr.co/edit/FkcSdaKpop4u3orKkGs1?p=preview

The zzz div is evergreen despite query in shared-styles should define background-color: green; only up to max-width: 30em. This can be fixed by putting same query around @apply(--my-test) but then it would make shared-styles close to useless.

Also can be workarounded by defining (min-width: 30em)  and putting empty --my-test there, so not a major problem.

**Comment by JeremybellEU** [comment] 2015-11-26 14:47
I think this is a duplicate of #2149

**Comment by bushuyev** [comment] 2015-11-26 16:24
Maybe not exactly the same but definetly on the same topic. 
The interesting thing is that in comments to #2149 Kevin writes that shim ".. is currently not sophisticated enough to match media-query rules" but in my case queries  work, though in a special way. Looks like there was some work done on the shim.

**Comment by bushuyev** [comment] 2015-11-26 16:25
Should it be closed since the subject is known?

**Comment by azakus** [comment] 2016-02-11 20:48
I think the `@media` queries are just ignored entirely by the css shim, so this seems like a duplicate of #2149

**Closed by azakus** 2016-02-11 20:48 UTC
