### ISSUE TITLE
`resolveUrl` ignores baseURI when given absolute URL

### ISSUE THREAD

**Issue by bedeoverend** [Polymer/polymer#4788] opened 2017-08-10 22:58 UTC
### Description
`Polymer.ResolveUrl.resolveUrl` when called with an absolute path, will return _just_ the path without the `baseURI`. This means you can't construct paths for URLs with a different domain, or if you wanted to share around the full path URL.

I'm assuming it's just [this line](https://github.com/Polymer/polymer/blob/master/lib/utils/resolve-url.html#L30). Happy to make a PR, just want to confirm the expected behaviour.

#### Live Demo
http://jsbin.com/defave/edit?js,console

#### Steps to Reproduce
Call `Polymer.ResolveUrl.resolveUrl` with an absolute path, and any baseURI e.g.

```js
Polymer.ResolveUrl.resolveUrl('/foo', 'http://localhost');
```

#### Expected Results
Expect the absolute path appended to the baseURI e.g. `http://localhost/foo`

#### Actual Results
Just the absolute path e.g. `/foo`

### Browsers Affected
Just tested in these:

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Polymer v2.0.2 - could be more, this is just the one I'm testing it on

**Comment by TimvdLippe** [comment] 2017-08-14 22:23
It seems that this is expected behavior (https://github.com/Polymer/polymer/blob/master/test/unit/resolveurl.html#L72). I am not sure that if we would change this behavior what usage breaks.

**Comment by bedeoverend** [comment] 2017-08-15 05:05
Shame, seems weird to be able to point a relative resource to a baseURI with a different domain, but not an absolute. If it is indeed expected behaviour then understand this isn't an issue, would be great to have a way of doing it inside of the `ResolveUrl` utilities however.

**Comment by kevinpschaaf** [comment] 2018-01-03 23:40
Agree this is an odd behavior, since it seems there's no reason not to allow alternate domains from being resolved via the library API.  Ideally we could just point users to use the platform [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) for resolving URL's rather than this library function, but `URL` is not supported on IE11 and we wrote this tiny shim as a lighter-weight polyfill of the minimal URL resolving capability needed in Polymer.

The existing bail-out on absolute URL's was added to fix https://github.com/Polymer/polymer/issues/2448 in 1.x, where a user's expectation is that absolute URL's in templates are resolved against the _main document_ baseURI, not the import URI.  However, since in Polymer 2.0 [we removed auto-rewriting of URL's](https://github.com/Polymer/polymer/issues/4357) altogether in favor of the user making the choice explicitly via use of `importPath` or `rootPath`, the addition of the absolute URL bail-out to `resolveURL` does not seem required any more.

I propose that we move the absolute URL bail-out to `Polymer.ElementMixin`'s implementation of the instance API `this.resolveUrl(url, baseURI)`, and remove it from `Polymer.ResolveUrl.resolveUrl(url, baseURI)`.  This would ensure we don't break users who were relying on `this.resolveURL('/foo')` resolving to `document.baseURI + '/foo'`, while allowing the use case described above via the library api: `Polymer.ResolveUrl.resolveUrl('/foo', 'http://localhost')`

**Closed** 2018-01-08 17:57 UTC
Labels: 2.x, p1

**Comment by bedeoverend** [comment] 2018-01-11 02:19
Awesome - thanks @kevinpschaaf, @TimvdLippe!

**Comment by kevinpschaaf** [comment] 2018-01-31 23:56
cc: @bedeoverend 

Unfortunately, due to the issue reported in https://github.com/Polymer/polymer/issues/5080, we're going to revert this change since it broke usage of `#`-identifiers in CSS, due to the function's use to resolve URL's in CSS.  Rather than go deeper to try and thread the needle here to avoid breakage, we're going to revert that change, more-clearly document the idiosyncrasies with `resolveUrl`, and recommend using [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) for general-purpose URL resolution and [polyfilling](https://github.com/webcomponents/URL) `URL` where necessary.

**Comment by bedeoverend** [comment] 2018-02-01 00:09
@kevinpschaaf no worries - that makes sense. Appreciate the update!
