### ISSUE TITLE
#<slot_id>::slotted(*) not working on Chrome, FF, Safari

### ISSUE THREAD

**Issue by motss** [Polymer/polymer#4022] opened 2016-09-30 02:39 UTC
### Description

Is this a valid selector for `<slot>` in Shadow DOM v1 `#<slot_id>::slotted(*)` ?
#### Live Demo

http://jsbin.com/kakomosoyo/1/edit?html,output
#### Steps to Reproduce
1. Go to [Live Demo](http://jsbin.com/kakomosoyo/1/edit?html,output)
#### Expected Results

`#<slot_id>::slotted(*)` should work on at least Chrome 53 but it turns out that none of the browsers I have tested understand `#<slot_id>::slotted(*)`.
#### Actual Results

At least on Chrome 53, `slot` with its `id` receives the correct styling.
### Browsers Affected

- [X] Chrome 53+
- [X] Firefox 49+
- [ ] Edge
- [X] Safari 9+
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.7.0
- webcomponents: v0.7.22
- OS: macOS Sierra v10.12

**Comment by Link2Twenty** [comment] 2017-03-30 13:41
A quick work around with this is to change
```CSS
#slot_id::slotted(*)
``` 
to
```CSS
::slotted(*)[slot=slot_name]
```

**Comment by TimvdLippe** [comment] 2017-09-19 23:11
Demo seems to be working correctly now: http://jsbin.com/zenedicolo/edit?html,console,output I think this is fixed in one of the more recent versions of Chrome.

**Comment by wojinwomacka** [comment] 2018-02-28 14:54
Definitely not.  Testing  http://jsbin.com/zenedicolo/edit?html,console,output in chrome and firefox is different. In Chrome everything works fine. In newest version of firefox (58.0.2), no styles are applied

**Comment by TimvdLippe** [comment] 2018-02-28 14:57
@wojinwomacka Confirmed. This is probably related to Firefox shipping shadow DOM. We have to investigate what broke and maybe need to update the polyfills.

**Comment by wojinwomacka** [comment] 2018-02-28 15:09
@TimvdLippe  I just tested it also on Microsoft Edge  and the results are really strange. If you wrap `<slot>` with `div` and style it like #divId #slotId::slotted(*)  then it works. But if you just use #slotId::slotted(*), styles are not applied. Can you check this out?

**Comment by TimvdLippe** [comment] 2018-02-28 15:47
So in Firefox it does not appear to work, as the `id` from the `slot` are removed and not put on the `elements` that are distributed into the `slot`.

**Closed** 2022-04-17 09:02 UTC
Labels: bug, wontfix, p2, css
