### ISSUE TITLE
`unset` function needed

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2630] opened 2015-10-26 19:34 UTC
An `unset` or `delete` function would be quite useful, so yeah:

    this.unset('prop')

will either set it to the default `value` or unset it entirely, and

    this.unset('obj.prop')

will simply delete the `prop`. And of course in both cases it should trigger a `notifyPath` just like `set`.

**Comment by samccone** [comment] 2015-10-26 20:59
related #2447, #2565

**Comment by ebidel** [comment] 2015-10-26 22:19
Dupe of 2565

**Closed by ebidel** 2015-10-26 22:19 UTC
