### ISSUE TITLE
How to use visual studio and beautify to handle polymer file?

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4927] opened 2017-11-09 09:49 UTC
I want eslint my code and beautify my css , html, and js.But it does not work! Codes like this:
`
:host{
}
<template>

</template>
`

**Comment by TimvdLippe** [comment] 2017-11-09 15:25
Seems to be duplicate of https://github.com/HookyQR/VSCodeBeautify/issues/185

**Comment by TimvdLippe** [comment] 2017-11-15 23:20
Closing this per above comment, as this is a request for a specific tool (as linked above).

**Closed by TimvdLippe** 2017-11-15 23:20 UTC
