### ISSUE TITLE
polymer.html:1895 Uncaught TypeError: Cannot set property '1' of undefined

### ISSUE THREAD

**Issue by agozie** [Polymer/polymer#3688] opened 2016-05-31 21:13 UTC
### Description

Error thrown at `importHref` after upgrading from v1.4.0 to v1.5.0: polymer.html:1895 Uncaught TypeError: Cannot set property '1' of undefined.
Everything is fine if I revert back to v1.4.0, my project is fairly large, I am stumped by this one.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.5.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment] 2017-08-15 23:56
Closing this one as I am not able to reproduce this. Please reopen this issue if you can supply a JSBin that shows the issue.

**Closed by TimvdLippe** 2017-08-15 23:56 UTC
Labels: 1.x
