### ISSUE TITLE
Need efficient way to do reset styles across large component sets

### ISSUE THREAD

**Issue by zhaoz** [Polymer/polymer#4856] opened 2017-09-26 00:03 UTC
Polymer needs a cheap way of applying shared styles in shadow and shady dom contexts.

Ideally, this would apply to hybrid elements and therefore work in 1.x and 2.x as its an important piece of the migration process.

The specific use case we are trying to address is shared styles that are used across all elements (e.g. a reset-style.css file). Since /deep/ is being deprecated, the current solution is to use a <style include> in every single component.

This works great in shadow dom, but is inefficient in shady dom. Since the current shady dom implementation would create a lot of duplicate code.

From discussing with @sorvell it seems like we can add a solution where a <style include> gets appended to the root without going through the style scoping. That seems like a solution that would work well, especially if it can continue to work with css variables (although this is not a blocker for this feature).

(aside: not a fan of the amount of boilerplate we're adding, but that's a separate discussion).

**Comment by ernsheong** [comment] 2017-09-26 02:06
Curious, what's `source: hooli`? :P I'm guessing it's internal Google use based on SV

**Comment by jfrazzano** [comment] 2017-09-26 11:47
You can dynamically add scoped style under the tags of elements and use a this[some function template tag] on a CSS get method 

Get method e.g.

Obj.defineprops(this,{compiledcss:{get:f(){
Return {
CSS:(somereducer)=>this[somereducer]'css junk',
};
}}});

It's native

It's native

**Comment by jfrazzano** [comment] 2017-09-26 11:49
You define this.cssreducerfunc= function(obj,...junk){

Do stuff you want and return it}.bind(this) 


Bind usually not needed and a memory synch

**Comment by jfrazzano** [comment] 2017-09-26 11:49
Sink

**Comment by vdegenne** [comment] 2017-09-26 16:42
I decide to answer with a personal method I am using, I can't really tell you if this method is recommended or not but for me it happens it has been the best choice for styling my applications.

As you say there is the `include` property for including styles inside the fragment of your custom polymer element. However this is replicating data, everytime you use the `include` attribute the style module is inserted inside the shadow dom of your element, and personally I sneeze everytime I see data replicated. Even if computers are faster and faster or your style modules are smalls, the performance won't really be downgraded you know but for me it isn't right to import a palette of styles inside a custom element, because most of the shared styles won't be used (sometimes you just need to use few styles of the palette for some elements) and also because this `include` attribute looks more like a hack than a real browser implementation thing.  
I think the Polymer team understands that and are working on a solution in Polymer 3.0 to make a more natural way of styling a hand of elements that are in disassociated scopes ([check this nice talk of Steve Orvell](https://www.youtube.com/watch?v=rvpJ5O0W_6A) for more information).  

As for Polymer 2.0 and the method I am using, I make an html import with all my element in this form

```html
<custom-style>
  <style>
    html {
      ...
    }
  </style>
</custom-style>
```

And define some mixins or css variables : 

```css
html {
  --my-variable-style: 30px;

  --my-mixin-style: {
    box-shadow: 0 0 1px 1px rgba(0, 0, 0, .3);
    border: 1px solid red;
  }
}
```

And I can use this variables in my custom elements like that

```html
<dom-module id="my-element">
  <template>
    <style>
      :host {
         @apply --my-mixin-style;
         margin-top: var(--my-variable-style);
    </style>
  </template>
  <script> ... </script>
</dom-module>
```

Hope that will help you.

**Comment by pdesjardins90** [comment] 2017-11-15 16:27
I'm one of those guys that manually imports a css-reset in every component in his app (100+).

IMO, the real problem is that shadow dom encapsulation isn't a total encapsulation. Its inner styles are encapsulated alright, but outer styles, like browser defaults leak in *by design*. 

Components should have a way to provide a strict, fully encapsulated styling interface. Otherwise you're welcoming side effects and high maintenance.

For the specific case of manually importing a css module in every component everywhere, I feel  \<custom-style> should be the element that takes care of it. It should register one or more \<style> that are prepended once whenever a component that extends Polymer.Element is instantiated.

**Comment by sorvell** [comment] 2017-12-11 23:04
@pdesjardins90 Allow me to explain the ShadowDOM design by breaking this down into 3 categories of styling: 

 1. styling based on selectors matching in user stylesheets: Out of the box, ShadowDOM provides encapsulation for this by ensuring that only styles in a given shadowRoot/document match elements in the same scope.
 1. styling based on inheritance (e.g. `font: sans-serif` is an inherited property): By adding a style `:host { all: unset;}` to a style in a shadowRoot, you can provide encapsulation for inherited properties (https://css-tricks.com/almanac/properties/a/all/).
  1. styling based on selectors matching in user agent (browser controlled) stylesheets: You can think about these styles as styling these elements are providing for themselves (just like another custom element might do). For these elements, one should implement selectors to customize the behavior (e.g. `input { padding: 2em }`). 

Note also that the coming [CSS Shadow Parts](https://tabatkins.github.io/specs/css-shadow-parts/) spec should make theming easier to accomplish across sets of elements.

**Comment by sorvell** [comment] 2017-12-11 23:05
Closing this as support for `shady-unscoped` has been added. This provides a more efficient "reset" mechanism when Shady DOM is used.

**Closed by sorvell** 2017-12-11 23:05 UTC
Labels: 1.x, 1.x-2.x compatibility, 2.x, p1, source: hooli

**Comment by pdesjardins90** [comment] 2017-12-12 15:44
@sorvell Thanks for the clarifications, you schooled me there with the `:host { all: unset; }`, didn't know that existed! 

I see your point as thinking of native elements as other custom elements that define their own styles, I had the wrong impression that their styles were somehow defined top-level and inherited all the way down in components, bypassing encapsulation. 

I had the pleasure to use [Vaadin's Themable Mixin](https://github.com/vaadin/vaadin-themable-mixin) recently, which emulates shadow parts and themes, and it solved alot of pains I had with cross app styling. Looking forward for the native version to happen!
