### ISSUE TITLE
change event in not existing element

### ISSUE THREAD

**Issue by ms123s** [Polymer/polymer#2355] opened 2015-08-24 14:01 UTC
Is this wrong or feature?
valueChanged is two times called.
The second time with value == null.
But when value == null,  the "test-element2" should not existent.
 if="[[value]]"

Manfred Sattler

```html
<dom-module id="test-element2">
    <script>
      Polymer( {
        is: "test-element2",
        properties: {
          value: {
            observer: "valueChanged",
            type: String
          }
        },
        valueChanged: function() {
          console.log( "valueChanged:", this.value );
        }
      } );
    </script>
  </dom-module>
        
  <dom-module id="test-element">
    <template>
      <template is="dom-if" if="[[value]]" restamp>
        <test-element2 value="[[value]]"></test-element2>
      </template>
    </template>
    <script>
      Polymer( {
        is: 'test-element',
        attached: function() {
          this.value = "Hello";
          this.async( function() { this.value = null; }, 200 );
        }
      } );
  
    </script>
  </dom-module>

  <test-element>
```

**Comment by arthurevans** [comment] 2015-08-24 17:50
In the Polymer 0.5 world, this might have worked as you expected. However, there are two or three things at work here:

1) Bindings are managed by the host element, not the template or an external system. In this case, your `test-element` has a list of "property effects" that occur when `value` changes. One of these sets the `if` property on the template, and one sets the `value` property on `test-element2`. I'm not sure whether there is a defined order here, or whether this is racy. (@sorvell or @kevinpschaaf can perhaps clarify?)

2) The template stamping isn't necessarily synchronous -- the template fires a `dom-change` event once it's performed all of the DOM manipulations. (https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-change) So it should all be done by the time the `dom-change` event handler is called, right? Except ...

3) Shady DOM tree changes are performed asynchronously. (https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api) This appears to be the actual culprit here. Check out the following jsbin:

http://jsbin.com/vohata/edit?html,console,output

As you'll note, the `dom-change` event gets fired (so the dom-if is getting notified first), then the value change event on the child element. Checking the tree at this time confirms that the child is still there. At this point, the `dom-if` has removed the child, but the remove operation is still pending.

If you call `Polymer.dom.flush()` at this point, a subsequent check shows the child is not there.

Now, if you place the `Polymer.dom.flush()` call inside the `dom-change` handler, the child is removed before the event is fired, and you don't get the spurious event. However, I suspect this is an antipattern, and you'd be better off having the parent ignore the extra event.

**Comment by ms123s** [comment] 2015-08-27 18:04
Is this so desired or an implementation detail that is accepted, because there is no alternative?

What does restamp on the outermost dom-if template?
I thought it makes all things new.
This is, what i want in this case.

I have done a ugly workaround.

The if-condition of the outermost template set to false
and then async after a time the actual values.

in relation to my example:
test-element1 is a form and
test-element2 are maybe many fields.

In case the form changed , all fields change too.

i have this demo (http://web.simpl4.org#!accounts)  ported from 0.5(here works fine)

And with the workaround also in 1.0

**Comment by azakus** [comment] 2015-11-12 20:17
Duplicate of #1716

**Closed by azakus** 2015-11-12 20:17 UTC
