### ISSUE TITLE
Enhancement in life cycle callbacks Polymer 2.0-rc.2

### ISSUE THREAD

**Issue by schmeisk** [Polymer/polymer#4412] opened 2017-03-10 16:25 UTC
Today, I stay all day testing the new polymer 2.0. But, I stayed 3 hours to discover a bug that my property observer did not working. And finally I discovered why, because I did not called the super.ready() inside my ready call back. 
It will be awesome that shows a warning or error warning to call super inside the life cycle hook. Because the logic inside the function was working perfectly. I cannot guess that we need to call the super.

Sorry my lack of English and knowledge. But i'ts my opinion.

Thank you for the great job that polymer team is doing.

**Comment by tony19** [comment] 2017-03-10 16:52
This should probably be a feature request for [polylint](https://github.com/PolymerLabs/polylint).

**Comment by tony19** [comment] 2017-03-13 07:31
Looks like a duplicate of https://github.com/Polymer/polymer-linter/issues/52

**Comment by azakus** [comment] 2017-03-16 03:46
Looks like this was added to linter in Polymer/polymer-linter#53

**Closed by azakus** 2017-03-16 03:46 UTC
Labels: 2.x, linter-tool
