### ISSUE TITLE
Lazy loading issue.

### ISSUE THREAD

**Issue by Bunny2242** [Polymer/polymer#4366] opened 2017-03-03 14:25 UTC
I have used lazy loading Polymer.Base.importHref in page.js.After 5 to 10 seconds only it is navigated to the page.Kindly help me how to resolve this.
     page('/home', function() {
                   Polymer.Base.importHref('/components/home/home.html', function() {
                           app.route = 'home';
                   });
  });

**Comment by azakus** [comment] 2017-03-16 04:45
Sorry, I'm not familiar with `page.js`. Can you provide a link to a reproduction with jsbin?

**Comment by balubunny4u** [comment] 2017-03-16 14:22
I can not share my code why because it's secure one.Is there any other solution.

**Comment by web-padawan** [comment] 2017-03-16 14:59
@Bunny2242 you should provide an example repo containing as much code as needed to reproduce. I suggest using PSK 1.x (which used to include `page.js`)

Or you can have a look at those [elements](https://www.webcomponents.org/search/routing).

**Comment by Bunny2242** [comment] 2017-04-04 07:24
I was facing this issue in large size application.If it is app size is less then am not facing this issue.

**Comment by TimvdLippe** [comment] 2017-08-17 03:00
Closing this issue as we can not reproduce it. We can reopen and investigate if you can create a runnable JSBin that shows the issue.

**Closed by TimvdLippe** 2017-08-17 03:00 UTC
Labels: 1.x, pending-response
