### ISSUE TITLE
Add a way to import external css files as styles with "custom-style" tag

### ISSUE THREAD

**Issue by jollycopper** [Polymer/polymer#3451] opened 2016-02-22 05:00 UTC
Currently there is no way to write style as a separate css file. The only way now is to create a style inside of the main html with `is="custom-style"`.

The reason why this is important is that many developers use LESS or SASS to style their webpages, but in Polymer their workflow no longer works.

**Comment by zoechi** [comment] 2016-02-22 05:46
dup of #2429 I guess
See especially this comment https://github.com/Polymer/polymer/issues/2429#issuecomment-166181555

**Comment by azakus** [comment] 2016-02-26 01:09
Yep, mostly a dupe of #2429, but there are workarounds (https://github.com/Polymer/polymer/issues/2429#issuecomment-166181555).

The problem here is that Polymer needs to process styles to work for both ShadyDOM encapsulation, and for CSS Custom Properties.
@arthurevans mentions why `<link rel="stylesheet">` is problematic in https://github.com/Polymer/polymer/issues/2429#issuecomment-141550061

**Closed by azakus** 2016-02-26 01:09 UTC
