### ISSUE TITLE
[0.9] if="{{ 1 < 2 }}" not supporded?!

### ISSUE THREAD

**Issue by teckays** [Polymer/polymer#1499] opened 2015-05-07 12:30 UTC
This si not working!
```html
<template is="dom-repeat" items="{{items}}">
    <template is="dom-if" if="{{index == 2}}">
      <!-- show third item -->
    </template>
</template>
```

a bug or a feature?

**Comment by teckays** [comment] 2015-05-07 12:30
http://jsbin.com/qevuzupoti/1/edit

**Comment by arthurevans** [comment] 2015-05-07 21:22
Feature. No expressions are supported in bindings, except for ! and inline functions.

https://www.polymer-project.org/0.8/docs/migration.html#data-binding

In general, expressions like this can be replaced with inline functions or computed properties, like this:

    <template is="dom-if" if="isIncluded(index)">

However, it appears that inline functions can't be defined on an auto-binding template. Not sure whether that's a bug or not.

**Comment by arthurevans** [comment] 2015-05-07 21:27
Opened #1500 for autobinding template issue. Closing this because it's working as intended.

**Closed by arthurevans** 2015-05-07 21:27 UTC

**Comment by chuckh** [comment] 2015-05-07 23:45
@arthurevans I think you mean this:
```
 <template is="dom-if" if="{{isIncluded(index)}}">
```

I have a working example at http://plnkr.co/edit/7KKqwIVVKVXt44nkuBgi?p=preview using this syntax with a custom element. It does not work using `auto-bind`

**Comment by arthurevans** [comment] 2015-05-08 02:09
Yep, I was writing too fast there. Thanks, Chuck.

**Comment by teckays** [comment] 2015-05-08 22:32
Ok, thanks for pointing out!

**Comment by kevinpschaaf** [comment] 2015-05-09 01:26
@teckays Also note, the case you showed is a good candidate for using the `filter` feature of `dom-repeat`.  It doesn't support filtering based on index (so if that's really your use case maybe not), but if your `item` has the criteria you would use to switch the `dom-if`, you'd be better using `filter` than `dom-if`, since you'd be stamping less stuff.

http://jsbin.com/dogizasicu/1/edit?html,console,output

**Comment by teckays** [comment] 2015-05-09 15:36
@kevinpschaaf didn't know about the `filter` attribute, thank you for sharing, will definitely use it when appropriate. The use case I have requires stamping all items but some of them treat in a different way.
