### ISSUE TITLE
this.$ doesn't work inside dom-if but this.$$(selector) does

### ISSUE THREAD

**Issue by johnlim** [Polymer/polymer#3612] opened 2016-04-22 15:43 UTC
### Description
this.$ doesn't work inside dom-if but this.$$(selector) does

#### Live Demo
https://github.com/johnlim/todo-list/tree/iron-query-media-bug

#### Steps to Reproduce
1. Clone the repo
2. Check out the branch `iron-media-query-bug`
3. Run the app using `gulp serve`
4. Type into the paper-input
5. From the console output, it can be seen that this.$ does not select paper-input but this.$$() does.
 

#### Expected Results
this.$ should work

#### Actual Results
this.$ doesn't select the element but this.$$() does

### Browsers Affected

- [* ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by ebidel** [comment] 2016-04-22 17:31
Dupe of https://github.com/Polymer/polymer/issues/642

**Closed by ebidel** 2016-04-22 17:31 UTC
