### ISSUE TITLE
impossible to print a page created with Polymer on Chrome

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [Polymer/polymer#2518] opened 2015-10-02 08:35 UTC
But print function works on IE and Firefox

**Comment by tjsavage** [comment] 2015-10-02 17:43
I'm unable to reproduce this - I'm able to print https://www.polymer-project.org/summit on Chrome 45.0.2454.101

**Comment by samccone** [comment] 2015-10-02 17:54
highly relevant https://github.com/PolymerElements/polymer-starter-kit/issues/376 :fax:

**Comment by robrez** [comment] 2015-10-02 19:16
I've wondered about this, too...
https://github.com/PolymerElements/paper-drawer-panel/issues/84

I can duplicate this over at the [element catalog](https://elements.polymer-project.org/browse?package=paper-elements)

Chrome: Version 45.0.2454.101 m
Windows 7

**Comment by tjsavage** [comment] 2015-10-02 21:42
You're right, I'm able to repro on catalog as well. Will dig in.

**Comment by claust** [comment] 2015-10-16 11:24
The Polymer main page fails to print in Chrome 46.6.0.2490.71 m.

https://elements.polymer-project.org/

**Comment by chuckh** [comment] 2016-01-10 23:45
On Mac OS El Cap with Chrome 47.0.2526.106 (64-bit) I was able to get the below to print using Polymer Starter Kit by:

1. Go to http://polymerelements.github.io/polymer-starter-kit/
2. Do a Select All
3. Right clicking on page and selecting Print

It will only print what is visible on the screen and selected. 

![image](https://cloud.githubusercontent.com/assets/19915/12224892/5ddfc9d6-b7b0-11e5-910a-b7d2e2cb018f.png)

**Comment by robdodson** [comment] 2016-01-10 23:52
Kinda wondering if we need a member of the Chrome team to look into this...

**Comment by chuckh** [comment] 2016-01-11 00:09
I got PSK printing on Safari 9.0.1 and MS Edge to print without using Select All. Firefox 43 just printed blank pages with or without Select All.

> Kinda wondering if we need a member of the Chrome team to look into this... :+1: 

MS Edge printing PSK.
![image](https://cloud.githubusercontent.com/assets/19915/12224987/12e95a4c-b7b4-11e5-90e6-942148e3e5a6.png)

**Comment by TimvdLippe** [comment] 2017-08-10 21:49
I can print on both Chrome and Firefox, therefore closing this issue. If you can still repo this, please let us know!

**Comment by chuckh** [comment] 2017-08-14 15:21
@TimvdLippe still having the same printing issue with the latest version of PSK using Polymer 2. See below it should be two pages but is only one.

### From Mac using Chrome Version 60.0.3112.90 (Official Build) (64-bit) doing a file print.
![image](https://user-images.githubusercontent.com/19915/29278033-61765244-80c8-11e7-81f4-d885ed7da23f.png)

###  From Mac using Chrome Version 60.0.3112.90 (Official Build) (64-bit) selecting text manually and doing file print.
![image](https://user-images.githubusercontent.com/19915/29278313-370d731a-80c9-11e7-8dc0-225e2c819010.png)

**Comment by TimvdLippe** [comment] 2017-08-14 18:29
Okay, so the issue here is probably related to scrolling. Reopening for now :smile:

**Comment by robrez** [comment] 2017-08-14 19:22
Would that be expected when using `app-layout-*` and something other than the "document" as the scroll target?

eg `fullbleed`, `has-scrolling-region`:

https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L78-L92

**Comment by TimvdLippe** [comment] 2017-08-14 19:58
Tagging @frankiefu for the above comment ^^

**Closed** 2022-04-16 08:02 UTC
Labels: wontfix, p3, needs investigation, 1.x
