### ISSUE TITLE
Not all listeners for scroll events added with passive option

### ISSUE THREAD

**Issue by dhrytsenko** [Polymer/polymer#4702] opened 2017-06-20 15:12 UTC
### Description

l work on PWA build with Polymer 2 and try to check it performance and other stuff with Lighthouse. I got one error about scroll listeners: `Uses passive listeners to improve scrolling performance` on line 434 in `/polymer/lib/utils/gestures.html` file. 
l saw that you already added passive listeners for scroll event but I think you missed few listeners which added without `{passive: true}` option for event like `touchstart` and `touchend` in `_add` function. Can you fix it?

### Example

![Lighthouse result](https://i.imgur.com/YTyCjDq.png)

### Browsers Affected

- [ ] Chrome

### Versions
- Polymer: v2.0.1

**Comment by azakus** [comment] 2017-06-22 18:50
Dupe of https://github.com/Polymer/polymer/issues/4667

**Closed by azakus** 2017-06-22 18:50 UTC
Labels: 2.x, p1
