### ISSUE TITLE
Uncaught NS_ERROR_UNEXPECTED in Polymer.Base._addFeature({ ... fire : ... } in Firefox

### ISSUE THREAD

**Issue by TobiasStockinger** [Polymer/polymer#1936] opened 2015-06-22 12:37 UTC
I noticed that in some cases, firing property-change events throws exceptions in Firefox (38.0.5). Other browsers (tested Chrome / Safari) don't bother. I'm using Polymer 1.0.0

I tracked down the source and it seems to happen in polymer.html
``` javascript 
Polymer.Base._addFeature({
    // ... 
    fire : function(type, detail, options){
        // ... 
        node.dispatchEvent(event); // <--- the exception is thrown here
        // ...
    }
    // ...
})
```

As a workaround, adding a try-catch block temporarily worked for me without any noticeable disadvantage (of course that depends on your code).

![screenshot 2015-06-22 14 17 47](https://cloud.githubusercontent.com/assets/6648745/8281827/0f6556ee-18ec-11e5-888e-b4541807dd6e.png)

My stacktrace with isolated custom dom-modules:
```
"EventTarget.prototype.dispatchEvent@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:1365:17.fire@http://localhost:3000/bower_components/polymer/polymer.html.js:1020:8._bindValueChanged@http://localhost:3000/bower_components/iron-input/iron-input.html.js:115:6._observerEffect@http://localhost:3000/bower_components/polymer/polymer.html.js:1260:0Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0._applyEffectValue@http://localhost:3000/bower_components/polymer/polymer.html.js:1519:0._annotationEffect@http://localhost:3000/bower_components/polymer/polymer.html.js:1245:7Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0._applyEffectValue@http://localhost:3000/bower_components/polymer/polymer.html.js:1519:0._annotationEffect@http://localhost:3000/bower_components/polymer/polymer.html.js:1245:7Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter

@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0._userChanged

@http://localhost:3000/components/ct-registration-form.html.js:210:16._observerEffect

@http://localhost:3000/bower_components/polymer/polymer.html.js:1260:0Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0._applyEffectValue@http://localhost:3000/bower_components/polymer/polymer.html.js:1519:0._annotationEffect@http://localhost:3000/bower_components/polymer/polymer.html.js:1245:7Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0._applyEffectValue@http://localhost:3000/bower_components/polymer/polymer.html.js:1519:0._annotationEffect@http://localhost:3000/bower_components/polymer/polymer.html.js:1245:7Polymer.Bind._modelApi._effectEffects/<@http://localhost:3000/bower_components/polymer/polymer.html.js:1119:0Polymer.Bind._modelApi._effectEffects@http://localhost:3000/bower_components/polymer/polymer.html.js:1116:0Polymer.Bind._modelApi._propertySet@http://localhost:3000/bower_components/polymer/polymer.html.js:1110:0Polymer.Bind._createAccessors/setter@http://localhost:3000/bower_components/polymer/polymer.html.js:1177:0.ready@http://localhost:3000/components/ct-drawer.html.js:68:16._invokeBehavior@http://localhost:3000/bower_components/polymer/polymer-micro.html.js:267:0._doBehavior@http://localhost:3000/bower_components/polymer/polymer-micro.html.js:262:0._readySelf@http://localhost:3000/bower_components/polymer/polymer-mini.html.js:66:0._ready@http://localhost:3000/bower_components/polymer/polymer-mini.html.js:53:0._tryReady@http://localhost:3000/bower_components/polymer/polymer-mini.html.js:42:0._initFeatures@http://localhost:3000/bower_components/polymer/polymer.html.js:2894:0Polymer.Base.createdCallback@http://localhost:3000/bower_components/polymer/polymer-micro.html.js:98:0created@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:6748:6upgradeWithDefinition@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:6718:4instantiate@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:6863:11generateConstructor/<@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:6876:13createElement@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:6897:0@http://localhost:3000/:36:17invoke@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:1090:54dispatchBubbling@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:1047:8dispatchEvent@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:1018:10dispatchOriginalEvent@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:973:0EventTarget.prototype.dispatchEvent@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:1365:17forwardMethodsToWrapper/</</constructor.prototype[name]@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:349:19bootstrap/<@http://localhost:3000/bower_components/webcomponentsjs/webcomponents.js:7011:0"
```

**Comment by kevinpschaaf** [comment] 2015-06-23 01:00
Do you happen to have any `<input is="iron-input">`'s that are `disabled`?

I can reproduce that FF error here by setting the input to disabled: http://jsbin.com/dokihi/edit?html,console,output

There is a discussion of this bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=889376, but it is closed as "RESOLVED WORKSFORME", even though the jsFiddle in the issue (http://jsfiddle.net/t4D7m/1/) still seems to fail on FF 38.  However, https://bugzilla.mozilla.org/show_bug.cgi?id=867418 looks like the same bug, which is duped to https://bugzilla.mozilla.org/show_bug.cgi?id=329509, which has been open since 2006.

This is problematic for type-extensions of form controls, since Polymer utilizes custom events for data-binding.  Will need to consider workarounds.

**Comment by TobiasStockinger** [comment] 2015-06-23 08:24
> Do you happen to have any <input is="iron-input">'s that are disabled?

That's the problem, yes! Thanks for the clarification and the links.
For my particular case, catching (and ignoring) the exception works.

**Comment by dominik0711** [comment] 2015-07-07 10:20
@TobiasStockinger Could you please share your catching code? Thanks!

**Comment by TobiasStockinger** [comment] 2015-07-08 13:34
Sure, but it's really just a simple try/catch around the .dispatchEvent() .... I'm not doing anything to properly handle the exception. 

``` javascript
fire: function (type, detail, options) {
  options = options || Polymer.nob;
  var node = options.node || this;
  var detail = detail === null || detail === undefined ? Polymer.nob : detail;
  var bubbles = options.bubbles === undefined ? true : options.bubbles;
  var cancelable = Boolean(options.cancelable);
  var event = new CustomEvent(type, {
    bubbles: Boolean(bubbles),
    cancelable: cancelable,
    detail: detail
  });
  try{ // leads to NS_ERROR_UNEXPECTED in Firefox
    node.dispatchEvent(event);
  }
  catch(e){
    console.log("could not dispatch event");
  }
  return event;
}
```

**Comment by kevinpschaaf** [comment] 2015-07-30 01:43
For now, we've decided to fix this in `iron-input` rather than Polymer.

Closing in lieu of https://github.com/PolymerElements/iron-input/issues/47

**Closed by kevinpschaaf** 2015-07-30 01:43 UTC
Labels: p1
