### ISSUE TITLE
Typings for Polymer.mixinBehavior() assume a concrete type

### ISSUE THREAD

**Issue by kito99** [Polymer/polymer#5054] opened 2018-01-19 22:15 UTC
### Description

The typings for `Polymer.mixinBehavior()` do not allow use of abstract classes. 

#### Steps to Reproduce

Example:

```typescript
class MyappView1 extends Polymer.mixinBehaviors([Polymer['AppLocalizeBehavior']], NowElements.BaseView) {
}
```

Where `NowElements.BaseView` is an abstract class that extends `Polymer.Element`.

#### Expected Results

Successful compilation and execution.

#### Actual Results

TypeScript compilation error: 

```
Error:(8, 84) TS2345: Argument of type 'typeof BaseView' is not assignable to parameter of type 'new () => BaseView'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.
```

### Browsers Affected
All

### Versions
master

What's a little frustrating about this is that the everything works fine if you change the type declaration to the following:

```typescript
 function mixinBehaviors(behaviors: object|object[], klass: any): any;
```

Clearly this is a pretty unsafe type declaration, but since the code runs, it's clear that JavaScript has no problem using an abstract class; it's a TypeScript issue.

I'm not sure there's a good solution for this, given there is a TypeScript limitation: https://github.com/Microsoft/TypeScript/issues/5843, but I think it's worth discussion so we can at the very least say something in the docs.

**Comment by TimvdLippe** [comment] 2018-02-06 22:22
It appears that the upstream TypeScript issue has been closed as [working as intended]: https://github.com/Microsoft/TypeScript/issues/5843#issuecomment-363264050 Not sure how we can resolve this issue.

**Comment by TimvdLippe** [comment] 2018-02-10 13:40
Per https://stackoverflow.com/questions/12802317/passing-class-as-parameter-causes-is-not-newable-error I thought `typeof T` would work here, but sadly that did not work either as it is a generic type :cry:

**Closed** 2022-04-17 09:02 UTC
Labels: wontfix, p2, typescript
