### ISSUE TITLE
Evergreen browser incompatibility

### ISSUE THREAD

**Issue by odysseefastgood** [Polymer/polymer#1706] opened 2015-06-01 13:12 UTC
Running any page of http://polymer-project.org/ on Firefox 38 shows a broken page.

The image below speaks by itself.

![screen shot 2015-06-01 at 3 06 54 pm](https://cloud.githubusercontent.com/assets/12143642/7913452/6351cf94-0870-11e5-9690-19f5ae669b5b.png)

I thought it was because of 0.5 and 0.8 earlier, but it's now "stable".

**Comment by clintonjrobinson** [comment] 2015-06-01 16:43
@odysseefastgood strange.  Works on Ubuntu 15.04 w Firefox 38.0


![screenshot from 2015-06-01 12 42 25](https://cloud.githubusercontent.com/assets/1816175/7917910/bd2757e2-085b-11e5-8b2f-01f0cf77ad7d.png)

**Comment by vinyll** [comment] 2015-06-01 17:50
Wow, thanks for the reply!
I'm quite amazed by this bug as none of my developments with polymer 0.5/0.8/1.0 work on firefox 38 Mac (nor previous) yet work on Firefox 40 (dev version).
I tried on Firefox 38 Windows and it does work.
I'll have to test on some other Mac and let you know (or re-open) if I can reproduce.

**Comment by arthurevans** [comment] 2015-06-01 20:25
If looks like what you're seeing is an issue with the experimental native web components flag on Firefox. It's actually a bug in the polyfills, which don't gracefully handle having some but not all of the web components available. See previous report here:

https://github.com/Polymer/docs/issues/1034

It also affects 1.0, although it doesn't appear to be as severe. (The site itself is still running 0.5.)

**Comment by vinyll** [comment] 2015-06-01 20:57
I confirm that going to `about:config` and turning `dom.webcomponents.enabled` to `false` solves the issues.
cf https://github.com/Polymer/docs/issues/1034
I was puzzle that Polymer would not "even" work on a stable Firefox but now I'm confident to go further!
Thanks for that.

**Comment by ebidel** [comment] 2015-06-02 03:45
Closing :)

**Closed by ebidel** 2015-06-02 03:45 UTC
