### ISSUE TITLE
Behavior property overwritting doesn't set/remove 'readOnly'.

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#2372] opened 2015-08-26 12:02 UTC
Combining two behaviors, `SubBehavior` and `SupBehavior`, that have the same property.

``` js
Polymer.SubBehavior = {
    properties: {
        myProperty: {
            value: 3000
        }
    }
};

Polymer.SupBehavior = {
    properties: {
        myProperty: {
            value: 3000,
            readOnly: true
        }
    }
}

Polymer.MyBehavior = [
    Polymer.SubBehavior,
    Polymer.SupBehavior
]
```

Will block the property's `readOnly` to whatever the first behavior declared. In the case above `myProperty` won't be read only.

**Comment by TimvdLippe** [comment] 2018-03-16 20:57
Per https://github.com/Polymer/polymer/blob/46299339ba3e8a6a099d73cc85aa47bbaffb608b/lib/mixins/element-mixin.html#L150-L154 this is working as intended. These fields are designed to not be overridden. Only `observer` is "duplicated" in that sense. Therefore I am closing this issue.

**Closed by TimvdLippe** 2018-03-16 20:57 UTC
Labels: 1.x, p2

**Comment by Pupix** [comment] 2018-03-16 21:41
A blast from the past 😄
