### ISSUE TITLE
reflectToAttribute

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4466] opened 2017-03-28 09:24 UTC
The data cannot be two-way or one way bounded,only decided by the very component.
How can I write like this
 ```
<parent-component showInquiry></parent-component>
```
to decide whether my child-component was show or not?I tried the  reflectToAttribute ,but failed.

```
//...
  properties: {
                showInquiry: {
                    type:'Boolean',
                    value:false,
                    notify:true,
                    reflectToAttribute: true,
                  },
//...
  [[showInquiry]] [[a]]

        <template is="dom-if" if="[[showInquiry]]" strip-whitespace >
```

**Comment by web-padawan** [comment] 2017-03-28 09:49
@yanlee26 In order to configure camel-case properties of elements using attributes, dash-case should be used in the attribute name. See [attribute deserialization](https://www.polymer-project.org/1.0/docs/devguide/properties#attribute-deserialization) for details.

So you need to change your code like this:
```html
<parent-component show-inquiry></parent-component>
```

**Comment by sorvell** [comment] 2017-04-03 21:07
Thanks for that good explanation @web-padawan. Closing since the issue is addressed by the previous comment.

**Closed by sorvell** 2017-04-03 21:07 UTC
