### ISSUE TITLE
appending DOM element to local dom does not apply styles

### ISSUE THREAD

**Issue by yattias** [Polymer/polymer#3100] opened 2015-11-29 06:04 UTC
Hi,

Within my Polymer (``v1.2.3``) element, I need to dynamically append newly created DOM elements to certain local DOM nodes. The elements I am appending contain a ``class="foo"``, where class ``foo`` has styles scoped within my polymer element.

The problem I am facing is that these styles are not applied to the elements. 

The following code will exemplify the issue:

```
      attached: function () {
        var el = document.createElement("span");
        el.textContent = "Woof. Woof. Meow!";
        el.classList.add("foo");

        Polymer.dom(this.root).querySelector(".bar").appendChild(el);
      }
```

Here is the template:

```
<dom-module id="my-element">
<template>

<style>
   .foo {
        color: red; 
  }
</style>
<div class="bar"></div>
<div class="baz"><span class="foo">I am not added dynamically!</span></div>

</template>
...
</dom-module>
```

In the above template, the element ``.foo`` within ``.baz`` will have styles applied to it but, element ``.foo`` within ``.bar`` would not (polymer's class ``style-scope`` is no applied to it).

Some additional info:
-  ``style-scope`` not added to dynamically created elements.
-  ``Polymer.dom(this.root).appendChild(el)`` applies styling but, does not add it at desired location.
- Calling ``updateStyles()`` or ``Polymer.dom.flush()`` explicitly after the element is added, does not resolve the issue.

**Comment by zoechi** [comment] 2015-11-29 06:26
sounds similar to #2701. The workaround for me is to use

```
<style>
   :host:: content .foo, 
   .foo {
        color: red; 
  }
</style>
```

**Comment by yattias** [comment] 2015-11-29 06:32
Yup. That certainly did it :+1:

**Comment by azakus** [comment] 2016-02-11 20:50
Closing as duplicate of #2701

**Closed by azakus** 2016-02-11 20:50 UTC

**Comment by dlsso** [comment] 2016-07-05 20:51
A note for those using compiled style sheets:

zoechi's workaround won't work, but an alternative solution I found was doing `Polymer.dom(this.root).appendChild(el) // works but at the wrong location as noted by yattias
Polymer.dom(this.root).querySelector('.your-selector-here').appendChild(el) // move  to correct location.`
