### ISSUE TITLE
gestures.html adds non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4667] opened 2017-06-06 00:06 UTC
This causes chrome to log Violation warnings
<img width="720" alt="screen shot 2017-06-05 at 5 04 35 pm" src="https://cloud.githubusercontent.com/assets/6173664/26808388/39b0f87e-4a11-11e7-8e96-862b48fe18fa.png">

**Comment by azakus** [comment] 2017-06-06 22:36
I will need this to be non-passive for browsers that don't support native `touch-action`, but I can make this better for Chrome

**Comment by BoefAE** [comment] 2017-06-19 18:38
I'm having the same issue, simular issue seems to appear on FireFox as well.

**Comment by davidmaxwaterman** [comment] 2017-06-20 14:57
I get thousands of these messages in my 1.9 app, all originating from within Polymer. I guess they're not from the same file since it's 2.x (right?), though I'm not too sure how to find that out. Is there any hope of getting these messages removed in 1.9 too?

**Comment by azakus** [comment] 2017-06-22 22:35
Hmm, I'm worried about the backwards compatibility with this change given the fact that `gestureEvent.preventDefault()` can call `touchEvent.preventDefault()`. Maybe this is best served as an opt-in for 2.x.

**Comment by BoefAE** [comment] 2017-06-25 16:27
Updated gestures.html with your update, works fine now. T.hanks!

**Comment by TimvdLippe** [comment] 2017-08-10 18:14
@krisu7 when #4724 is merged. The problem there is that we are not able to (regression) test the feature

**Closed** 2017-09-11 22:03 UTC
Labels: 2.x, p1

**Comment by govis** [comment] 2018-11-21 21:02
<code>[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.</code> seems to be back in Polymer 3. 

I have <code>setPassiveTouchGestures(true);</code> and use passive gesture listeners as per https://polymer-library.polymer-project.org/2.0/docs/devguide/gesture-events#use-passive-gesture-listeners

Also "Use passive gesture listeners" section is missing form the Polymer 3 Gesture Events TOC: https://polymer-library.polymer-project.org/3.0/docs/devguide/gesture-events

**Comment by govis** [comment] 2018-11-21 21:15
It looks like we may need to set <code>setPassiveTouchGestures(true);</code> before importing any elements that may add gesture listeners in it's constructor

**Comment by govis** [comment] 2018-11-21 21:15
It looks like we may need to set setPassiveTouchGestures(true); before importing any elements that may add gesture listeners in its constructor
