### ISSUE TITLE
TypeError: Cannot read property '_children' of undefined

### ISSUE THREAD

**Issue by Mygod** [Polymer/polymer#2076] opened 2015-07-13 15:46 UTC
Part of my code that's causing the problem:

    <template is="dom-bind">
        <firebase-collection order-by-child="wins" location="..."
                             data="{{leaderboard}}"></firebase-collection>
        <paper-material>
            <ol>
                <template is="dom-repeat" items="[[leaderboard]]">
                    <li>
                        <span>[[item.wins]]</span>
                        wins by
                        <a href="[[item.website]]" target="_blank">[[item.nickname]]</a>
                    </li>
                </template>
            </ol>
        </paper-material>
    </template>

Whenever I update the `wins` of current user, his entry will be gone and never added back. I also get this error:

    TypeError: Cannot read property '_children' of undefined
     at dom-repeat.Polymer._detachRow (http://localhost/bower_components/polymer/polymer.html:3676:24)
     at dom-repeat.<anonymous> (http://localhost/bower_components/polymer/polymer.html:3655:16)
     at Array.forEach (native) at dom-repeat.Polymer._applySplicesArraySort (http://localhost/bower_components/polymer/polymer.html:3653:9)
     at dom-repeat.Polymer._render (http://localhost/bower_components/polymer/polymer.html:3524:6)
     at dom-repeat.Polymer.Templatizer._flushTemplates (http://localhost/bower_components/polymer/polymer.html:3102:8)
     at Object.Debouncer.complete (http://localhost/bower_components/polymer/polymer.html:986:15)
     at Object.Polymer.Async._atEndOfMicrotask (http://localhost/bower_components/polymer/polymer.html:947:1)

Any help would be greatly appreciated.

**Comment by kevinpschaaf** [comment] 2015-07-13 17:10
This looks like a duplicate of #2009, which is a P1 issue we're working to resolve.

**Closed by kevinpschaaf** 2015-07-13 17:10 UTC

**Comment by Mygod** [comment] 2015-07-16 03:17
UPDATE: I just build the master branch of polymer and it seems mine is still unresolved.

    TypeError: Cannot read property '_children' of undefined
    at dom-repeat.Polymer._detachRow (http://localhost/bower_components/polymer/polymer.html:3676:24)
    at dom-repeat.<anonymous> (http://localhost/bower_components/polymer/polymer.html:3655:16)
        at Array.forEach (native)
        at dom-repeat.Polymer._applySplicesArraySort (http://localhost/bower_components/polymer/polymer.html:3653:9)
        at dom-repeat.Polymer._render (http://localhost/bower_components/polymer/polymer.html:3524:6)
        at dom-repeat.Polymer.Templatizer._flushTemplates (http://localhost/bower_components/polymer/polymer.html:3102:8)
        at Object.Polymer.Debounce.Debouncer.complete (http://localhost/bower_components/polymer/polymer.html:986:15)
        at Object.Polymer.Async._atEndOfMicrotask (http://localhost/bower_components/polymer/polymer.html:947:1)

And I just realized if there's only one property updated it works fine. If there're two properties (of the same item) getting updated, it will remove the item and the following item at the same time and throw this exception.
