### ISSUE TITLE
Starter Kit not working, because of customElements.define

### ISSUE THREAD

**Issue by DiiLord** [Polymer/polymer#4641] opened 2017-05-29 18:12 UTC
#### Steps to Reproduce

1. Set up Polymer 2 Starter Kit
2. Serve it with Polymer CLI

#### Expected Results

See the Basic Starter Kit layout

#### Actual Results

No Page, instead errors (a lot).

Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.0
- webcomponents: v1.0.0

**Comment by arthurevans** [comment] 2017-05-30 16:46
The live demo you linked to appears to work fine, and I can't reproduce the errors you're seeing when creating a new PSK project using Polymer CLI 1.1.0 and Chrome 59. Did you see any bower errors when initializing the project?

**Comment by arthurevans** [comment] 2017-05-30 20:07
Oh, wait. Are you by any chance using device emulation in DevTools?

One issue we've seen is that if you switch devices (for example, from emulating an iOS device to emulating an android device) the browser may cache an incompatible set of files (i.e., a mixture of ES5 (compiled) and ES6 (uncompiled) files. 

This is because `polymer serve` by default compiles on the fly based on the user agent it receives from the browser, and in this case DevTools is changing the user agent string when you change devices.

You can work around this by forcing `polymer serve` to always compile, or to never compile:

```
polymer serve --compile never # more performant on most browsers
polymer serve --compile always # should run on any browser
```

So for example if you're just testing in Chrome with device emulation, use `--compile never`.

**Comment by DiiLord** [comment] 2017-06-01 11:18
It still throws the same error :(

**Comment by nazar-pc** [comment] 2017-08-03 23:00
This started happening in my custom project when upgraded from Polymer 2.0.1 to Polymer 2.0.2.
I'm not using any of Polymer's tooling besides `closure` gulp task.

**Comment by TimvdLippe** [comment] 2017-08-04 00:40
I am only using `yarn run build estimate-size` to get the working bundle, there was some confusion about `closure`. @sorvell is this the thing you were talking about with my initial confusion of the gulp-tasks?

**Comment by TimvdLippe** [comment] 2018-01-27 21:55
I am unable to reproduce the reported issues. I suspect they have been fixed in the mean time in the tooling or PSK.

**Closed by TimvdLippe** 2018-01-27 21:55 UTC
Labels: 2.x, pending-response
