### ISSUE TITLE
Text doesn't bind when <span> has attributes

### ISSUE THREAD

**Issue by japacible** [Polymer/polymer#1571] opened 2015-05-20 06:26 UTC
Let's say `helloWorldText` = 'Hello World'.

The following renders: `Hello World`
`<span>[[helloWorldText]]</span>`

However, when I add any attributes to <span>, such as `class` or `on-click`, the text binding isn't rendered. For example, the two following examples renders: `[[helloWorldText]]`

`<span class="foo">[[helloWorldText]]</span>`
`<span class="foo" on-click="onClick">[[helloWorldText]]</span>`

It looks like I need to add an extra <span> around the text binding to render, like this:

`<span class="foo"><span>[[helloWorldText]]</span></span>`
`<span class="foo" on-click="onClick"><span>[[helloWorldText]]</span></span>`

Is this expected? Should I be surrounding any/all `[[textBinding]]` with plain `<span>` tags?

I'm currently using 0.8. Thanks!

**Comment by arthurevans** [comment] 2015-05-20 06:55
That's definitely a bug. I can't reproduce it in 0.9:

http://jsbin.com/bipobu/2/edit#H:L24

I can't reproduce it in 0.8-rc.2, either. Do you know exactly what version you have?

You will get this if you have any whitespace around the binding, but I've never seen it when the span has an attribute on it.

**Comment by japacible** [comment] 2015-05-20 15:49
We're using v0.8.0-rc.7. Here's our current [bower.json](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/polymer/v0_8/bower.json&l=5).

Could I provide any other info that would be helpful?

**Comment by kevinpschaaf** [comment] 2015-05-21 21:40
We could not reproduce this issue.  Can you please try to modify the following JSBin to reproduce the issue?  Thanks.
http://jsbin.com/wefecifogo/1/edit

**Comment by japacible** [comment] 2015-05-29 18:44
Hmm, I can only consistently repro in Chromium with 0.8.0-rc.7. We'll be upgrading to 1.0 soon, so I can remove the extra `<span>` around the text binding when we do so.

Thanks!

**Comment by japacible** [comment] 2015-06-24 02:10
@kevinpschaaf Hey Kevin, this is no longer repro-able on our side.

**Comment by kevinpschaaf** [comment] 2015-06-24 16:31
Thanks for the update, closing.

**Closed by kevinpschaaf** 2015-06-24 16:31 UTC
Labels: pending-response
