### ISSUE TITLE
Data binding using Javascript 

### ISSUE THREAD

**Issue by stefanoantonel** [Polymer/polymer#3420] opened 2016-02-13 19:52 UTC
Hi guys!!! 
I'm trying to create an instance of _service-detail_ element with javascript inside _service-section_ element. 
I've already imported _service-detail_  in _elements.html_. 
For example: 
In **service-section** element: 
```javascript
showDetails: function(e) {
   var detail = document.createElement('service-detail');
   detail.lang = this.lang;
   detail.services = this.services;
}
```
The problem is that if the property **lang** in _service-section_ changes, this change is not propagated to the _service-detail_ element. 

On the other hand, if I use inside the _service-section_ element the tag:
```html
<service-detail lang="{{lang}}" services="{{services}}"></service-detail>
```
When I change the value of the **lang** in _service-section_ it also change in the _service-detail_ . (As it's suppose to work). 

Now the question is, How can I do to bind properties using Javascript and creating the elements dynamically?

Thank you everyone for do the best!

**Comment by bedeoverend** [comment] 2016-02-15 00:50
Hey @stefanoantonel, looks like this might be a duplicate of #1796 and #2638? Those discussions might give you an idea of where imperative data binding is at.

**Comment by azakus** [comment] 2016-02-20 00:56
@bedeoverend agreed, seems like a dupe of #1796 or #2368, which need to be deduped together at some point.

**Closed by azakus** 2016-02-20 00:56 UTC

**Comment by kaste** [comment] 2016-02-23 23:07
I proposed #3460. I used something like this and if I did not messed up the PR this enables something like this:

```
showDetails: function(e) {
   var detail = document.createElement('service-detail');
   this.addCustomEffect('lang', function(path, value, oldValue) {
      detail['lang'] = value;
   };
}
```

**Comment by stefanoantonel** [comment] 2016-03-01 13:36
@kaste Thank you for your proposal !

**Comment by kaste** [comment] 2016-03-01 14:02
Unfortunately the Holy Grail does not answer. 😯

stefanoantonel <notifications@github.com> schrieb am Di., 1. März 2016
14:37:
