### ISSUE TITLE
[1.0] Problem using data-binding and dom-if

### ISSUE THREAD

**Issue by samuelcardillo** [Polymer/polymer#1710] opened 2015-06-01 20:14 UTC
Hi, I am having a huge issue and after few hours trying to solve it with other people on the IRC #polymer , I decided to create an issue here. 

I am creating an element which have a conditional template. If the attribute "img" is not equal to null then it show a paper-toolbar with a background image and everything work well. The problem is that when I call multiple time my element, the image of the last element I called is displayed on all the previously called element as we can see in this image : 

![capture d ecran 2015-06-01 a 22 08 52](https://cloud.githubusercontent.com/assets/7973882/7922183/d39250f0-08aa-11e5-993e-3455e91000a3.png)

Here is the source of the element : http://pastebin.com/04J9jzgx
Here is an example where I am calling it : 
![capture d ecran 2015-06-01 a 22 12 25](https://cloud.githubusercontent.com/assets/7973882/7922253/4fa43532-08ab-11e5-9b82-b3ff325644b2.png)

What we can also see is that for width, it work well. If I change the value of width of the first one, it will not change the second one. I tried many thing such as calling "_changeImage" in created & ready but it doesn't work also. 

I am definitively stuck and I think its an issue with Polymer. I miss the old and easy data-binding in attributes

**Comment by zishanj** [comment] 2015-06-01 22:05
The problem is with `_changeImage` function:

    _changeImage: function(data){
      this.$$("template")._content.children.paperImg.style.backgroundImage = "url('" + data + "')";
    }

You are changing all the child `paperImg`. What you have to do is, change the `id` also for each `paper-toolbar` element and let it be in sequence like `paperImg1`, `paperImg2`... Then you can sets it's image like this:

    this.$.paperImg1.style.backgroundImage = "url('" + data + "')";

Or you better use `dom-repeat` and generate the `id` for `paper-toolbar` dynamically by appending number in sequence and use the above line of code in single function.

**Comment by ledomaine** [comment] 2015-06-02 00:14
Excellent idea ! I tried to do it but it still doesn't work and duplicate the image. I've added an ID attribute when I call the element, like that : 

![capture d ecran 2015-06-02 a 02 00 44](https://cloud.githubusercontent.com/assets/7973882/7925931/3c642a02-08cb-11e5-9926-e1e8de0a81b5.png)

Then the code of _changeImage is now : 

      this.$$("template")._content.querySelector("paper-toolbar").setAttribute("id",this.id);
      this.$$("template")._content.getElementById(this.id).style.backgroundImage = "url('" + data + "')";

The first line is set to give the dynamical attribute to the paper-toolbar and the other one, obviously to change the image. If I do a console.dir like that : ```console.dir(this.$$("template")._content.getElementById(this.id));``` it show me that it got the id ```paper-toolbar#1.style-scope.paper-card``` but the result still change everything... 

Here is the updated code : http://pastebin.com/fzDB6K5v

Thanks in advance

**Comment by ledomaine** [comment] 2015-06-04 22:46
Hi everyone,

Do anyone have any news or something related to this problem  ? I am still trying to find a way to fix it...

Thanks in advance

**Comment by kevinpschaaf** [comment] 2015-07-28 01:17
Sorry for the delay in looking at this.

The example code above that modifies the template content is definitely not what you want; a shared template content is stored per element registration for all nested templates, so modifying that template will affect any future instances, as you discovered.

Instead, in order to modify content stamped in the `dom-if`, the easiest way is to use data-binding.

I made a reproduction using your code, and fixed it to work using more idiomatic usage of Polymer features, like using inline computed functions to calculate inline-style to apply the width and background images:  http://jsbin.com/kebiha/edit?html,output

As an alternative to data-binding, you could listen for the `dom-change` event fired from `dom-if` to know when it is safe to query the local DOM for children that `dom-if` stamps, since `dom-if` stamps lazily and may not be there when you query from an observer, and then simply use `Polymer.dom(this.root).querySelector(...)` (or the shorthand `this.$$(...)`) to query for local dom children and set style properties directly.  However, I'd recommend the data-binding features above.

Closing per the fixed example above, but feel free to re-open and comment if I missed anything.

**Closed by kevinpschaaf** 2015-07-28 01:17 UTC
Labels: p2
