### ISSUE TITLE
Latest Crome Issues

### ISSUE THREAD

**Issue by ACC-Medlink** [Polymer/polymer#4133] opened 2016-11-04 19:33 UTC
### Description
Error thrown - only in latest version of chrome  Version 54

it works fine in Version 53.0.2785.143 m

#### Live Demo

http://crm.accmedlink.net/calendar.html

#### Steps to Reproduce
1) Open http://crm.accmedlink.net/calendar.html in latest chrome build
2) Select Dropdown -- nothing appears

#### Expected Results

Dropdown menu appears
#### Actual Results

Dropdown does not appear
### Browsers Affected

- [ *] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.0.0
- webcomponents: vX.X.X  -- not sure

**Comment by tony19** [comment] 2016-11-04 20:33
Hmm. Cannot reproduce in Chrome 54 and 56. The dropdown from your demo shows up for me (and no console errors):
![screen shot 2016-11-04 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/26580/20021420/a5f6696c-a2a3-11e6-98ea-844482d28b0e.png)

**Comment by caraya** [comment] 2016-11-05 22:18
I can confirm that it works as expected in Chrome 54 running in Yosemite

Also works in Chrome Canary (56) on same platform.

**Comment by sorvell** [comment] 2016-11-07 18:44
Also cannot see the problem on Chrome 54. Can you provide more info on the steps to reproduce? Thanks.

**Comment by TimvdLippe** [comment] 2017-08-17 00:24
Closing per above comment.

**Closed by TimvdLippe** 2017-08-17 00:24 UTC
Labels: 1.x, pending-response
