### ISSUE TITLE
1.2.4 removeChild method returns error

### ISSUE THREAD

**Issue by behnamt** [Polymer/polymer#3388] opened 2016-02-08 12:33 UTC
The following code was working fine in polymer 1.2.3 but after update it returns the following error : 

> Uncaught Error: The node to be removed is not a child of this node: [object Text]

and the last line of error stack is : 
Polymer.Base.extend.removeChild @   polymer-mini.html:775

``` javascript
if (typeof parent !== 'undefined') {
        parent.close();
        while (Polymer.dom(parent).firstChild) {
          Polymer.dom(parent).removeChild(Polymer.dom(parent).firstChild);
        }
      }
```

 "parent" is a bootstrap modal

The only child of "parent" in 1.2.3 is just the bootstrap modal but in 1.2.4 there is another element which actually is a child of parent but somehow it's not.

**Comment by azakus** [comment] 2016-02-09 23:43
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by nibuen** [comment] 2016-03-12 04:11
@azakus @behnamt I just started running int a very similar problem, but using domHost,  I went ahead and make jsbin and assuming that this is same issue.

 https://jsbin.com/togedefike/edit?html,console,output

Notes:
- Doesn't always happen, and different nesting will allow this to work.  Thus the weird nesting I have in example.
- Tried variants for wrapping with Polymer.dom() but hasn't helped. (seems more related to my bin then @behnamt)

**Comment by JosefJezek** [comment] 2016-04-30 12:19
Hint:

For locating dynamically-created nodes in your element’s local DOM, use the $$ method:
`this.$$(selector)`
$$ returns the first node in the local DOM that matches selector.

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html

**Comment by nibuen** [comment] 2016-04-30 23:01
@JosefJezek At least for my part it isn't for dynamically created nodes as you can see in my jsbin.  Ignoring that, not sure what I would try in the jsbin that would be flexible enough to remove the parent as a selector?

**Comment by JosefJezek** [comment] 2016-05-01 06:11
@nibuen Polymer provides a custom API for manipulating DOM such that local DOM and light DOM trees are properly maintained. You can not remove child from parent DOM...

**Comment by nibuen** [comment] 2016-05-01 16:58
@JosefJezek You can and they do, that is the whole point of this issue.

**Comment by dfghi** [comment] 2016-05-12 13:14
I stumbled on this issue as well, I think it's related to this discussion on stackoverflow:
http://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node

In my case it happens consistently, I have a dom-repeat iterating on a templetized element that include in its <content> a dom-if. Apparently when the dom-repeat is refreshed the content of the dom-if is detached (having parentElement/parentNode null) but still satisfies some of the conditions for the removal.
Anyway, except for the errors in the console it actually works for me.

**Comment by marksmits** [comment] 2016-07-15 07:38
I have the same issue with polymer 1.6.0.

<template id="booleanTemplate">
	<template is="dom-if" if="{{column.editable}}">
		<paper-toggle-button value="{{value}}" checked="{{value}}" disabled="{{!column.editable}}"></paper-toggle-button>
	</template>
	<template is="dom-if" if="{{!column.editable}}">
		<span>
			<span class="cell-value">{{formattedValue}}</span>
		</span>
	</template>
</template>

If you for example put an toggle button(also tried paper-input -> same error) inside an if statement which results in the error if i want construct the template.

The error happens on clearing the template instance
Polymer.dom(rowCell).innerHTML = '';

Uncaught Error: The node to be removed is not a child of this node: [object Text]
removeChild @ polymer-mini.html:767
_teardownInstance @ polymer.html:5090
detached @ polymer.html:5034
_invokeBehavior @ polymer-micro.html:434
_doBehavior @ polymer-micro.html:429
(anonymous function) @ polymer-micro.html:218
whenReady @ polymer-micro.html:101
detachedCallback @ polymer-micro.html:216
removeChild @ polymer-mini.html:566
removeChild @ polymer-mini.html:773
_clear @ polymer-mini.html:952set @ polymer-mini.html:1140
_constructRowCell @ exm-table-column.html:131

**Comment by TimvdLippe** [comment] 2017-08-15 00:15
Closing this issue as `Polymer.dom` is now on the legacy element and scheduled to be removed (this issue is one of the reasons it is being removed :smile: )

**Closed by TimvdLippe** 2017-08-15 00:15 UTC
Labels: 1.x, pending-response
