### ISSUE TITLE
Property bindings don't get activated for dynamically loaded element definitions

### ISSUE THREAD

**Issue by Tanbouz** [Polymer/polymer#2614] opened 2015-10-23 09:21 UTC
**Quick description**
I have a single page app where each page is an element itself. To avoid loading all pages and their media when visiting the landing page, pages are loaded dynamically. When a user navigates the app, page.js loads the "page element" by invoking the function `_importPage`. I'm not sure if this is the best way to go around making a single page app in Polymer but overall it seems working.

**Router code**
```
_importPage: function(page) {
  if (!document.querySelector('link[href="' + page + '"]')) {
    var link = document.createElement('link');
    link.setAttribute('rel', 'import');
    link.setAttribute('href', page);
    document.head.appendChild(link)
  }
}
```
```
var that = this;
page('/posts/:posturl', function(data) {
  page_loaded = that._importPage('pages/posts.html');
  that.route = 'posts';
  that.queryString = data.params['posturl'];
});
```

Sometimes I need to pass a query string to the page element

```
<page-posts name="posts" query-string="[[queryString]]"></page-posts>
```

**Page code**
However, in `<page-posts>` element. Nothing appears on the page, the `<span>` element is empty! `console.log` does print the value correctly.
```
  <template>
    <span>{{queryString}}</span>
  </template>
  <script>
  Polymer({
    is: 'page-posts',
    ready: function() {
      console.log(this.queryString);
    },
    properties: {
      queryString: {
        type: String,
      }
    },
  });
  </script>
```

**Workarounds**
It will work if the page is not loaded dynamically. For example, adding this to the head/or elements.html:
```
<link rel="import" href="../pages/posts.html">
```
Or if I add $
```
<page-posts name="posts" query-string$="[[queryString]]"></page-posts>
```

**Comment by ebidel** [comment] 2015-10-23 17:12
Confirmed. Seeing the same: http://jsbin.com/qofuyesuza/edit?html,output

This is a bit tricky. The definition of page-posts isn't registered by the time the binding to `queryParam` is setup, so the binding gets lost in Binding Limbo. It's curious though that the the attribute binding (`query-param$=`) works. It gets picked and propagated through to the property, even after the fact.

> Aside: I remember running into this exact issue (lazy load a component and have the bindings not work) for Google :santa: Tracker. We ended up using attribute bindings in a couple of places or later setting the property in JS.

@sorvell @kevinpschaaf is there a right way to approach this? Any helper methods we can create to make make data binding WorkAsExpected :tm: for delay-load cases?

BTW @Tanbouz, check out `Polymer.Base.importHref`. It's a helper that does what your `_importPage` is doing :).

**Comment by kevinpschaaf** [comment] 2015-10-23 20:27
Any sort of late-binding templates to a host is not supported by the simplified binding machinery Polymer has in place now, so unfortunately it's not as simple as adding helper methods.

The "Carbon elements" project will be addressing the need for more sophisticated lazy-loading.

What I would recommend in the meantime is to create top-level page elements within `<template is="dom-if">`'s whose definitions are lazy-loaded via `Polymer.Base.importHref`, and stamp the `dom-if` template once the definition is loaded.  Let me know if that's enough guidance to get you going.

**Comment by Tanbouz** [comment] 2015-10-24 13:40
Yes! Sounds good for my simple app. Looking forward for the carbon elements.
Thank you :+1:

**Comment by ebidel** [comment] 2016-01-31 22:19
Dupe of https://github.com/Polymer/polymer/issues/2653

**Closed by ebidel** 2016-01-31 22:19 UTC
Labels: databinding, elements, enhancement, p2
