### ISSUE TITLE
Dependency webcomponentsjs not resolving in bower

### ISSUE THREAD

**Issue by stevenpeh** [Polymer/polymer#3648] opened 2016-05-09 03:40 UTC
### Description

Running "bower install Polymer/polymer" as per documentation in a new project seeded with "bower init" causes the following error:

`bower polymer#*                 cached https://github.com/Polymer/polymer.git#1.4.0`
`bower polymer#*               validate 1.4.0 against https://github.com/Polymer/polymer.git#*`
`bower webcomponentsjs#^0.7.20        ENOTFOUND Package webcomponentsjs not found`
#### Live Demo

https://jsbin.com/xukike/edit?html,output
#### Steps to Reproduce
1. Create a new empty project
2. run `bower init` to seed it with a bower config
3. run `bower install Polymer/polymer` as per documentaion

Error goes away if manually install webcomponents prior, i.e. 

`bower install webcomponents/webcomponentsjs --save`

The bower.json file in Polymer seems to use the wrong label for webcomponentsjs, i.e.:
`"webcomponentsjs": "^0.7.20"`

whereas when manually install webcomponents with the `--save` flag, the bower.json file refers to it as:

`"webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.22"`
#### Expected Results

Install completes
#### Actual Results

Error: 

`bower webcomponentsjs#^0.7.20        ENOTFOUND Package webcomponentsjs not found`
### Browsers Affected

N/A
### Versions

Bower version 1.7.9
Latest Polymer (1.4.0).  Same when tried it with 1.3.0

**Comment by mbana** [comment] 2016-05-14 18:03
Although not entirely related, I've been wondering why the Polymer libs are not hosted on a CDN like most other JS libs. If there's no limitation, can I kindly ask that the team post up the libs on a CDN. It really just saves people have to do a bower install to see a working example of anything.

**Comment by arthurevans** [comment] 2016-05-14 19:30
@stevenpeh I can't reproduce this issue. I tried several variations with Bower 1.7.7 then upgraded to Bower 1.7.9 with the same results. You might try running `bower cache clean` and then re-running the install, since it appears that you're getting cached results.

You're right the label looks wrong, but it actually works because webcomponentsjs used to be in the Polymer github organization. So if you go to https://github.com/Polymer/webcomponentsjs you'll be seamlessly redirected to webcomponents/webcomponentsjs.

@azakus in the interest of being more explicit, should we update Polymer's bower dependency to point to `webcomponents/webcomponentsjs`? Just askin'.

@mbana There are actually some pretty good reasons why a CDN doesn't work well, at least for production code. HTTP Imports requires a flat dependency tree, so all of your components need to end up as peers, which is how bower installs them:

```
bower_components/
  polymer/
  paper-button/
  google-map/
```

paper-button and google-map import polymer using a _relative URL_: `../polymer/polymer.html`.

Most CDNs, though, would divide those by github organization:

```
Polymer/polymer/polymer.html
PolymerElements/paper-button/paper-button.html
GoogleWebComponents/google-map/google-map.html
```

And right there the relative URLs are broken. A little more info is here:

https://www.polymer-project.org/1.0/docs/start/reusableelements.html#structure

The Polymer Project has set up a development CDN, polygit, which you can use for all of your testing and prototyping needs:

https://www.polymer-project.org/1.0/tools/overview.html#polygit

This model doesn't work great for production because at present to get good performance out of the majority of browsers, you're going to need to vulcanize you dependencies. Since every app is going to need to use different dependencies, you'd either end up importing them all piecemeal (which would be slow) or importing gigantic vulcanized bundles of every possible element (which would be _really_ slow).

There are a lot of positive things going on in the web landscape right now, like HTTP2 and HTTP2 Push and discussions around HTML modules, that might make this much simpler in the long run. But right now, you need vulcanize for production for at least some portion of your traffic, and that means installing dependencies locally. Hope that helps.

**Comment by mbana** [comment] 2016-05-15 08:55
@arthurevans, I am not sure I follow. Could you please correct any misunderstanding:

* Why can't Vulcan infer that they are peers?
* Don't browsers cache files are they've initially been loaded, meaning, there is a one-time hit unless the cache is cleared etc.
* If all else fails, if CDNs made them peers would it then resolve the issue?

Many thanks for your detailed reply.

**Comment by TimvdLippe** [comment] 2017-08-15 23:31
Closing per @arthurevans 's comment. Feel free to open a question on [StackOverflow](https://stackoverflow.com/questions/tagged/polymer) if you are still encountering issues.

**Closed by TimvdLippe** 2017-08-15 23:31 UTC
Labels: 1.x, needs investigation, p1
