### ISSUE TITLE
Templatizer : missing dataHost._parentProps

### ISSUE THREAD

**Issue by darkengines** [Polymer/polymer#3899] opened 2016-09-03 16:40 UTC
### Description

Error thrown when changing value of a templatized child element, the child element is bound to a sub property of the model..
#### Live Demo

https://jsbin.com/vubaxekuro/edit?html,console,output
#### Steps to Reproduce

Just change the paper-input value.
#### Expected Results

The model should be updated wihtout exception.
#### Actual Results

The model is updated but an exception has been thrown.
### Browsers Affected
- [X] Chrome
- [x] Firefox
- [X] Edge
- [X] Safari 9
- [X] Safari 8
- [X] IE 11
### Versions
- Polymer: master
- webcomponents: master
### Exception

```
error TypeError: Cannot use 'in' operator to search for 'object' in undefined
    at TemplateInstance._notifyPathUpImpl [as _notifyPathUp] (https://polygit.org/polymer+:master/components/polymer/src/lib/template/templatizer.html:331:16)
    at TemplateInstance._notifyPath (https://polygit.org/polymer+:master/components/polymer/src/standard/notify-path.html:110:18)
    at TemplateInstance.set (https://polygit.org/polymer+:master/components/polymer/src/standard/notify-path.html:209:18)
    at TemplateInstance.<anonymous> (https://polygit.org/polymer+:master/components/polymer/src/lib/bind/accessors.html:236:20)
    at TemplateInstance._notifyListener (https://polygit.org/polymer+:master/components/polymer/src/standard/configure.html:220:21)
    at paper-input.<anonymous> (https://polygit.org/polymer+:master/components/polymer/src/lib/bind/accessors.html:269:24)
    at paper-input.fire (https://polygit.org/polymer+:master/components/polymer/src/standard/utils.html:231:12)
    at paper-input._notifyChange (https://polygit.org/polymer+:master/components/polymer/src/lib/bind/accessors.html:25:14)
    at paper-input._notifyEffect (https://polygit.org/polymer+:master/components/polymer/src/lib/bind/effects.html:39:14)
    at paper-input._effectEffects (https://polygit.org/polymer+:master/components/polymer/src/lib/bind/accessors.html:83:17)
```

**Comment by darkengines** [comment] 2016-09-08 16:53
Hotfix (**may induce side effects**) :
https://github.com/darkengines/polymer/commit/f8e3bac50ce9b9b22d22ba62ed93c02423f269ed

**Comment by TimvdLippe** [comment] 2017-08-17 00:15
This seems to be a side-effect of `Polymer.dom`, which has been deprecated and is on the legacy mixin. Therefore I am closing this issue. If you can reproduce this issue without `Polymer.dom`, please reopen this issue.

**Closed by TimvdLippe** 2017-08-17 00:15 UTC
Labels: 1.x
