### ISSUE TITLE
Updating dom-bind customStyle does not work

### ISSUE THREAD

**Issue by birkir** [Polymer/polymer#1953] opened 2015-06-24 16:08 UTC
Consider fresh Polymer starter kit project.

```
app.customStyle['--paper-toolbar-background'] = 'red';
app.updateStyles();
````

But if the app is setup as polymer element, it works.

Works: http://plnkr.co/edit/hIPUqR654bpMBWmpkBUV?p=preview
Does not work: http://plnkr.co/edit/DWa0FCl9Oqe9wwHiBau2?p=preview

**Comment by sorvell** [comment] 2015-06-24 17:40
This behavior is by design but needs explanation. `updateStyle` updates custom property styling in an element and its local DOM (Shady or Shadow DOM). Polymer template based elements like `dom-bind` produce dom but do not create local dom. Instead they emit dom into the scope in which they exist. In this case, that's the document. It's that scope on which `updateStyles` should be called. For the document scope, this is `Polymer.updateStyles`. 

There also hasn't been a way to add `customStyle` to the document scope until a recent commit to master that will be included in the next release, which should be available shortly. After the next release, you will be able to do the following:

```
app.changeTheme = function () {
  Polymer.StyleDefaults.customStyle['--paper-toolbar-background'] = 'red';
  Polymer.updateStyles();
 };
```

**Closed by sorvell** 2015-06-24 17:40 UTC
