### ISSUE TITLE
No element is getting located when it's inside the shadow root in selenium.

### ISSUE THREAD

**Issue by ajay1324** [Polymer/polymer#5581] opened 2019-08-08 10:06 UTC
#### Live Demo

https://jsbin.com/luhaxab/edit

https://glitch.com/edit/#!/polymer-repro?path=my-element.html:2:0

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by TimvdLippe** [comment] 2019-09-15 18:10
Closing as duplicate of https://github.com/SeleniumHQ/selenium/issues/5869

**Closed by TimvdLippe** 2019-09-15 18:10 UTC
