### ISSUE TITLE
Scroll, user has to tap twice to fire tap event.

### ISSUE THREAD

**Issue by hourliert** [Polymer/polymer#2065] opened 2015-07-10 19:05 UTC
Hi,

I am developing a web app using polymer. Everything works great on desktop and almost everything works great and mobile expect one view. This view is accessible [here](https://alpha.wid.la/#!/projects).

On this specific view, the user could scroll the page and tap on a card to display a modal view. The problem is (**on mobile**):
* if user doesn't scroll and directly taps on a card. It works perfectly.
* if user scrolls and taps on a card, nothing happen but if the user taps on the same card again, it works.

I can reproduce this bug on my OnePlus One, Nexus 9 and ios simulator.

I have tried to debug it but before I explain to you what "I found", here is  a similar view structure that I use:

```html
<paper-drawer-panel> <!-- this element listen on **track** event to be able to swipe the drawer -->

  <div drawer>...</div>
  <paper-scroll-header-panel main>

   <card-list>
     <template is="dom-repeat" items="[[cards]]">
       <card model="[[item]]"></card> <!-- this element listen on **tap** event and fire a new event -->
     </template>
   </card-list>

  </paper-scroll-header-panel main>

</paper-drawer-panel>
```

So after debugging, I observed:
* when the user directly taps on a card, [info.prevent](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L527) is `false` and everything works great, the `tap` event is fired.
* when the user scrolls, first the `<card/>` `tap` event should occurred. But as [`dy`](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L525) is too high, the event is not fired. The gesture is also [reset](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L535). Second the  `<paper-drawer-panel/>` `track` event should occurred and it does. So [this](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L451) line is executed. This will prevent the next tap event. I guess all of this is normal. But then. the user will really tap on the card and now [info.prevent](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L527) is `true` because of the previous `Gestures.prevent('tap');`. The `tap` event is not fired but the [tap gesture is reset](https://github.com/Polymer/polymer/blob/815bb975dadbb494c19c875216e09fe70c643ecb/src/standard/gestures.html#L535). The user has to tap again on the card to finally fire the `tap` event.

If I remove this [line](https://github.com/PolymerElements/paper-drawer-panel/blob/0339161b5ee1c46f587b92beab70fec13d507378/paper-drawer-panel.html#L342). Everything works perfectly (obviously except the gesture to open the drawer).

I hope I was clear enough. Does someone have an idea ?
Thanks in advance,

Thomas

**Comment by rubenstolk** [comment] 2015-07-13 15:33
Thank you so much, I've got the same issue!

**Comment by kevinpschaaf** [comment] 2015-07-13 16:47
Thanks for the issue.  This issue tracker is for the core Polymer library, not for issues with elements created with it.  We'll move this to an appropriate issue tracker.

**Comment by hourliert** [comment] 2015-07-13 17:26
Thanks for your answer. Indeed I use 2 paper-elements but this issue seems also related to the [gesture](https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html) implementation. Where do you think this issue should be reported?

**Comment by rubenstolk** [comment] 2015-07-14 04:13
I also feel this is more of a core related issue than a specific element issue.

**Comment by myfreeweb** [comment] 2015-07-16 16:18
+1

"Everything works perfectly" – well not *everything*, seems like the gesture to open the drawer doesn't work without the `track` event.

**Comment by tjsavage** [comment] 2015-07-16 16:22
@azakus Do you think this is a gestures issue or specific to an element?

**Comment by azakus** [comment] 2015-07-17 18:07
This seems like a general gestures issue. Looks like a regression from #1590

**Comment by myfreeweb** [comment] 2015-07-17 18:21
Looks like the correct fix this time is `this.info.prevent = false`

**Comment by m4b** [comment] 2015-07-19 00:04
The issue is definitely in the `track` event code being handled incorrectly, similar issues coming up in [`<paper-drawer-panel>`](https://github.com/PolymerElements/paper-drawer-panel/issues/80)

**Comment by myfreeweb** [comment] 2015-07-19 09:21
@m4b this isn't "similar" – this is the *exact same issue*! The example here features `paper-drawer-panel` too.

The fix is [just like this one](https://github.com/Polymer/polymer/commit/9b0bdf524cc4db991ed85c0451d48114c1e31bc0) but  `POINTERSTATE.tapPrevented` is now called `this.info.prevent`.

**Comment by rubenstolk** [comment] 2015-07-19 09:41
So anybody preparing a PR here?

**Comment by m4b** [comment] 2015-07-19 17:48
@myfreeweb I saw that you won't sign the CLA so I mirrored your commit.  Not sure how legal that is, heh, so we'll have to see.  Also, I assume you're ok with that?  

Anyway testing on firefox seems to resolve the issue, similarly with android, nice find!

**Comment by myfreeweb** [comment] 2015-07-19 17:59
Of course. This fix is SO small I didn't even make a PR before @rubenstolk asked.

**Comment by m4b** [comment] 2015-07-19 18:05
Cool.  A small fix, but a huge impact :+1: :)  Mobile was essentially unusable imho before this fix; as I mentioned in the issue I raised, when scrolling through lists of items, it would cause next touch loss, but from the users perspective it just seemed like the app was broken and crappy.

I might finally be able to unleash my app on the world now ;)

**Comment by hourliert** [comment] 2015-07-19 18:22
Thanks for the fix. Waiting on the next polymer release and ready to publish my app too.
Thanks again.

**Comment by rubenstolk** [comment] 2015-07-20 04:15
For the ones who are really keen on launching their app before this PR gets merged and don't want to change the polymer code themselves:

```
  // Patch for https://github.com/Polymer/polymer/issues/2065
  window.addEventListener('WebComponentsReadyx', function () {
    var recognizer = window.Polymer.Gestures.recognizers.filter(function (r) {
      return r.name === 'tap';
    })[0];
    recognizer.mousedown = function (e) {
      this.info.prevent = false;
      this.save(e);
    };
    recognizer.touchstart = function (e) {
      this.info.prevent = false;
      this.save(e.changedTouches[0]);
    };
  });
```

**Comment by m4b** [comment] 2015-07-20 04:38
@rubenstolk: nice! As soon as iron-list/issues/21 is done (don't want to reference), which I'm thinking will be this week, things are looking quite nice!

**Comment by rubenstolk** [comment] 2015-07-20 04:51
Definitely, thanks so much @m4b @myfreeweb, and just in time before I have to release my app...

**Comment by m4b** [comment] 2015-07-20 04:53
Thank @myfreeweb I didn't do anything :stuck_out_tongue:

**Closed** 2015-07-21 18:14 UTC
Labels: p1
