### ISSUE TITLE
Misleading errors when using the same function as listener of two different attributes in 1.0

### ISSUE THREAD

**Issue by josator** [Polymer/polymer#1817] opened 2015-06-10 09:34 UTC
When using the same function as observer of two different attributes in the "properties" (by mistake),  a change with "undefined" as new value is triggered in all the attributes, this skips even the "value:" default value specified in "properties".

This uncontrolled "undefined" update in the observed attribute can cause the new value to be updated to "Nan" inside the observer function, leading to an infinite loop of observer calls. Right now "Nan == Nan" seems to evaluate to "true".

This should be studied to notify in the console when an user has made this mistake and telling him to use the "observers" array instead.

**Comment by kevinpschaaf** [comment] 2015-06-15 22:50
Not sure we understood your exact setup where you'd like a warning; can you modify the following example (which has expected behavior):
http://jsbin.com/befeka/edit?html,console,output

If your point is that having the same function as two observers is likely an error, we are building a linter and this could be one thing it flags (we won't warn in the core library because this could be a valid and intended setup).

As for the `NaN !== NaN`, this was solved in #1811 and will be released shortly.

**Comment by josator** [comment] 2015-06-15 23:58
I do not know if is similar to my problem, but I set the properties in the ready method or by default. In my case I need to set an observer on these attributes, but i do not need to set the attributes from outside the element. Maybe it is not correct, but many things I was able to do on 1.0 do not work now.

http://jsbin.com/qewozuyedo/edit?html,console,output

**Closed** 2015-06-16 12:30 UTC
Labels: linter-tool, pending-response
