### ISSUE TITLE
Can't use openlayers draw control in Polymer script.

### ISSUE THREAD

**Issue by purpleP** [Polymer/polymer#1109] opened 2015-01-20 08:36 UTC
Full info can be found here.

http://stackoverflow.com/questions/28039895/drawing-doesnt-work-in-openlayers3-with-polymer

<link rel="import" href="/static/bower_components/polymer/polymer.html">
<script src="/static/bower_components/openlayers3/build/ol.js" type="text/javascript"></script>
<polymer-element name="my-map">

    <template>

<link rel="stylesheet" href="/static/bower_components/openlayers3/css/ol.css" type="text/css">
        <style>

            .map {
                height: 100%;
                width: 100%;
            }
        </style>

        <h2>My Map</h2>
        <div id="map" class="map"></div>
    </template>

    <script>
        Polymer({

            domReady: function() {

                this.map = new ol.Map({
                    target: this.$.map,
                    layers: [
                      new ol.layer.Tile({
                        source: new ol.source.MapQuest({layer: 'sat'})
                      })
                    ],
                    view: new ol.View({
                      center: ol.proj.transform([37.41, 8.82], 'EPSG:4326', 'EPSG:3857'),
                      zoom: 4
                    })
                    });

                var featureOverlay = new ol.FeatureOverlay({
                  style: new ol.style.Style({
                    fill: new ol.style.Fill({
                      color: 'rgba(255, 255, 255, 0.2)'
                    }),
                    stroke: new ol.style.Stroke({
                      color: '#ffcc33',
                      width: 2
                    }),
                    image: new ol.style.Circle({
                      radius: 7,
                      fill: new ol.style.Fill({
                        color: '#ffcc33'
                      })
                    })
                  })
                });
                featureOverlay.setMap(this.map);

                var modify = new ol.interaction.Modify({
                  features: featureOverlay.getFeatures(),
                  // the SHIFT key must be pressed to delete vertices, so
                  // that new vertices can be drawn at the same position
                  // of existing vertices
                  deleteCondition: function(event) {
                    return ol.events.condition.shiftKeyOnly(event) &&
                        ol.events.condition.singleClick(event);
                  }
                });
                this.map.addInteraction(modify);

                var draw = new ol.interaction.Draw({
                    features: featureOverlay.getFeatures(),
                    type: "LineString"
                });
                this.map.addInteraction(draw);

            }

        })
    </script>

</polymer-element>

**Comment by fredj** [comment] 2015-03-04 17:04
It's an openlayers bug, this issue can be closed.

**Comment by fredj** [comment] 2015-03-19 06:48
Fixed with https://github.com/openlayers/ol3/pull/3322

**Comment by tjsavage** [comment] 2015-10-23 23:28
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:28 UTC
Labels: 0.5

**Comment by fredj** [comment] 2015-10-26 07:56
@tjsavage that's fine, the issue is fixed in openlayers
