### ISSUE TITLE
notifyPath's value doesn't do anything 

### ISSUE THREAD

**Issue by bedeoverend** [Polymer/polymer#3179] opened 2015-12-09 07:40 UTC
It seems that calling `notifyPath` will update any observer with the value that exists in the path, not the value given to `notifyPath`. If this is the intended behavior, is there another purpose of the value argument in `notifyPath`?

See [example codepen](http://codepen.io/bedeoverend/pen/ZQYdwQ?editors=101)

**Comment by kaste** [comment] 2016-01-16 23:24
Duplicate of #2606.

**Comment by kaste** [comment] 2016-02-25 12:25
Let's keep it real here. Nobody wants to supply the value argument anyway. API wise it's either 

```
  this.set('foo.bar', 'quux');
```
or
```
  this.foo.bar = 'quux';
  this.notifyPath('foo.bar'); 
```
With the latter having the notion of: I hereby notify you, Polymer, the library, that **I** changed this path. Do whatever is appropriate.

**Comment by kaste** [comment] 2016-02-25 13:04
Actually if #3439 lands, the value you send should get through to your observers. But I don't think this is the intended usage of this method. It is not covered by tests anyway.

**Closed** 2016-03-28 19:54 UTC
Labels: databinding, needs documentation, question
