### ISSUE TITLE
Weird Polymer Catalog Bug (Md) -- "paper-toast"

### ISSUE THREAD

**Issue by bakirov** [Polymer/polymer#1678] opened 2015-05-30 11:16 UTC
Dear Sirs,

It seems I found a bug in Polymer Catalog. To reproduce, please follow these steps:

1. Open polymer catalog: https://elements.polymer-project.org/
2. Choose Md (Paper Elements)
3. From paper elements select paper-button; switch to demo in left pane
4. Select "paper-toast" from "other elements"
5. Now, select any other element, e.g. "paper-menu" -- "paper-toast" disappears from elements catalog.

More weird behavior:

1. Repeat steps 1-4 above
2. Now, select "paper-toggle-button"
3. Now, again select "paper-toast" -- "paper-toggle-button" disappears!
4. You can toggle between "paper-toast" and "paper-toggle-button" by clicking "paper-toast" element.

Best regards!

**Comment by francisbrito** [comment] 2015-05-30 15:44
I think this is a feature. It actually makes sense to remove an element from the **other elements list** upon being selected.

**Comment by bakirov** [comment] 2015-05-30 16:14
@francisbrito, did you try to reproduce this? This bug is not about selected element removed from other elements list.

**Comment by francisbrito** [comment] 2015-05-30 16:31
@bakirov, I see. I misread your report. Following the steps described above works as expected for me: selected element is hidden from the "other elements" list, unselected elements are shown. 

Could this be a browser related issue? I tested on Chrome 43 for Linux.

**Comment by bakirov** [comment] 2015-05-30 16:44
Uploading a screenshot of a behavior.
I use a Chrome version 43.0.2357.81 m on Windows 7 (64-bit).

![paper menu polymer element catalog](https://cloud.githubusercontent.com/assets/1590466/7898286/29975548-071d-11e5-964e-65ff8367c34a.png)

**Comment by bakirov** [comment] 2015-05-30 19:43
Hmm, in Chrome Incognito and in Firefox everything is OK.

**Comment by kevinpschaaf** [comment] 2015-06-02 22:36
@bakirov We were unable to reproduce the double `paper-tabs` in your last screenshot.

As far as we can tell, your earlier description of the currently selected item being removed from the "other elements" when selected list is by design, as @francisbrito suggested.

Can you try and provide any additional information that might help us reproduce the double `paper-tabs` issue?

**Comment by tjsavage** [comment] 2015-06-03 01:05
auto-moving this issue to Polymer/polymer-element-catalog#101 and closing this one

**Closed by tjsavage** 2015-06-03 01:05 UTC
Labels: needs move, pending-response
