### ISSUE TITLE
Suggest installing iron-input in Quick tour of Polymer

### ISSUE THREAD

**Issue by MattMS** [Polymer/polymer#3566] opened 2016-04-06 23:21 UTC
When reaching the [Bind to a property](https://www.polymer-project.org/1.0/docs/start/quick-tour.html#bind-to-a-property) section of the [Quick tour of Polymer](https://www.polymer-project.org/1.0/docs/start/quick-tour.html), I could not get the example code to work because I had not installed the [iron-input](https://elements.polymer-project.org/elements/iron-input).

I reached this after following the [Installing with Bower](https://www.polymer-project.org/1.0/docs/start/getting-the-code.html#using-bower) instructions.

Would it be worthwhile to remind the user to do `bower install --save PolymerElements/iron-input` at this point?

**Comment by TimvdLippe** [comment] 2016-04-12 19:14
Duplicate of https://github.com/Polymer/docs/issues/1559 (CC: @arthurevans )

**Comment by flancer64** [comment] 2016-04-13 04:22
Thanks, @MattMS! This is the command I am looking for.

**Closed** 2016-04-13 16:27 UTC
