### ISSUE TITLE
Use web standards for imports in polymer library

### ISSUE THREAD

**Issue by jarrodek** [Polymer/polymer#5514] opened 2019-03-27 19:51 UTC
### Description

Most of project's files uses web standard when importing dependencies (e.g. `import { dedupingMixin } from '../utils/mixin.js';`. However `lib/elements/custom-style.js` and `lib/legacy/legacy-element-mixin.js` uses Polymer's import syntax for files located in `@webcomponents` library.
This makes it difficult to use the library without using polyserve. When developing apps that are not running in the web (Electron, Chrome app) it is required to take additional steps in order to make it run in dev environment (compilation on source file change, some other measures).

I would like to see the `@webcomponents` imports to comply with web standards so the library can be used directly in the web browser without using Polymer tooling.

**Comment by kevinpschaaf** [comment] 2019-03-27 22:04
Closing as duplicate of https://github.com/Polymer/polymer/issues/5238#issuecomment-390012108 and https://github.com/Polymer/polymer/issues/5431#issuecomment-437599257.  Please see those threads/comments and a [blog post on the topic](https://www.polymer-project.org/blog/2018-02-26-3.0-preview-paths-and-names) for more details on the reasoning that went into the decision-making for package names being the only non-standard convention used in published Polymer Project source.

Also, [Chrome intent to implement import maps](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/qYeQFqgFOyA/rXJapjMaEAAJ) and [@pika/web](https://github.com/pikapkg/web) are two exciting new areas worth following in this space.

**Closed by kevinpschaaf** 2019-03-27 22:04 UTC

**Comment by jarrodek** [comment] 2019-03-28 01:46
Thanks for the links. I was asking on Polymer Slack channel some time ago about reasoning behind this decision but didn't get the answer. Reading this comments I think everything has been said already about that. My humble opinion is that the platform should be first, not tooling. Although, I do understand the reasons behind that decision now.
