### ISSUE TITLE
Passing through CSS variables fails since Polymer 1.3.0

### ISSUE THREAD

**Issue by ronnyroeller** [Polymer/polymer#3462] opened 2016-02-24 10:18 UTC
### Description
CSS styles are ignored if they contain a CSS variable that depends on another CSS variable, e.g.:
```
--paper-fab-background: var(--my-paper-fab-background);
```

This is handy if the user of an element should be able to style embedded elements (e.g. a paper-fab that is contained in the element).

The following two usages of CSS variables work both:
```
background: var(--my-paper-fab-background);
--paper-fab-background: red;
```

This issue was introduced between Polymer v1.2.4 (works) and v1.3.0 (doesn't work).

#### Live Demo
https://jsbin.com/pilota/edit?html,output

[Comment out the `--paper-fab-background: var(--my-paper-fab-background);` to see how the style gets applied without the CSS variable.]

For a full demo see this component: https://github.com/Collaborne/paper-fab-speed-dial/blob/master/paper-fab-speed-dial.html#L39

#### Steps to Reproduce
1. Create `my-element`
2. Append `my-element` to document.body
3. Create `div`.
4. Append `div` to `my-element`
5. Add `class` attribute to `div`
6. Add to referenced style a CSS variable which depends on a CSS variable

#### Expected Results
Style is applied

#### Actual Results
Style is ignored

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [not tested] Safari 9
- [not tested] Safari 8
- [not tested] IE 11

### Versions
- Polymer: v1.3.0
- webcomponents: v0.7.21 

Downgrading Polymer to v1.2.4 solves the problem.

**Comment by sorvell** [comment] 2016-02-24 19:08
Thanks for report! Confirmed and closing this as a dupe of #3461

**Closed by sorvell** 2016-02-24 19:08 UTC
