### ISSUE TITLE
polymer 2 doesn't remove $ from non-bound attributes

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#5278] opened 2018-06-29 23:54 UTC
I am in the process of upgrading from Polymer 1 to 2, and have noticed that some of my code has hard-wired attributes on polymer elements but still use `$=`, eg : 
```
<my-element data-value$="some value"></my-element>
```

This is likely because I also use it in places where the value is bound, and so the `$=` is necessary.

In Polymer 1, it seems like Polymer would remove the `$` so it would work as a normal attribute; but in Polymer 2, it seems like the `$` is not removed and so becomes part of that attribute's name, which messes with the key in the element's dataset object - ie `dataset['value$']` is `some value`.

I don't see this mentioned anywhere in the upgrade docs. Is this expected/intentional?

**Comment by TimvdLippe** [comment] 2018-06-30 08:52
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!

**Comment by jsilvermist** [comment] 2018-06-30 09:16
This issue seemed pretty straightforward to me...

It doesn't really require a live demo to ask if this was an intended change or not, because that pretty much assumes it wasn't intended.

To clarify, he's saying that an attribute with a binding such as
```html
abc$="[[def]]"
```
Will set `abc`, where
```html
abc$="def"
```
Will set the attribute `abc$`.

**Comment by TimvdLippe** [comment] 2018-06-30 09:29
@jsilvermist Thanks for the clarification. This was initially unclear to me. In general, we enforce the CONTRIBUTING guidelines to make sure we can work effectively as possible. Since this issue had the template deleted, we lose a lot of valuable information.

For now, with the clarification, the issue is clear, so I will reopen. However, for future issues we do require the template to be filled in, such that we can effectively help our users.

**Comment by jsilvermist** [comment] 2018-06-30 17:31
@TimvdLippe Glad to help, also, sorry if my original comment was a bit rude, that wasn't intended.

**Comment by davidmaxwaterman** [comment] 2018-07-01 02:12
Sorry I wasn't clear in my original post. I suppose I could have tried to make a test case, as I have many times before in my GitHub issues for polymer, but it seemed simple enough to just describe (my mistake there) and would really need two test cases to properly demonstrate the difference...

**Comment by davidmaxwaterman** [comment] 2018-07-01 02:17
Actually, @jsilvermist, it isn't just that, but also that polymer 1 would set `abc` for `abc$="def"`, ie remove the `$`. If both polymer 1 and 2 were the same (or it was a documented difference), then I would have no problem.

**Comment by kevinpschaaf** [comment] 2018-07-23 19:37
@davidmaxwaterman I don't believe your claim is correct that Polymer 1.x would set an attribute suffixed with `$` to a static value when there was no binding.

Per the code in 1.x, the `$` is only stripped from the attribute name if and only if the value contained bindings: https://github.com/Polymer/polymer/blob/a8e6530bb607507192b228311dc1bd3326a101fa/src/lib/annotations/annotations.html#L351-L359

These two glitches show the same behavior for 1.x and 2.x:
* 1.x: https://glitch.com/edit/#!/adventurous-playroom?path=public/my-element.html:12:0
* 2.x: https://glitch.com/edit/#!/azure-flag?path=public/my-element.html:12:0

I'm going to go ahead and close this issue.  Please open a new one with a repro if you find the behavior to be inconsistent.

**Closed by kevinpschaaf** 2018-07-23 19:37 UTC
