### ISSUE TITLE
polygit server is down

### ISSUE THREAD

**Issue by tstewart15** [Polymer/polymer#3884] opened 2016-08-24 21:17 UTC
polygit.org is down.

Duplicate Issues:
https://github.com/PolymerLabs/polygit/issues/7
https://github.com/PolymerLabs/polygit2/issues/13

**Comment by garlicnation** [comment] 2016-08-24 21:32
Duplicate of https://github.com/PolymerLabs/polygit2/issues/13
Other issue closed.

**Closed by garlicnation** 2016-08-24 21:32 UTC
