### ISSUE TITLE
PropertyEffects should not stomp on existing accessor

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3937] opened 2016-09-10 00:10 UTC
_From @sorvell on September 7, 2016 15:53_

Currently PropertyEffects creates an accessor if there is not already `this.__propertyEffects[property]`. This can stomp on a user accessor which seems non-ideal. It would be nice if users could implement their own accessors and call `_get/_setProperty` to tie into the accessors/effects system.

It's not as easy as checking `hasOwnProperty` to avoid creating the accessor because we rely on saving existing function references this way. Instead, we would likely have to inspect `getOwnPropertyDescriptor` and see if there's an existing getter/setter. The perf of this is something to investigate.

_Copied from original issue: PolymerLabs/alacarte#112_

**Comment by justinfagnani** [comment] 2016-09-17 20:28
@kevinpschaaf and I were talking about this yesterday day, and there are a few possible variants to investigate here.

  1. A per-property check that there isn't already an accessor
  2. A per-element flag on whether to create accessors. This could be useful for elements that optimize by generating the accessors at build time, and distribute that way.
  3. A global flag that turns off creating accessors, useful for apps that have optimized by generating accessors.

An important sub-task is to document and enable user-written accessors that are full-fidelity substitutes for meta-programmed accessors. @kevinpschaaf I'm not sure what the setter should look like, since we don't have a closure with effects:

```javascript
class A extends Polymer.Element {
  get foo() { return this.__data__.foo; }
  set foo(value) { this._propertySetter('foo', value, effects); } // not quite right
}
```

**Comment by kevinpschaaf** [comment] 2016-09-23 00:48
In light of mixins and base classes, it seems there's not actually a great way to do this robustly, other than walking the entire prototype chain and checking for `Object.getOwnPropertyDescriptor(proto).get`, since there's not a cheap way to identify you're about to stomp on an accessor with another accessor.

@justinfagnani any clever ideas here?

**Comment by justinfagnani** [comment] 2016-09-23 03:52
Not sure how it currently works, but it seems like accessors should be defined on the prototype associated with the constructor function with the config block that declared the property. So there shouldn't be any additional prototype walking above finding the config blocks.

Something naively like this:

```javascript
function defineOwnAccessors(proto) {
  const config = proto.constructor.config;
  for (const property of Object.keys(config.properties)) {
    const propertyDef = config[property];
    if (!proto.hasOwnProperty(property)) {
      Object.defineProperty(proto, property, {
        get: /* ... */,
        set: /* ... */,
      });
    }
  }
}
```

This assumes you have some place already that walks up the class/proto hierarchy to define accessors, like:

```javascript
function defineAccessors(proto) {
  // walk up to Polymer.Element, or the first superclass that's already setup
  while (proto instanceof Polymer.Element && !hasAccessorsDefined(proto)) {
    defineOwnAccessors(proto);
    proto = Object.getPrototypeOf(proto);
  }
}
```

That's not more proto-chain walking that already done, is it?

**Comment by TimvdLippe** [comment] 2017-09-19 23:13
Closing this as duplicate of https://github.com/Polymer/polymer/issues/4595. PR is currently open at #4815

**Closed by TimvdLippe** 2017-09-19 23:13 UTC
Labels: 2.x, databinding, p2
