### ISSUE TITLE
Nested dom-repeat's with computed arrays trigger observers but do not otherwise update UI

### ISSUE THREAD

**Issue by unionthugface** [Polymer/polymer#5127] opened 2018-02-22 01:46 UTC
### Description
If there are nested `dom-repeat` elements using computed arrays, and a change is made to a subproperty of the parent object/array from which the outermost computed array is constructed, the change will traverse up and down all the observed/computed paths in the script as expected, but the UI of the innermost `dom-repeat`'s won't re-render, even with an explicit call to the `render` function of the individual `dom-repeat`'s involved.

#### Steps to Reproduce
Please see the code example [here](https://stackoverflow.com/questions/48893547/polymer-2-x-dom-repeat-does-not-observe-changes-to-computed-arrays-children/48893832?noredirect=1#comment84802464_48893832)

#### Expected Results
In the example code in the link, making a change to `parentArray.1.IsChecked` would trigger a re-computation of computed array `outerComputedArray`, and the change to the `sesh.IsChecked` property in the innermost `dom-repeat` would be reflected in the UI, checking the `paper-checkbox`.

#### Actual Results
In the example code in the link, making a change to `parentArray.1.IsChecked` triggers a re-computation of computed array `outerComputedArray` as expected; however the change to the `sesh.IsChecked` property in the innermost `dom-repeat` is not re-rendered, and the `paper-checkbox` remains unchecked.

### Browsers Affected

- [X ] Chrome
- [X ] Firefox
- [X ] Edge
- [ ?] Safari 9
- [ ?] Safari 8
- [? ] IE 11

### Versions

- Polymer: v2.x
- webcomponents: v1.1

**Comment by MajorBreakfast** [comment] 2018-02-22 13:55
Can you provide a working demo, e.g. using codepen? Here's a link to one of my old demos. It should be straightforward to adapt: https://codepen.io/MajorBreakfast/pen/XZMRJZ

I think your problem stems form the usage of a computed property. This can lead to property change notifications of subproperties not reaching the place where they're needed. Not a bug, just a limitation of a system which avoids dirty checking. It might be possible to make your use case work by using the `sort` and `filter` methods of `<dom-repeat>` (and thus avoid the computed property) or by using the MutableData mixin on all involved elements. But without a working demo that can be debugged and tinkered with it's hard to tell.

**Comment by TimvdLippe** [comment] 2018-03-09 21:25
Closing this issue per above comment. We can reopen when a jsbin is supplied.

**Closed by TimvdLippe** 2018-03-09 21:25 UTC
Labels: pending-response, question
