### ISSUE TITLE
Two-way data binding causes infinite loop with some elements

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#3399] opened 2016-02-10 02:07 UTC
http://jsbin.com/cewicocezo/1/edit?html,output

Changing the first `paper-input` causes an infinite loop ("Maximum stack size" error), but changing the first `paper-slider` is fine. Notice that when the two elements are reversed (i.e. `paper-input` before `paper-slider`), the error does not occur. This is a regression from v1.2.3.

From https://github.com/PolymerElements/paper-slider/issues/116

cc @kevinpschaaf @sorvell @frankiefu

**Comment by TimvdLippe** [comment] 2016-02-10 07:19
On my Android Chrome browser I am unable to reproduce this problem. What browser are you using?

**Comment by christophe-g** [comment] 2016-02-13 15:24
Chrome Version 45.0.2454.85 (64-bit) here - but I don't see how this issue can be browser-specific.

**Comment by kevinpschaaf** [comment] 2016-02-18 20:16
Root cause is twofold:
* The slider changes the `value` property in an observer synchronous to its setter, which causes a new notification to the host (an propagation to local children) before the original value reaches the input.
* Once the stack unwinds and the original change to `value` is set to the input, which notifies back to the host with the old value.

Proposed solution(s):
* Re-engineer elements to avoid synchronous validation and change of input properties to avoid contention for "source-of-truth" (e.g. elements can validate inputs internally, but must not change inputs for validation, only state change such as user action)
* Late-bind property value sent to effects in `_effectEffects`, so that they are always working on the _latest_ host value of the property, rather than the one passed in.

Note, the 2nd solution will only solve this particular case; there is a more general intractable problem with two elements validating their inputs and synchronously when they do not-agree (e.g. slider with min=0, max=5 and another one with min=10, max=20 -- this will always iloop if they are two-way bound), hence the first solution seems the correct path.

**Comment by keanulee** [comment] 2016-02-18 22:23
For reference, the offending change of input is in IronRangeBehavior (https://github.com/PolymerElements/iron-range-behavior/blob/master/iron-range-behavior.html#L102). @notwaldorf @cdata do you see any issue with removing the `_validateValue` method?

**Comment by notwaldorf** [comment] 2016-02-18 22:38
@blasten is the most familiar with that behaviour

**Comment by TimvdLippe** [comment] 2017-08-15 00:18
The issue seems to be fixed in Polymer 2: http://jsbin.com/mineratuze/edit?html,console,output I can modify all elements with no errors thrown.

**Closed by TimvdLippe** 2017-08-15 00:18 UTC
Labels: 1.x, databinding, needs investigation, p1
