### ISSUE TITLE
Inconsistent attribute deserialization (eg: string to object vs number to object).

### ISSUE THREAD

**Issue by jonagh** [Polymer/polymer#4464] opened 2017-03-27 16:00 UTC
Upgrading to Polymer 2.0 (2.0-preview) and I've noticed an apparent change with attribute deserialization. Specifically if a property of non-String type is assigned a string value via its corresponding attribute then it is NOT deserialized (successfully), however other values (eg numbers or booleans, etc) will deserialize perfectly fine even when the property's type does not match.

Eg:
```
properties: {
  myobj: { type: Object }
}
...
<my-thing myobj="hello"></my-thing> <!-- doesn't work -->
<my-thing myobj="234"></my-thing> <!-- works! -->
```
This issue seems to affect string values specifically. If a number, bool, etc is specified then it sets the property successfully but if it's just some text string then it fails.

JSBin: https://jsbin.com/paqazel/edit?html,output

**Expected results** would be either that string values deserialize for non-string types (as they seemed to do before 2.0) or that they don't deserialize but neither do other values that don't match the declared type.

**Actual results** are that string values behave special and the inconsistency makes me feel like something is wrong here, and it made me confused and spend a bunch of time trying to figure out what I was doing wrong when upgrading to 2.0.

Or maybe I've misunderstood something?
Thanks :)

Chrome 58
Polymer 2.0-preview

**Comment by azakus** [comment] 2017-03-27 19:12
That is handled by the PropertyAccessor mixin: https://github.com/Polymer/polymer/blob/master/lib/mixins/property-accessors.html#L283-L324

It does look like the intent may have been to allow Object types to allow Strings and Numbers, but Arrays to fail with `null`.

**Comment by kevinpschaaf** [comment] 2017-04-03 22:29
Confirmed unintended change, will fix.

**Comment by pkaske** [comment] 2017-11-27 19:50
Can I make a friendly ping about this @kevinpschaaf? Just want to know if this will be fixed in the nearer future or if I should override property serialization.

**Comment by pkaske** [comment] 2017-11-27 20:54
@kevinpschaaf I looked at the code and saw that the whole situation seems to be a quite easy to fix regression. So I created a pr.

**Closed** 2017-12-12 19:01 UTC
Labels: databinding, p1
