### ISSUE TITLE
Allow for explicit CSS mixin inheritience when re-defining a mixin

### ISSUE THREAD

**Issue by bendavis78** [Polymer/polymer#2487] opened 2015-09-26 23:12 UTC
Take the following use case:

We have a big theme file that defines some mixins for standard paper-\* elements:

``` css
:root {
  --paper-dropdown-menu-icon: {
    color: var(--some-theme-color);
  };
}
```

Now, let's say I have a custom element called `my-custom-form` that needs to make a padding tweak to dropdown icons, and defines the following in its stylesheet:

``` css
:host {
  --paper-dropdown-menu-icon: {
    padding-right: 12px;
  };
}
```

This, of course, will wipe out whatever CSS properties were defined in the global theme. The common workaround to this is for custom elements to something like this:

``` css
:host {
  --paper-dropdown-menu-icon: {
    padding-right: 12px;
    @apply(--my-custom-form-paper-dropdown-menu-icon);
  };
}
```

But then the theme author has to add the new mixin to the theme file, and things start getting ugly:

``` css
:root {
  --paper-dropdown-menu-icon: {
    color: var(--some-theme-color);
  };
  --my-custom-form-paper-dropdown-menu: {
    color: var(--some-theme-color);
  };
}
```

Ideally, an element developer would be able to decide explicitly whether a mixin should extend the currently defined mixin, or just override it. My proposal would look like this:

``` css
:host {
  --paper-dropdown-menu-icon: {
    @apply();
    padding-right: 12px;
  }
}
```

Calling `@apply()` without arguments would apply rules from the currently defined mixin (think `super()` in python).

**Comment by nazar-pc** [comment] 2015-09-28 16:37
I do not like this particular syntax, but :+1: for such feature, would be nice to have.
Probably, this way might be more explicit:
```css
:host {
  --paper-dropdown-menu-icon: {
    @apply(--paper-dropdown-menu-icon);
    padding-right: 12px;
  }
}
```

If think logically, `--paper-dropdown-menu-icon` when we use it exists as declaration for some element higher in DOM tree, so we can use it without issues (literally we just extend it for current part of DOM tree).

But I guess, for this feature to be implemented it should be suggested and added to standard proposal: https://tabatkins.github.io/specs/css-apply-rule/

**Comment by samccone** [comment] 2015-09-28 16:37
> But I guess, for this feature to be implemented it should be suggested and added to standard proposal: https://tabatkins.github.io/specs/css-apply-rule/

:+1: I agree

**Comment by bendavis78** [comment] 2015-11-18 09:40
@nazar-pc: I agree w/ your suggestion, explicit is probably better. Currently that syntax causes an infinte loop in Polymer. Are there any other reference implementations of the `@apply` spec? I wonder if that usage was considered.

**Comment by nazar-pc** [comment] 2015-11-18 13:32
I don't think it is implemented fully anywhere. Polymer also doesn't provide full polyfill, just good enough approximation. If spec will support this - I think Polymer will as well.

**Comment by nazar-pc** [comment] 2015-11-24 07:31
Confirmed to be implemented in spec

**Comment by sorvell** [comment] 2016-01-29 00:01
I think @nazar-pc suggestion here (https://github.com/Polymer/polymer/issues/2487#issuecomment-143798877) is a good one. I consider it a bug that the property shimmer does not support this right now. We'll take a look at improving this.

Note that an alternate possibility would be something like below. This would require additional spec'ing and is probably not any better:

`--paper-dropdown-menu-icon[padding-right]: padding-right: 12px;`

**Comment by TimvdLippe** [comment] 2018-02-06 18:51
We took another look at this issue. Since this is a specification issue, we are closing it as is. In the future, `::part` and `::theme` will be used instead of `@apply` which has a different model. We have a experimental polyfill available at https://github.com/PolymerLabs/part-theme which you can try out and see if that works as you expect.

**Closed by TimvdLippe** 2018-02-06 18:51 UTC
Labels: 1.x, css, p1
