### ISSUE TITLE
Classes are computed before dom-change

### ISSUE THREAD

**Issue by eximius313** [Polymer/polymer#3584] opened 2016-04-13 21:47 UTC
#### Live Demo

https://jsbin.com/taposiqole/1/edit?html,css,console,output
#### Steps to Reproduce
1. You have a div, which class must be computed
2. Computation depends on elements inside template, so you **must** create computation method inside `dom-change` event
3. Classes are computed before dom change runs, so computation does not occur
#### Expected Results

You can create computation method inside `dom-change`
#### Actual Results

![image](https://cloud.githubusercontent.com/assets/5578017/14510413/96e106b2-01d1-11e6-90d9-bcd923cbac2f.png)
### Browsers Affected
- [X] Chrome
- [X] Firefox
- [?] Edge
- [?] Safari 9
- [?] Safari 8
- [X] IE 11
### Versions
- Polymer: "1.4.0"
- webcomponents: version 0.7.21

**Comment by kaste** [comment] 2016-04-15 11:10
This is pretty much blocked by the nice warning you see. If we remove that warning, we could try to teach Polymer to very lazily evaluate that function. But then the user wouldn't see a warning on typos etc. 

I would have liked this for #3358 but not even asked b/c I thought they will never accept this change.

**Comment by TimvdLippe** [comment] 2018-01-18 14:44
Closing this as working as intended. If you want to update the value when the data-binding changes, you have to explicitly pass in this value: http://jsbin.com/momuruwihi/1/edit?html,css,console,output This means that any hidden dependency in an observer or computed function must be explicitly declared as argument of that function.

**Closed by TimvdLippe** 2018-01-18 14:44 UTC
Labels: 1.x, api-feedback
