### ISSUE TITLE
Feature Request: Event handling with Automatic node finding

### ISSUE THREAD

**Issue by lukeschaefer** [Polymer/polymer#4647] opened 2017-05-31 17:56 UTC
It would be extremely powerful to be able to use automatic node finding (`this.$["element-id"]`) in bindings. Taking away tons of boilerplate javascript code. For example:

```
<iron-ajax
  id='ajax'
  url='/handlers/GetSomething'
  on-load='$.dialog.open'>
</iron-ajax>

<paper-dialog id='dialog'>
  We did the thing!
</paper-dialog>

<paper-button
  on-tap='$.ajax.generateRequest'>
</paper-button>
```

The interaction between these elements is all defined without having to create obvious boilerplate such as:

```
onButtonTap: function(){
  this.$['get-something'].generateRequest()
},

onAjaxLoad: function(){
  this.$.dialog.open()
}
```

**Comment by TimvdLippe** [comment] 2017-05-31 18:01
This is a duplicate of #3259

**Comment by TimvdLippe** [comment] 2017-08-04 03:23
Closing as duplicate of #3259

**Closed by TimvdLippe** 2017-08-04 03:23 UTC
Labels: 2.x, enhancement, p2
