### ISSUE TITLE
Inheritance of CSS Variables

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1470] opened 2015-04-30 05:52 UTC
While using CSS variables, I noticed that the current implementation only reflects the CSS rules that are defined in the ``domHost`` of a custom element. However, any ancestor could define a selector that matches a given node.  Let me provide some examples to illustrate the issue:

Case 1:
```html
<x-tree>
<style>
:host {
  --foo: 1;
}
</style>

--foo is 1 as expected
<x-leave>
<style>
:host {
  --foo: 2;
}
 --foo is 2 as expected
</style>
</x-leave>
</x-tree>
```

Case 2:
```html
<x-tree>
<style>
:host {
  --foo: 1;
}
</style>

`--foo` is 1 as expected
<x-leave>
`--foo` is 1 as expected since it's inherited from the DOM host
</x-leave>
</x-tree>
```

I have concluded after a further investigation that the problem isn't the order of
```js
  (1) this.mixin(props, this._computeStylePropertiesFromHost());
  (2) this.mixin(props, this._computeOwnStyleProperties());
```
as I suggested in https://github.com/Polymer/polymer/pull/1459, but rather the the selector matching mechanism.  For example, if we were using divs and css properties, we will get this result:

```html
<style>
.tree {
  color: red;
}

.substree {
  color: blue;
}
  
.tree .subtree {
  color: green;
}
</style>

<div class="tree">
<!-- color is red -->
<div class="subtree">
<!-- color is green since the selector `.tree .subtree` has higher precedence than `.subtree`-->
</div>
</div>
```

This is what the implementation of custom variables doesn't handle yet because it assumes that the only way you can override properties is by defining them in their immediate ``host``.  I think the rules that contain CSS variables should be propagated down the tree in order to make it work.

So for example:
```html
<head>
<style is="x-style">
x-tree {
  --foo: 2;
}
x-tree x-leave {
  --foo: 3;
}
</style>
</head>
<x-tree>
<style>
:host {
  --foo: 1;
}
</style>
--foo should be 2, so that it will work in the same way as regular CSS properties.
<x-leave>
--foo should be 3, instead of 1.
</x-leave>
</x-tree>
```
I hope it helps.

**Comment by sorvell** [comment] 2015-05-05 13:35
This is by design. Polymer's custom property support is intended primarily to support cross scope styling, not inheritance from parent to child. 

This is done for efficiency. We shim property values only at scope boundaries, not across the entire tree. To do so would require computing style inheritance through the entire dom tree, which we think is simply not practical.

Native custom properties will support these type of use cases.

**Comment by arthurevans** [comment] 2015-05-06 00:34
So is this doc incorrect (from the PRIMER):

These custom properties can be defined similar to other standard CSS properties
and will inherit from the point of definition down the composed DOM tree,
similar to the effect of `color` and `font-family`.

**Comment by sorvell** [comment] 2015-05-06 04:00
Fixed in PRIMER via https://github.com/Polymer/polymer/commit/4ab986bdf0a234e11b51433624eb1de4755cf272

**Closed** 2015-05-21 23:29 UTC

**Comment by dleroux** [comment] 2016-05-10 14:59
What is interesting is that this looks like it works with a mixin but not a simple variable.
