### ISSUE TITLE
Diffrent behavior <content> in Shadow dom and Shady dom

### ISSUE THREAD

**Issue by dihar** [Polymer/polymer#3706] opened 2016-06-10 12:24 UTC
### Description

Why in shadow dom <content> doesnt unwraped, how in shady dom: 

![image](https://cloud.githubusercontent.com/assets/12913462/15963966/8f1bcf8c-2f1e-11e6-9746-7e2d85beba8f.png)

![image](https://cloud.githubusercontent.com/assets/12913462/15964029/0048910e-2f1f-11e6-90c0-f7fcd8f94152.png)
### Browsers Affected
- [ ] Chrome
### Versions
- Polymer: v1.1.0
- webcomponents: v0.7.22

**Comment by miztroh** [comment] 2016-06-10 13:29
Try enabling the "Show user agent shadow DOM" in Chrome's Developer Tools settings.

**Comment by dihar** [comment] 2016-06-10 14:22
Miztroh, ok, I see, that <content> tag must be in dom, but why with polyfill it not that? Tag <content> deleted after attached

**Comment by miztroh** [comment] 2016-06-10 14:24
The polyfill won't show native elements' local DOM.

**Comment by dihar** [comment] 2016-06-10 14:41
I'm trying to explain on example:
I created element-wrap of <video>
```
<link rel="import" href="/components/polymer/polymer.html">

<!--
@todo comment
-->

<dom-module id="lms-video">
	<template>
		<style>
			:host {
				display: block;
			}
			.wrap{
				width: 100%;
				position: relative;
			}
			.play-button{
				position: absolute;
				top: 50%;
				left: 50%;
				transform: translate(-50%, -50%);
				width: 164px;
				height: 164px;
				border-radius: 50%;
				background-color: #3a7ad9;
				cursor: pointer;
				transition: all .1s ease-in;
			}
			.arrow{
				width: 46px;
				position: absolute;
				top: 50%;
				left: 55%;
				transition: all .1s ease-in;
				transform: translate(-50%, -50%);
			}
			.play-button:hover{
				width: 175px;
				height: 175px;
			}
			.play-button:hover .arrow{
				width: 40px;
			}
			#video {
				width: 100%;
			}
		</style>
		<div class="wrap">
			<video id="video">
				<content></content>
			</video>
			<div class="play-button">
				<svg class="arrow" viewbox="0 0 46 61">
					<polyline points="0,0 46,30.5 0,61" fill="#ffffff">	
				</svg>
			</div>
		</div>
	</template>
	<script>
		(function() {
			'use strict';
			var counter = 0;
			Polymer({
				is: 'lms-video',
				properties: {
					_video: Object
				},
				attached: function(){
					this._distributeContent();
					this._video = this.$.video;

					this._video.addEventListener('tap', this._toggleVideo.bind(this));
					this.$$('.play-button').addEventListener('tap', this._toggleVideo.bind(this));

					this._video.addEventListener('play',this._videoPlay.bind(this._video, this));
					this._video.addEventListener('pause',this._videoPause.bind(this._video, this));

				},
				/** tag video require source tags in child, 
					but in shadow dom they distributed in tag content, 
					fix it in this function*/
				_distributeContent: function(){
					this.getContentChildren('content').forEach(function(node){
						this.$.video.appendChild(node);
					}.bind(this))
				},
				_toggleVideo: function(){
					if(!this._video){
						return false;
					}

					if(this._video.paused){
						this._video.play();
					} else {
						this._video.pause();
					}
				},
				_videoPause(host, e){
					var playButton = host.$$('.play-button');
					if(!playButton){
						return false;
					}
					playButton.style.display = '';
					host._video.removeAttribute('controls');
					playButton.animate([{opacity: '0'}, {opacity: '1'}], {
						duration: 200
					});
				},
				_videoPlay(host, e){
					var playButton = host.$$('.play-button');
					if(!playButton){
						return false;
					}
					playButton.animate([{opacity: '1'}, {opacity: '0'}], {
						duration: 200
					}).addEventListener('finish', function(e){
						playButton.style.display = 'none';
						host._video.setAttribute('controls', '');
					});
				}

			});
		})();
	</script>
</dom-module>
```
in main code this element show that: 

```
<lms-video>
    <source src="/uploads/test-video.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
</lms-video>
```

in shadow dom element <source> distributed to the <video> in <content> tag, and because of this <video> doesn't see <source>, with polyfill <source> distributed to the <video> in child. I created fix this moment(_distributeContent function), but really behaviors in shadow and shady dom can be diffrent?

P. S. I'm realy trying to type accessibly=)))

**Comment by arthurevans** [comment] 2016-06-10 15:58
@dihar Yes, there are functional differences. It sounds like your previous code was relying on an implementation detail of the shady DOM shim. Using `getContentChildren` should work correctly across both local DOM implementations. (If you want to be able to update the video dynamically by replacing the `<source>` element, you might look at [observeNodes](https://www.polymer-project.org/1.0/docs/devguide/local-dom#observe-nodes).

Shadow DOM is doing what it's supposed to do. The child node ("source") has a logical place in the tree, as a child of `<lms-video>`. When the browser renders this tree, it _projects_ or _distributes_ this node as if it was a child of the `<content>` tag. The dev tools are trying to show you all of this information—where `<source>`actually is in the tree and where's it's distributed to.

On a browser that doesn't support shadow DOM, the only way to get the child node to render in the correct place is to actually _put_ the child node there. So the shady DOM shim moves children around so that they appear in their final "distributed" position. The goal of the shim is to have your elements function similarly in shadow DOM and non-shadow DOM browsers. However, it's not perfect and there are some functional differences documented in the [local DOM](https://www.polymer-project.org/1.0/docs/devguide/local-dom) and [styling](https://www.polymer-project.org/1.0/docs/devguide/styling) chapters of the doc.

**Comment by dihar** [comment] 2016-06-14 07:26
arthurevans, thanks! I thik, I undestand you.

**Comment by jaichandra** [comment] 2016-09-09 18:24
This could be one of the reason for `paper-checkbox` and `paper-radio-button` breaking in ember.js. Below is a working example of the issue. Try navigating to 'about' and then back to 'index' route, and see the issue.
http://codepen.io/jaichandra/pen/jrOpab?editors=1010

**Comment by jaichandra** [comment] 2016-09-15 13:48
Updated above example with two more wrapper components for `paper-checkbox` - `x-foo` and `x-foo-content`. `x-foo` wraps `paper-checkbox` and doesn't use `<content>` tag. That one works fine. `x-foo-content` wraps `paper-checkbox` the same way but adds a `<content>` tag, and we see that it breaks again once we navigate to `about` and back to `index` route. 
http://codepen.io/jaichandra/pen/jrOpab?editors=1010

**Comment by TimvdLippe** [comment] 2017-09-13 21:38
Closing this issue as working as intended. The explanation of @arthurevans in https://github.com/Polymer/polymer/issues/3706#issuecomment-225222671 describes the limitations of shady dom. As shadow dom is now implemented natively in Safari and Chrome, you can rely on the native behavior instead of shady com.

**Closed by TimvdLippe** 2017-09-13 21:38 UTC
Labels: 1.x
