### ISSUE TITLE
Catch when interdependent observers cause infinite loop

### ISSUE THREAD

**Issue by andybons** [Polymer/polymer#3620] opened 2016-04-27 00:36 UTC
Say a user inadvertently creates the following scenario:

``` js
properties: {
  chicken: Object,
  egg: Object,
},

observers: [
  '_chickenHatched(egg)',
  '_eggLaid(chicken)',
],

_chickenHatched: function(egg) {
  this.chicken = this._crackOpen(egg);
},

_eggLaid: function(chicken) {
  this.egg = this._getEgg(chicken);
},

```

Then the moment either property becomes defined, infinite looping ensues...
![tumblr_mutbjnogjc1qz6z2wo1_500](https://cloud.githubusercontent.com/assets/365204/14838340/40a504a2-0bd5-11e6-9712-8640424be997.gif)

It would be nice to have an upper limit set on the number of dependent observers fired so that these bugs can be more easily tracked down.

(Per a discussion with @sorvell)

**Comment by d1manson** [comment] 2016-04-28 11:40
You might also encounter this via a `debounce`, especially in the zero-delay case.

**Comment by TimvdLippe** [comment] 2017-09-13 21:53
When you do this, the browser will report the infinite loop as `RangeError: Maximum call stack size exceeded at runEffectsForProperty` (see http://jsbin.com/noratigera/edit?html,console,output) The callstack contains the invoked methods, such that debugging should be fairly straightforward. Therefore I am closing this as working as intended.

**Closed by TimvdLippe** 2017-09-13 21:53 UTC
Labels: 1.x, api-feedback
