### ISSUE TITLE
this.push fires 2 modified events

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/polymer#3713] opened 2016-06-15 09:09 UTC
### Description

`this.push('array', value)` fires 2 `array-changed` events.
#### Live Demo

https://jsbin.com/fozotu/edit?html,console,output
#### Expected Results

Only 1 `*-changed` event should be fired when pushing data.
#### Actual Results

2 `*-changed` event should be fired when pushing data.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions
- Polymer: 1.5
- webcomponents: 0.7.22

**Comment by kaste** [comment] 2016-08-11 16:50
Can't repro; you probably changed your JSBin? Duplicate of #3226 ?

**Comment by TimvdLippe** [comment] 2017-08-15 23:41
I am unable to reproduce this issue as well and I think it has since been fixed. If you are still experiencing this issue, feel free to reopen this issue with a JSBin that shows the issue.

**Closed by TimvdLippe** 2017-08-15 23:41 UTC
Labels: 1.x
