### ISSUE TITLE
Contents of vanilla <template> disappears inside dom-bind

### ISSUE THREAD

**Issue by gaurav21r** [Polymer/polymer#2335] opened 2015-08-21 12:38 UTC
Greetings from [Super Elements!!!](https://github.com/rcorp/superelements)

We use HTML5s `<template>` for some cool stuff inside our custom element. When we use our element inside a `<template is="dom-bind">` Polymer seems to remove our `<template>`'s contents!

So
```html
<template is="dom-bind">
  <template id="my-template>
     Whatever!
 </template>
</template>
```

Isn't the same as
```html
<template is="dom-bind">
</template>
<template id="my-template>
   Whatever!
</template>

```
The bug can be better illustrated here:
http://plnkr.co/edit/A7GsB6kdZBZb4b2gMss4?p=preview

According to me a good architecture is for `dom-bind` should be that it **modifies only `is="dom-repeat"` `is="dom-if"`and `is="dom-bind"`** and **leave the vanilla HTML5 `<template>` alone!**

I hope you consider this a bug!!!

**Comment by gaurav21r** [comment] 2015-08-24 13:26
@kevinpschaaf @sorvell Thanks for immediate attention. What is meant by `p1`? I'm sorry I'm new to the conventions of this repo!

**Comment by kevinpschaaf** [comment] 2015-08-27 17:27
`p1` means priority 1, we use labels `p0` - `p3` to denote relative priority (0 highest).

We do this processing (cache the template's content and hand it back as `_content` as part of the outer template extension's createdCallback) for a couple reasons:

1. Better performance: `template.content.cloneNode(true)` runs faster when it does not have to recursively clone nested template content fragments
2. It avoids two critical browser bugs:
   * On Chrome, calling `template.content.cloneNode(true)` results in custom elements in any nested templates to be incorrectly upgraded (they should remain inert: https://code.google.com/p/chromium/issues/detail?id=430578, fixed in Chrome relatively recently)
   * On Safari, calling `template.content.cloneNode(true)` results in empty nested template content fragments (https://bugs.webkit.org/show_bug.cgi?id=137619, we confirmed that it is fixed in WebKit nightly, but it's not yet in a stable version of Safari yet)

However, we have a bailout option: If you place `preserve-content` on any nested templates, they should be left pristine (and subject to the browser bugs in 2 above).  This is the recommended solution, since we don't intend to remove the `_content` treatment in the short term for the reasons above.

**Closed by kevinpschaaf** 2015-08-27 17:27 UTC
Labels: p1
