### ISSUE TITLE
keySplices is never set in array observers (basic snippet in official docs fails too)

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3239] opened 2015-12-28 00:01 UTC
I am trying to figure out how array observers work -- unsuccessfully.
I was writing up some examples, and just couldn't get `changeRecord` to have meaningful values both at init time and when the array changed. In particular, `keySplices` seems to be always `null`. 

In the end, just to make sure, I pasted the exact example [in the guide](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation), and I am getting:

```
Uncaught TypeError: Cannot read property 'indexSplices' of undefined 
```

By digging into the code, I noticed that at init time `this.__data__` only have one key, `users`. With subsequent array operations (for example this.push( 'users', 'merc'), `this.__data__` has both `users` and `splices` as keys, but users.splices.keySplices is still `null`.

If the basic array observer in the docs doesn't work, then I get the feeling that maybe something bad has happened to the array observer...

**Comment by arthurevans** [comment] 2016-01-08 01:38
Hi @mercmobily. Do you have a jsbin or something that reproduces what you're seeing?

I tried plugging the doc sample into jsbin, and I **am** seeing that the _initial_ call to the observer has an undefined change record—which definitely seems like a bug. But subsequent ones appear to have both the `indexSplices` and `keySplices` properties:

http://jsbin.com/qalema/2/edit?html,console,output

**Comment by arthurevans** [comment] 2016-01-08 01:39
(Tagging this a bug because at a minimum, the undefined-initial-change-record seems like, well, a bug.)

**Comment by kaste** [comment] 2016-01-14 23:40
`indexSplices` and `keySplices` get indeed `null` as soon as you use `async` (or debounce). T.i. the changeRecord gets mutated. Ouch.

http://jsbin.com/tikosikomu/edit?html,console,output

**Comment by mercmobily** [comment] 2016-01-15 00:24
Please accept my apologies for not being as proactive as I should about this one. I just got swamped by work unexpectedly... do you guys want me to look into it more? I saw from the documentation that you are also rewriting the Array section... I suspected that maybe I was using it wrong?

**Comment by arthurevans** [comment] 2016-01-15 02:24
@kevinpschaaf the issue @kaste is seeing is a little puzzling to the user. It appears to be on purpose, to avoid keeping around (potentially large) change records:

https://github.com/Polymer/polymer/blob/4d45842a40064d509ec97ac897c2f4fb8782ffdc/src/standard/notify-path.html#L448

Should we document this as a limitation? Send the user a shallow copy?

(Also, why do we bother setting `array.splices` to the change record if we immediately null out the keySplices & indexSplices after firing the event?)

I don't _think_ it's related to the issue @mercmobily reported, but it could be.

**Comment by kevinpschaaf** [comment] 2016-01-15 20:52
`set`'ting the `array.splices` (it actually calls `notifyPath`) object causes path notifications to propagate to any observers of `array.*` or `array.splices` synchronously.  When the call to `notifyPath` returns all observers have been notified.  The reason for nulling is both to allow any previously deleted array items to be GC'ed (they are held in the change record), but it also serves a more important purpose: splice information is _temporal_, that is it only has meaning relative to the _current state of the array_; if you look at the change async after the change, the array may have been further mutated, and your ability to replay what happened is lost.

re: `keySplices`, in the current implementation, one must have first called `Polymer.Collection.get(array)` on the array once in question to indicate interest in key tracking.  This is an optimization to prevent key tracking for all arrays.  The reason being that being notified of changes to keys is generally non-useful unless you've read out the keys and have a base from which to deal with changes.

**Comment by arthurevans** [comment] 2016-01-15 22:12
Hm. I guess what I was asking there was why you set `array.splices = change` on [Line 444](https://github.com/Polymer/polymer/blob/4d45842a40064d509ec97ac897c2f4fb8782ffdc/src/standard/notify-path.html#L444) and then call `_notifyPath` on the next line. But that's an implementation detail, so not that important. Overall point makes sense, we need to make it clear that async handling of property-change events in general (and array mutations or object mutations in particular) is problematic, and should probably be avoided.

(I guess people probably don't usually need a debouncer on a property changed event, but if they do, um, I guess they should check the latest values instead of messing with the actual changes?)

The second point, though, is _super_ interesting. Because (I believe) `dom-repeat` is always going to call `Polymer.Collection.get(array)`, right? And as it happens, I inevitably add a `dom-repeat` to the template whenever I'm testing any code sample with an array in it, so I can easily see what I'm working with. 

As a result, my testing has always showed the `keySplices` property. So huh. Um. Maybe we document that the `indexSplices` property is always there, `keySplices` may be there, and we cover `keySplices` and `Polymer.Collection` in some advanced topics area. 

Any idea on the other issue, the initial changeRecord being undefined?

**Comment by kaste** [comment] 2016-01-15 22:26
@kevinpschaaf  Interesting reply. I was aware that splices are somewhat temporal. But you don't need a full replay always. I wanted to take some snapshots; and I used `keySplices.added` for that. The keys in there are pretty stable and usable. 

The underlying problem here is what I've shown in #2606. The internal event/notification system does not respect and use the actual value you send with the event. It always accesses the underlying data structure, the property the event is about. In effect a producer like say `<iron-ajax>` always have to hold a reference to the response, where it could just send the most recent event out and forget about it. Same here with `array.splices`. There should be no need for `array.splices` b/c we send the changeRecord with the following notifyPath anyway.

On the `keySplices`: Would it possible to make that a lazy evaluated getter? So that we don't get a penalty if we don't use it. 

@arthurevans Async/Debouncing events - be it property-changed events or whatever - has always the same implications: Maybe the world has changed since the original event came in. That's it and we have to deal with it. Please don't mutate arguments you send to user land. You wouldn't do this for click events either, although the user might have clicked something different already.

**Comment by kaste** [comment] 2016-01-16 13:13
About GC: If I remember correctly the debouncer does not free the callback after firing, t.i. it still holds a reference to it, preventing GC. (I just vaguely remember this from reading the actual code, and this could have changed since then as well.)

**Comment by mercmobily** [comment] 2016-02-19 01:30
Probably late in the game, but... here is [the JSBin that shows that the basic example doesn't work](http://jsbin.com/vopajed/).

The JSBin is the exact [code in the guide](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation), except a little bit extra to actually add a user.

1) As soon as the code is run, changeRecord is undefined
2) When a user is added, changeRecord.keySplices and changeRecord.indexSplices are both set to `null` (which I think it's what's been discussed here)

Things get a little better when using `Polymer.Collection.get` on `this.users`. On the JSBin, just uncomment the line:

    // UNCOMMENTING THIS MAKES THE SECOND CALL WORK
    //Polymer.Collection.get(this.users);

(BTW, without `Polymer.Collection.get(this.users);` I am getting erratic results with `keySplices` always set as `null` and `indexSpices` *sometimes* set to null, and other times set properly.

In general, it doesn't look like it's working as intended at all. The need to call `Polymer.Collection.get()` should be documented at least -- which would still leave the bug of having changeRecord set as `undefined`.

I hope the JSBin helps, even if it came a *little* late...!

**Comment by arthurevans** [comment] 2016-02-19 18:53
@kevinpschaaf @azakus I agree with @mercmobily here.

I think everything here is explained except why we're receiving an initial callback with an undefined change record. This just seems buggy.

The presence or absence of the `keySplices` property is odd and side-effecty, especially since we don't document `Polymer.Collection`, but at least we can document this in the short term.

**Comment by kaste** [comment] 2016-02-19 20:21
My #3423 would solve the initially undefined bug. This is a clean fix, so if that PR is declined I will submit a dirty fix for this issue.

I think `keysplices` should be deprecated. If it's costly to generate this value, I rather do this when I actually need it.

**Comment by ryanwtyler** [comment] 2016-03-15 15:02
I think this is related. I pass array wild card to a computedBinding and changeRecord.indexSplices is undefined immediately after checking for splices in change record path. 

_computeDisabled: function(l_attempts, positionChange, l_name) {
        console.log("name: " + l_name);
        console.log("positionChange: " + positionChange);
        console.log("path: " + l_attempts.path);
        if (l_attempts.path == "item.attempts.splices") {
          console.log("added:  " + l_attempts.indexSplices);

        }
        return false;
      }, 

http://codepen.io/ryanwtyler/pen/ZWBvQN?editors=1011

**Comment by mercmobily** [comment] 2016-04-30 06:37
Guys, what's the status on this?
I *believe* the behaviour of the GITS I had mentioned has changed (!), but changeRecord is still 'undefined'.
The example in the official documentation right now still fails (!):

    Polymer({

      is: 'x-custom',

      properties: {
        users: {
          type: Array,
          value: function() {
            return [];
          }
        }
      },

      observers: [
        'usersAddedOrRemoved(users.splices)'
      ],

      usersAddedOrRemoved: function(changeRecord) {
        changeRecord.indexSplices.forEach(function(s) {
          s.removed.forEach(function(user) {
            console.log(user.name + ' was removed');
          });
          console.log(s.addedCount + ' users were added');
        }, this);
      },

      addUser: function() {
        this.push('users', {name: "Jack Aubrey"});
      }

    });

> my-elem2.html:34 Uncaught TypeError: Cannot read property 'indexSplices' of undefined
> page.js:797 Uncaught TypeError: Cannot read property 'length' of undefined

...!

**Comment by kaste** [comment] 2016-04-30 15:09
My PRs on this issue have not been merged (nor declined), so for the initial call we still see an undefined. The only change so far is that the change record is stable and thus can be sent around and processed later.

**Comment by arthurevans** [comment] 2016-04-30 17:04
Hi folks,

Sorry things are moving so slowly. The month before I/O is traditionally the busiest time of year for the team and everyone is overbooked, so PR reviews typically lag. 

As for the docs, that's my fault. I've been working on a larger rewrite for the data binding docs and I was trying to avoid putting another little bandaid on existing docs. But I got steamrolled by I/O stuff before I could finish the rewrite. So here we are.

We could add a note about these oddities, something like:

**Change record may be undefined on first callback.** Due to a known issue, the change record may be undefined the first time the observer is invoked, so your code should guard against this.

keySplices is a weirder one, but I think we have to document it because people will see it under some circumstances.

**Comment by mercmobily** [comment] 2016-05-03 07:47
Documentation looks good (see my little note). BUT, should this bug stay open?

**Comment by kevinpschaaf** [comment] 2018-01-13 01:53
Since `keySplices` and the `Collection` abstraction has been removed from Polymer 2 altogether, I'm closing this issue as will not fix for 1.x.

**Closed by kevinpschaaf** 2018-01-13 01:53 UTC
Labels: 1.x, bug, p1
