### ISSUE TITLE
Polymer data binding issue when using immutable data

### ISSUE THREAD

**Issue by Qvatra** [Polymer/polymer#3762] opened 2016-07-02 09:14 UTC
### Description

Problem: we're using redux to manage state in our app. This is causing issues in the rendering. Changes in arrays (f.e. remove) are not correctly handled by the dom-repeat. What happens is that data and the stamped-templates are getting mixed up.
#### Live Demo

http://plnkr.co/edit/yvaB7A
here you can reproduce the issue.
We have found an ugly workaround but to use it we have to introduce internal array _items to be able to use Polymer mutation methods :

```
      var splices = Polymer.ArraySplice.calculateSplices(val, oldVal);
      this._items.splice(0, this._items.length);
      val.forEach(item => this._items.push(item));
      this.notifySplices('_items', splices);
```

related [StackOverflow question](https://stackoverflow.com/questions/37994019/polymer-1-5-how-to-notify-dom-repeat-when-using-immutable-data-structure)
#### Steps to Reproduce
1. Click on the first template to remove it
#### Expected Results

the first item and first template are removed.
#### Actual Results

the first item and last template are removed.
#### Question:

What is the correct way of using dom-repeat with immutable data?

**Comment by devinivy** [comment] 2016-07-06 03:50
Immutable data doesn't work well with Polymer data-binding because it removes the granularity of notifications and splices.  Consider this an area of research– Polymer supplies the data-binding and a low-level API to that data-binding via `notify()` and `notifySplices()`, so you would need to do the rest of the work to tie those things together.  Check-out this project which uses immutable data with Polymer: https://github.com/home-assistant/home-assistant / http://paulusschoutsen.nl/blog/2015/07/using-polymer-with-flux-and-a-global-app-state/

**Comment by tur-nr** [comment] 2016-07-11 10:14
In your demonstration I can't see your implementation of Redux. Is the demo just an imitation of your application? It would be good to see how you have integrated Redux and it's use within your elements. Also what's the use of `my-repeater.html`, can't see where it's use is.

I ask this because we are decisioning a similar issue in tur-nr/polymer-redux#13

**Comment by TimvdLippe** [comment] 2018-02-11 15:21
This is working as intended, as `<dom-repeat>` reuses templates for performance reasons and only updates properties. To remove templates, the `restamp` option should be added, which is tracked in #1713 and a PR is up at #4957. Therefore closing this issue as a duplicate of #1713.

**Closed by TimvdLippe** 2018-02-11 15:21 UTC
Labels: 1.x
