### ISSUE TITLE
JS error with dom-repeat and async splice array element in followed by remove last element

### ISSUE THREAD

**Issue by trevordixon** [Polymer/polymer#2009] opened 2015-07-01 23:38 UTC
Demonstration: http://plnkr.co/edit/isFkxmfNUa5mrhZL1wST?p=preview

If you splice an element into an array then remove the last element (in that order), in an async handler, and the array is items for a dom-repeat, you'll trigger a javascript error "Cannot read property '_children' of undefined".

**Comment by LM450N** [comment] 2015-07-02 08:59
The `splice` method belongs to the _Array.prototype_. So, it must be called directly on the array. Moreover, you have to reflect the property as attribute. Else the DOM is not updated on array value change.

Please see this version of [your Plunkr][1]

[1]: http://plnkr.co/edit/qBRGVDXZZ3XOFxIHDx0k

**Comment by trevordixon** [comment] 2015-07-06 18:30
@LM450N Polymer 1.0 requires `this.splice('arr', ...)` instead of `this.arr.splice(...)`. See https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-repeat.

**Comment by LM450N** [comment] 2015-07-06 18:56
Yes you're right. I learned this yesterday. My apologies.

**Comment by trevordixon** [comment] 2015-07-06 20:00
If you remove the last element first, then insert an element, there's no error, but once all elements are the same, dom-repeat does strange things.

http://jsbin.com/quyubahohu/edit?html,console,output

**Comment by kevinpschaaf** [comment] 2015-07-13 16:43
Confirmed the issue, fix is in progress.

**Closed** 2015-07-16 02:00 UTC
Labels: p0

**Comment by kevinpschaaf** [comment] 2015-07-16 02:22
The primary issue related to errors (throwing) when mutating an array multiple times in the same turn is resolved.

@trevordixon Note that your repro case also exhibited the issue in #1913 since you were pushing duplicate values (`'foo'`) on to the array, which accounts for the "strange things".

Original repro on master:
http://jsbin.com/tekiwu/edit?html,console,output

Confirmed that replacing `'foo'` with `Math.random()` makes it work as expected:
http://jsbin.com/zubama/edit?html,console,output

Stay tuned on #1913 if the duplicates issue was important to your use case...

**Comment by sansantosh** [comment] 2016-07-07 07:55
If I store 'this' in self variable and after REST operation success if I do self.shift('arrayName') or self.shift('arrayName', 1, 1). This operation fails. It adds weird item in array which results in this error: polymer.html:4209 [dom-repeat::dom-repeat]: expected array for `items`, found 1
