### ISSUE TITLE
Blog down https://blog.polymer-project.org/ 

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1603] opened 2015-05-24 02:40 UTC
Somebody pushed the wrong button :P

https://blog.polymer-project.org

**Comment by arthurevans** [comment] 2015-05-24 05:10
Thanks Gert. Yep, we have a DNS problem affecting the blog. Please stand by, may be offline for a couple of days.

**Comment by Nevraeka** [comment] 2015-05-26 13:35
thanks @arthurevans

**Comment by ebidel** [comment] 2015-05-26 14:00
Dupe of https://github.com/Polymer/docs/issues/1081#issuecomment-105442831

**Closed by ebidel** 2015-05-26 14:00 UTC
