### ISSUE TITLE
🎷 confusing dom-if / falsey detection for initial values

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2447] opened 2015-09-17 20:46 UTC
### :black_medium_square:  Given

``` html
<template is="dom-if" if="[[zap]]">
  <b>wow</b>
</template>
<template is="dom-if" if="[[!zap]]">
  <b>tank</b>
</template>
```

``` js
...
properties: {
   zap: String
},
attached: function() {
  this.setTimeout(function() {
    this.zap = 'doge';
  }.bind(this), 1000)
}
...
```
### :waning_gibbous_moon:  Expected
1. tank should show
2. then after 1 second wow should show (tank should not be showing now)
### :earth_africa: What happens IRL

tank never shows... and then wow shows (in 1 second)
### :pencil2:  Hypothesis

because `zap` is never "defined" polymer does not try and negative a value that has not been resolved
### :computer: :hammer: Hack fix

``` diff
properties: {
-   zap: String
+   zap: {
+     type: String,
+     value: ''
+   }
},
```
### :spaghetti: Ideal fix

In a dom-if... it should try and eval `zap` right away, because ideally I would like to be able to handle the "missing" case without having to define a falsey string val.

Thanks for the :watch: 
Let me know if this is a terrible idea... feel free to close :skull: :hear_no_evil:

**Comment by tomalec** [comment] 2015-09-20 23:34
:+1:

**Comment by samccone** [comment] 2015-10-13 20:28
ping @tjsavage -- This is something that keeps being a headache across applications that I am building, any thoughts?

**Comment by samccone** [comment] 2015-11-04 22:51
another ping on this issue :pager:  

I think the use-case of this can be expressed quite simply:

I want to hide a content area while a scope var is not defined, and instead show a loading indicator..

you would think we could do 

`dom-if="[[!foo]]"` however since foo is not defined this expression is not evaluated, Instead I have to introduce a new tmp var / method in my logic that gets computed off of foo, and initially is set to false... thus increasing the amount of state that I have to hold on to just to deal with this evaluating flow.

I would love to hear how other people are dealing with this, because it is something I continually hit when building async applications where data flows into my "state" post render
.

**Comment by tjsavage** [comment] 2015-11-05 01:34
I think this is quite reasonable, and probably fits into our [roadmap goal](https://github.com/Polymer/project/blob/master/Roadmap.md#core-library) of "Fix and make usage of `undefined` consistent throughout the library." The plan is to comb through all the places where `undefined` makes an impact and make sure they're all aligned, so this should certainly be looked at as part of that process.

**Comment by samccone** [comment] 2015-11-05 19:31
some non breaking syntax ideas to enable this behavior... (evaluating foo even if it is undefined)

```
<template is="dom-if" if="[{[foo]}]">
```

```
<template is="dom-if" if="[[[foo]]]">
```

```
<template is="dom-if" if="{{{foo}}}">
```


---


@nazar-pc @JeremybellEU any thoughts in this area?

**Comment by JeremybellEU** [comment] 2015-11-05 21:07
The syntax might be troublesome for new developers whom would confuse the 3 `{` with the regular 2, which might introduce programming errors.

In the last hour I have tried to understand the annotation setup mechanics. I have found when things are initiated, but sadly lack the experience where all calls land (they jump between files). For me it seems most logical if all properties are initially `undefined` and the property would be evaluated right away. Since `!undefined === true`, this issue would be solved.

Evaluating right away might lead into problems of ordering of properties, as shown in #2674 .

**Comment by nazar-pc** [comment] 2015-11-05 21:15
I personally don't have problems with `[[!zap]]`. The reason why is simple, literally from the first day of switching to Polymer 1.x I've started to send PRs with different bugs/features and since I really need them I'm using patched version myself and maintaining/rebasing it against upstream constantly.

PR I want to mention here is #2205, it basically does what **Hack fix** section suggests but with nice syntax:
```php
properties: {
   zap: ''
},
```
I'm not sure it solves initial problems, I also had difficulties with `undefined` in some places, but anyway this particular issue is easily avoided without any pain.
BTW, PR does not as nice as I'd like it to be, but it works, give it a try:)

**Comment by azakus** [comment] 2015-11-06 20:46
It seems like a bug that the default value of a type is not used when defining it in Properties.
As @tjsavage said, this should tie into the cleanup of `undefined` in the data binding system.

**Comment by sasivarnan** [comment] 2016-06-21 13:51
+1

Facing the same issue with Boolean type also.
http://plnkr.co/EgdYKE

**Comment by TimvdLippe** [comment] 2017-11-28 19:43
We have discussed this use-case and decided that it is working as intended. As the data-binding system of Polymer relies on a push-model (e.g. when you set values, side effects like bindings run), a value that has yet to be set (`undefined`) causes no side effects to occur. Thus, if you want to "push" the value and update the binding, you should use a value other than `undefined`. Luckily this should be straightforward with any other falsy value, such as `null`.

We do agree that this notion is different than the falsiness of `undefined` in JavaScript, but this is a consequence of the push model used in data-bindings. Thus I am closing this issue as working as intended.

**Closed by TimvdLippe** 2017-11-28 19:43 UTC
Labels: 1.x, databinding, dom-if, on roadmap, p1
