### ISSUE TITLE
`notifyPath` after a property is `delete`d

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2631] opened 2015-10-26 19:36 UTC
`notifyPath` seems to first check for changes and if it doesn't find changes it won't do anything. If we `delete` a property on an object and next trigger

```
this.notifyPath('object', this.object);
```

nothing will happen, so it would be useful to either have a `force` flag on `notifyPath`, or alternatively have it properly realize something changed at least.

**Comment by samccone** [comment] 2015-10-26 20:59
related https://github.com/Polymer/polymer/issues/2447

**Comment by GabiAxel** [comment] 2015-12-09 09:30
I suggest generalising this to any case of object properties change without reference change. I have a case where I want to `notifyPath` on multiple properties at a time, and currently this is not possible. I propose adding something like this:

```javascript
this.notifyPath('obj.*', obj);
```

which would make `notifyPath` bypass the reference equality check and would work for multiple properties change and deletion.

**Comment by kwaclaw** [comment] 2016-04-04 21:27
I would find this useful as well. In my case I am changing multiple properties on an array element provided by an external library, but I am not adding or removing any array elements.
As it stands right now I have to call notifyPath for each changed property. A single call would be preferable.

**Comment by darkengines** [comment] 2016-09-14 07:42
This would be usefull to me too. I'am working with json schema and I sometime need to delete properties. I also suggest something like this:
`this.delete('parentProperty.childProperty');`

**Comment by TimvdLippe** [comment] 2017-08-10 22:28
Still an issue with Polymer 2: http://jsbin.com/dolukotoso/edit?html,console,output

**Comment by merlinnot** [comment] 2017-08-26 14:12
For the time being, here's what I use as a workaround:
```
delete this.objectName[propertyName];
this.notifyPath(`objectName.${propertyName}`, false)
```

**Comment by TimvdLippe** [comment] 2017-12-03 22:00
Closing this as duplicate of #2565

**Closed by TimvdLippe** 2017-12-03 22:00 UTC
Labels: 2.x, databinding, enhancement, p2
