### ISSUE TITLE
Polymer shared styles will stop working?

### ISSUE THREAD

**Issue by Boscop** [Polymer/polymer#4874] opened 2017-10-08 23:17 UTC
I'm getting this warning in chrome dev console when I open my polymer app that uses shared styles:
> [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

Is this caused by the shared-styles.html? What should I do instead?

**Comment by web-padawan** [comment] 2017-10-09 03:35
Duplicate of #4679 and #4867. Fixed by #4849

See [this comment](https://github.com/Polymer/polymer/issues/4679#issuecomment-333187751) explaining why this warning appears regardless of the fix.

Please search for issues before asking questions like this. It is better to ask in the Slack channel.

**Closed** 2017-10-14 00:16 UTC
