### ISSUE TITLE
improve error message on invalid element names

### ISSUE THREAD

**Issue by fergald** [Polymer/polymer#1163] opened 2015-02-04 09:36 UTC
I just got this error message (because I didn't have a "-" in my element name)

Uncaught SyntaxError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'sentence'. The type name is invalid.
and a JS stack trace.

There was no reference to the file:line that was doing something bad.

Also the use of "type" in the exception but "element" everywhere else is unhelpful.

**Comment by HoverBaum** [comment] 2015-10-02 08:56
Just had the same issue. Found no reference on elements having to have a "-" in their names. This should be document, or even better fixed so elements don't have to contain a "-".

Am using Polymer 1.0.

**Comment by accidentallyc** [comment] 2015-10-02 09:07
@HoverBaum 

I think polymer is following the [w3c draft](http://www.w3.org/TR/custom-elements#concepts) regarding custom elements. It under chapter 4, saying 

> ... must contain a U+002D HYPHEN-MINUS character ...

I think. xD not so sure.

**Comment by HoverBaum** [comment] 2015-10-02 09:30
@accidentallyc 

Following the standard seems to make sense. So I shouldn't be talking about "fixing" things for Polymer. Though I still think this could be worth documenting better in the Polymer docs. (Actually it's documented in the polymer-generator readme.)

**Comment by fergald** [comment] 2015-10-02 10:08
It is actually documented in the tutorial too but it's easy to miss. Good
error messages would make things a lot easier.

**Comment by samccone** [comment] 2015-10-02 16:22
+1 to better baked in errors here :)

CC @ebidel @tjsavage

**Comment by ebidel** [comment] 2015-10-02 16:46
We have this documented in a bunch of places, but it's still easy to miss:

https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#register-element
https://www.polymer-project.org/1.0/docs/start/quick-tour.html#register
http://www.html5rocks.com/en/tutorials/webcomponents/customelements/#gettingstarted

I think we can improve the error message though.

**Comment by ebidel** [comment] 2015-10-02 16:48
Actually, this is the error message `document.registerElement` throws back in the browser. Can you file a  crbug.com and post it here?

Ex: `document.registerElement('abc')` produces this message.

**Comment by HoverBaum** [comment] 2015-10-02 17:31
@ebidel hope I did what you asked for https://code.google.com/p/chromium/issues/detail?id=538668&thanks=538668&ts=1443807038

**Comment by azakus** [comment] 2016-01-27 20:36
Dupe of #2736

**Closed by azakus** 2016-01-27 20:36 UTC
