### ISSUE TITLE
leading to 404 page on apptoolbox page

### ISSUE THREAD

**Issue by anandrajk** [Polymer/polymer#4943] opened 2017-11-17 20:29 UTC
**By mistake i raised this issue in polymer/docs kindly ignore or resolve.**

on page
>https://www.polymer-project.org/2.0/toolbox/

>header section 
 >Edit on GitHub link leading to  404 page

>https://github.com/Polymer/docs/edit/master/app/2.0/toolbox/.md 
             
 some how ".md" is added in end of link which has to be removed 
to resolve 404 redirection.
 i also added a screen shot with highlighted error area 

![spell](https://user-images.githubusercontent.com/5354591/32917750-2c769a36-cb46-11e7-9103-d6aee6049713.PNG)

**Comment by TimvdLippe** [comment] 2017-11-18 13:15
Closing as duplicate of https://github.com/Polymer/docs/issues/2387

**Closed by TimvdLippe** 2017-11-18 13:15 UTC
