### ISSUE TITLE
[ShadyDOM] Non-distributed nodes do not have attached() called.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#1365] opened 2015-04-02 23:56 UTC
In Shadow DOM non-distributed have `attached()` and `detached()` called at the appropriate times. In Shady DOM `attached()` at least isn't called.

**Comment by sorvell** [comment] 2015-04-03 01:20
This is a known limitation that we just haven't addressed yet. The node is not actually attached to dom so attachedCallback does not fire. We can detect and deal with this, but it adds some complexity.

**Comment by Meligy** [comment] 2015-07-21 04:49
Is there any other equivalent event? I have noticed detached has the same issue with 1.0.5 as well.

**Comment by TimvdLippe** [comment] 2017-08-20 15:44
@justinfagnani Going through the issues again and I am having trouble understanding what the problem is. If this is still an issue, could you create a JSBin that shows it?

**Comment by justinfagnani** [comment] 2017-08-21 09:39
The problem was that custom elements that are not distributed do not have their lifecycle methods called. I assume this is still a problem with ShadyDOM.

**Comment by TimvdLippe** [comment] 2017-11-19 15:31
I am unable to reproduce this issue: http://jsbin.com/hosazex/edit?html,console,output

**Comment by TimvdLippe** [comment] 2017-12-03 21:14
Closing this per above comment. Feel free to reopen with a JSBin that shows the issue.

**Closed by TimvdLippe** 2017-12-03 21:14 UTC
Labels: 1.x, enhancement, on roadmap, p3
