### ISSUE TITLE
All Styles are dropped for elements which have any CSS vars in their style description

### ISSUE THREAD

**Issue by shal1y** [Polymer/polymer#3476] opened 2016-02-25 21:17 UTC
### Description
Styles using CSS vars are being ignored and are not being included/loaded when elements are being loaded. This started after updating Polymer to v1.3.0

#### Steps to Reproduce
1. Create any polymer element
2. In it's style declaration, add **at-least** one CSS var, eg: color: var(--element-color, #ff0000)
3. Add the element into the project

#### Expected Results
The element should have its styles available in the page

#### Actual Results
**All** the styles for the element are ignored and not loaded

### Browsers Affected
- [✓] Chrome
- [✓] Firefox
- [] Edge : not tested
- [✓] Safari 9
- [] Safari 8 : not tested
- [] IE 11 : not tested

### Versions
- Polymer: v1.3.0
- webcomponents: v0.7.21

**Comment by arthurevans** [comment] 2016-02-25 22:02
Seems to be a duplicate of #3461. See that bug for a workaround.

There's a fix under testing for this, and we hope to have a new release out next week.

**Closed by arthurevans** 2016-02-25 22:02 UTC

**Comment by shal1y** [comment] 2016-02-25 23:06
Thanks a lot @arthurevans. Will be waiting for the update, tried the workaround, but did not work for me.
