### ISSUE TITLE
CSS @apply not working when parent has same component as sibling

### ISSUE THREAD

**Issue by jehna** [Polymer/polymer#4410] opened 2017-03-10 12:52 UTC
### Description
`@apply`'ed CSS property from native CSS mixin is not getting applied on component, when the component has been used previously in the DOM without the CSS property.

#### Live Demo
http://jsbin.com/hiceguvoca/1/edit?html,console,output

#### Steps to Reproduce
1. Create `my-element`
2. Append `my-element` to document.body
3. Create `wrapper-element` that also has `my-element` inside it.
4. Append `wrapper-element` to body after `my-element`
5. `@apply` a css variable called `--css-variable` in `my-element`
6. Try to set any CSS property to the `--css-variable` block inside the `wrapper-element`

#### Expected Results
The CSS property should be applied to the `my-element` component inside `wrapper-element`

#### Actual Results
The CSS property is not applied.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0-preview
- webcomponents: v1

**Comment by jehna** [comment] 2017-03-10 12:55
## Known workaround:

Add the same CSS property to the component that was first introduced in the DOM. (see comment in the jsbin example)

**Comment by azakus** [comment] 2017-03-12 23:49
Can reproduce without Polymer, so this is probably a ShadyCSS bug: http://jsbin.com/medaday/edit?html,output

**Comment by azakus** [comment] 2017-03-12 23:49
This issue was moved to webcomponents/shadycss#69

**Comment by TomK** [comment] 2017-04-01 07:55
I think this should be reopened here. I'm unable to reproduce it directly in shadycss, can anyone else get it to fail there?

Failing polymer codepen:
http://codepen.io/oridan/pen/jBQodm

**Comment by TomK** [comment] 2017-04-01 07:58
@azakus possible to write a unit test against shady that fails as per your example? It seemed to work for me, it's possible I set it up wrong though.

**Comment by azakus** [comment] 2017-04-05 21:40
@TomK looks like https://github.com/Polymer/polymer/pull/4399 caused stamping the template to move to `ready()` which worked around #4486

**Comment by azakus** [comment] 2017-04-05 21:42
Per findings in  https://github.com/webcomponents/shadycss/issues/69#issuecomment-290945588 and https://github.com/webcomponents/shadycss/issues/69#issuecomment-291962819, reopening this issue and closing webcomponents/shadycss#69

**Comment by azakus** [comment] 2017-04-05 21:45
Updated JSBin with master branches: http://jsbin.com/tajusit/edit?html,output, seems to work correctly.

However, I'm going to leave this open for a bit to make this a test in Polymer so we don't regress accidentally

**Closed** 2017-04-06 21:32 UTC
Labels: 2.x, css, p1
