### ISSUE TITLE
Negative numbers in computed bindings

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2264] opened 2015-08-13 09:39 UTC
```javascript
Polymer(
...
    properties : {
        negative_num : {type: Number, value: -1},
    },
    some_method : function (num) {
        return num;
    }
....

```
Not working, empty inside:
```html
<span>[[some_method(-1)]]</span>
```
Working, `-1` text inside:
```html
<span>[[some_method('-1')]]</span>
```
Working, `-1` text inside:
```html
<span>[[some_method(negative_num)]]</span>
```

**Comment by sorvell** [comment] 2015-08-15 00:20
@azakus Would you mind making a fix for this? It looks like the problem is that we parse a literal argument as a number only if it's positive: 

https://github.com/Polymer/polymer/blob/master/src/standard/effectBuilder.html#L214

**Comment by nazar-pc** [comment] 2015-08-17 00:08
I did PR for this: #2286

**Closed** 2015-08-19 00:20 UTC
Labels: p1
