### ISSUE TITLE
Regarding undefined's and computed expressions

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3572] opened 2016-04-10 12:16 UTC
Computed expressions are the base foundation for computed properties, computed annotations (e.g. `<div>[[foo(a, b)]]</div>`) and (multi-) observers. The handling of the undefined value is currently unsatisfactory. For example:

```
    <div>[[formatDate(data.lastModified, 'dd-mm-yy')]]</div>
```

This annotation will update as soon as we `set('data', data)` to a data structure that defines `lastModified`. If we then get new data, and `lastModified` becomes maybe eventually undefined, the annotation will not update at all. It will stay there unchanged, showing old data. Since we all live and breathe polymorphic data structures in JS, this is behavior is not sufficient. For the same reason something simple as: 

```
    <div>[[OR(data.customMessage, data.defaultMessage)]]</div>
```

doesn't work at all.

On top of that, there is an exception to the rule implemented: All expressions that receive only _one_ argument, are always called with any value, be it undefined or something else. 

I had three solutions for this in mind:
1. All expressions are by default guarded against undefined's. The user can opt-in to get undefined values (e.g. `[[OR(?data.customMessage, ?data.defaultMessage)]]`). This is pretty straight forward thinking and implemented in #3423 and #3452.
2. All expressions are guarded against seeing undefined's until all their dependencies can be fulfilled _once_. After that they receive undefined values unconditionally. This is (by mistake) implemented in #3560. That essentially means that each expression has its own initialization guard.
3. All expressions receive undefined values unconditionally. We guarantee that during config phase/the initialization of the element an expression is only evaluated _at most once_. (No PR yet.)

**Comment by kevin-wise-infusionsoft** [comment] 2016-04-12 23:35
This is one of the single biggest stumbling blocks.  I would prefer option 3 as that is the most intuitive.  Option 2 would also work reasonably well but requires more thought.  Option 1 would be a bare minimum, although it seems cumbersome to have to opt in to behavior that most people would expect to be the default.

**Comment by kaste** [comment] 2016-04-15 11:14
I would go for option 3 as well. Of course it is the hardest to implement :unamused:

**Comment by ChadKillingsworth** [comment] 2016-08-12 15:01
This just bit me hard on a project and took much debugging to find. Option 3 is the only sane choice in my opinion.

The fact that the current behavior is to be simply silently ignored makes this extremely difficult to debug - and it's not obvious that this is expected behavior from the documentation.

JSFiddle for reference: https://jsfiddle.net/vuds0b9u/24/

**Comment by kevin-wise-infusionsoft** [comment] 2016-08-12 18:04
@azakus Are undefineds treated how they are because of a philosphical difference, or is it just a matter of priorities?  In other words, if someone created a PR that implemented option 3, would it be considered (assuming it was high quality and didn't introduce new issues) or would it be rejected outright on the basis that it was undesirable behavior?  Just wondering where the core Polymer team stands on this issue.

**Comment by kaste** [comment] 2016-08-12 19:00
Yes, a comment isn't too much to ask.

Option 1 is a good choice if you don't want a breaking change. It solves the issue and makes the 1.x branch better. It is straightforward and easy to explain.

**Comment by TimvdLippe** [comment] 2017-08-08 02:05
Observers run with `undefined` in Polymer 2 as described in [the upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade#update-observers), therefore I am closing this issue.

**Closed by TimvdLippe** 2017-08-08 02:05 UTC
Labels: 1.x, api-feedback, databinding, needs discussion
