### ISSUE TITLE
Polymer.Base.splice doesn't properly update the underlying collection's keyMap correctly

### ISSUE THREAD

**Issue by urandom** [Polymer/polymer#2411] opened 2015-09-04 17:27 UTC
When processing a splice, a new key is generated. That key is not the correct index position of the item within the array. Its whatever comes after the last index. This in turn messes up any future calls to Polymer.Base.set for a property of an item of that array.
You'd call this.set('items.55.prop', false), and internally, the path would change from 'items.55.prop' to 'items.237.prop' or something like that. And when you get to any changed observer for 'items.*', the record contains the new messed up path, and ultimately you can't do anything with it.

**Comment by shawncplus** [comment] 2015-09-09 16:54
I ran into a similar (if not the same) issue while building a polymer element which renders a form from a JSON Schema.

*deep breath*

The element is used by specifying the schema on the element and it recurses specifying the child property's schema and its path for `this.set` it all works fine up to and including adding items to an 'array' type property. There is an observer on `formData.*` that watches for updates to values from form elements. All works fine and dandy until you splice an item out of an array and then change values in the form at which point the `set()` function will look like `this.set('formData.pets.1.type', 'dog');` (correct) but the observer will be notified with `{path: 'formData.pets.2.type'}` because `set()` internally uses `Polymer.Collection.get(array).getKey(prop);` which will return `2` for `formData.pets.1` because the map does not get updated on splice.

My workaround is the following:

    // this gets called on-value-changed of form elements
    this.set(this.schemaPath, e.target.value);
    // workaround (both lines required)
    this.notifyPath(this.schemaPath, e.target.value);

because notifyPath does not try to resolve a path to its Collection equivalent like `set()` does it will (thankfully) blindly accept that this is the correct path and will update the value appropriately. Now, interestingly enough this does not break if you `push()` an item to the array after splicing because of the aforementioned "bug". The new item will be at Collection index 3, not Collection index 2 which would break the `notifyPath()` workaround.

This was "fun" to debug

**Comment by jcmoore** [comment] 2016-04-05 01:19
I think I'm encountering an issue related to this one -- the problem seems to originate in `Polymer.Collection.prototype._arraySplices` (I intend to follow up tomorrow with a simple test case).  I may be fundamentally misunderstanding what Polymer.Collection has to do, but I'm interested in drafting a PR with some recommendations.  However, I am having some trouble understanding exactly what is expected to be in each of the `keySplices`.  Can someone enlighten me (perhaps you @kevinpschaaf )?

As far as I can tell, for an array of `indexSplices`:

```
keySplices = indexSplices.map(function (iSplice) {
  return {
    added: 
  };
});

function numArray (length) {

}
```

**Comment by jcmoore** [comment] 2016-04-05 23:27
Here's a jsbin I hope should help illuminate the problematic conditions I'm seeing -- https://jsbin.com/retujemaqi/3/edit?html,output

**Comment by TimvdLippe** [comment] 2017-08-21 15:33
I tried to reproduce this problem in Polymer 2 (http://jsbin.com/durajuciqu/edit?html,console,output) and it seems that all paths are correct. Therefore I am closing this issue. If you can modify my JSBin to again show the error, we can reopen this issue and debug further 😄

**Closed by TimvdLippe** 2017-08-21 15:33 UTC
Labels: 1.x, databinding, p2
