### ISSUE TITLE
Polymer 3.0.2 uses named modules

### ISSUE THREAD

**Issue by paulvarache** [Polymer/polymer#5242] opened 2018-05-23 16:31 UTC
#### Live Demo
https://harmonious-pin.glitch.me/

#### Expected Results
The browser loads the element

#### Actual Results
The browser cannot load the element and throws this error: `Uncaught TypeError: Failed to resolve module specifier "@webcomponents/shadycss/entrypoints/apply-shim.js". Relative references must start with either "/", "./", or "../"..`

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v3.0.2
- webcomponents: v2.0.0

**Comment by TimvdLippe** [comment] 2018-05-23 16:45
This is a duplicate of #5238. Please see our response at https://github.com/Polymer/polymer/issues/5238#issuecomment-390012108 for solutions.

**Closed by TimvdLippe** 2018-05-23 16:45 UTC
