### ISSUE TITLE
CSS variables and animation keyframes

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#3029] opened 2015-11-19 15:32 UTC
Hello! While testing out the CSS variables I ran into an odd problem: the CSS variables seem to not be parsed inside animation keyframes.

[Here](https://jsbin.com/rurudawuhe/edit?html,output)'s a jsbin describing what I was trying to do.

Is this a bug inside Polymer's parser or is this not even covered in the CSS variables spec? How would one go about making an animation inside shadowDOM customisable with the current CSS variables/mixins system?

Cheers.

**Comment by arthurevans** [comment] 2015-11-19 20:38
Duplicate of #2399. I think this is a limitation/bug in Polymer's custom properties shim.

Maybe @sorvell or @notwaldorf can comment, but I think the current answer is that you can't currently customize anything inside the keyframe.

**Closed by arthurevans** 2015-11-19 20:38 UTC
Labels: duplicate

**Comment by jpdevries** [comment] 2015-12-30 22:13
I'm also noticing keyframes for CSS Variables not being parsed in this codepen 
http://codepen.io/jpdevries/pen/MKbrrX?editors=110

best viewed in Firefox 42.0
