### ISSUE TITLE
lint polymer with errors

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer#4482] opened 2017-03-31 21:38 UTC
### Description

Error thrown when lint polymer
#### Steps to Reproduce

1. Clone https://github.com/Polymer/polymer.git
2. Install `npm install && polymer install`
3. Run `gulp lint`

#### Expected Results

lint passed
#### Actual Results

lint with error in file lib/utils/gestures.html
`656:29  error  Parsing error: Identifier 'movefn' has already been declared`

### Versions

- Polymer: https://github.com/Polymer/polymer/commit/8c1a5765b88f15926e3ad6c555904c834e36547a

**Comment by sorvell** [comment] 2017-04-03 22:05
We're not able to reproduce the warning based on our [lint rules](https://github.com/Polymer/polymer/blob/master/.eslintrc.json). Can you refine or give alternate steps to see the problem? Might you be using different linting rules?

**Comment by baocang** [comment] 2017-04-04 06:32
@sorvell 
see https://travis-ci.org/RhymeStudio/polymer/jobs/218341542

I do git reset --hard 6ca0927 and git push origin HEAD --force

It still appear，Is my travis-ci with some wrong?

**Comment by web-padawan** [comment] 2017-04-04 06:37
@baocang try to put this line into your `.eslintrc.json` 
```
"root": true 
```
By default, ESLint will look for configuration files in all parent folders up to the root directory. Not sure if this is really the reason, but such a behavior can sometimes lead to unexpected results like this.

**Comment by baocang** [comment] 2017-04-04 06:39
Thank's @web-padawan, I have a question there: Is the code mean declared a function named movcefn and a variable with the same name in the same scope.

```javascript
let movefn = function movefn(e) {
    if (!hasLeftMouseButton(e)) {
      self._fire('up', t, e);
      untrackDocument(self.info);
    }
};
```
why not use 
```javascript
let movefn = function (e) {
    if (!hasLeftMouseButton(e)) {
      self._fire('up', t, e);
      untrackDocument(self.info);
    }
};
```
or 
```javascript
function movefn (e) {
    if (!hasLeftMouseButton(e)) {
      self._fire('up', t, e);
      untrackDocument(self.info);
    }
};
```

**Comment by baocang** [comment] 2017-04-04 06:50
And see : https://travis-ci.org/RhymeStudio/polymer/jobs/218339581

I just set root in my .eslintrc.json 😩 
```JSON
"root": true
```

**Comment by web-padawan** [comment] 2017-04-04 10:08
> the code mean declared a function named movcefn and a variable with the same name in the same scope.

This is usually used for recursion. When you store function expression in variable, it's functions name must be still defined like this so function could call itself.

So, did that `"root": true` option resolve your issue or not?

**Comment by baocang** [comment] 2017-04-04 14:36
@web-padawan The `"root": true` option can not resolve my issue the right job at: https://travis-ci.org/RhymeStudio/polymer/jobs/218346155

**Comment by baocang** [comment] 2017-04-04 14:47
@web-padawan in addition, the strange is i can pass the link on my MacBook Pro.

**Comment by kevinpschaaf** [comment] 2017-04-25 19:45
Closing, as we cannot reproduce this locally or on CI.  Feel free to re-open a new issue if there is a clear reproduction case.  Thanks.

**Closed by kevinpschaaf** 2017-04-25 19:45 UTC
Labels: 2.x, pending-response
