### ISSUE TITLE
Two Way Binding not working

### ISSUE THREAD

**Issue by jasondbriggs** [Polymer/polymer#1201] opened 2015-02-17 18:54 UTC
I'm trying to get 2 way binding to work properly. I setup a test case here, so you can see what we are trying to do.

http://plnkr.co/edit/KjQ9DusaFg2jp1BTFUde?p=preview

**Comment by pflannery** [comment] 2015-02-17 19:47
you need to specify is="auto-binding" when [binding outside of polymer](https://www.polymer-project.org/docs/polymer/databinding-advanced.html#bindingoutside)

```html
   <template is="auto-binding">
       <test-app></test-app>
   </template>
```

**Comment by Nevraeka** [comment] 2015-02-27 11:55
:+1: @pflannery - can this be closed?

**Comment by davidmaxwaterman** [comment] 2015-02-27 12:31
I don't quite understand where the binding is done *outside* of polymer in that example - as far as I can see, the binding is attempted inside the test-app polymer element by using the same property for both test-input elements.

IMO, the issue here is that they are attempting to reflect the changes occurring in one of the properties back out to the value of the attribute. I found an example of this here, under 'attribute reflection' :

<https://divshot.com/blog/web-components/polymer-features-you-may-have-missed/>

I guess using auto-binding might be a 'better way - but is it as simple as wrapping it in an auto-binding template? ...and isn't the example supposed to work too, albeit with the `reflect: true` addition (and perhaps removal of the `*10` which just makes things confusing)?

...or could you do something like this :

```
<test-input id='one' value='{{$.two.value}}'></test-input>
<test-input id='two' value='{{$.one.value}}'></test-input>
```

So, when one is updated, the other is too (and vice versa.

**Comment by pflannery** [comment] 2015-02-27 16:50
The example has changed since I last looked at this. It was just binding directly to the {{value}} not {{hue * 10}}, here is the original http://plnkr.co/edit/LMMrosVjNca2zGFqMsdz?p=preview

I've noticed what's happening now, if the polymer elements in the original example are are swapped around so that ```test-input``` comes before ```test-app``` then it works.

@Nevraeka perhaps this is still a bug, but it's not something I can clarify. I have a feeling though that dependencies should be defined before using them.

**Comment by arthurevans** [comment] 2015-02-27 17:34
In the case of the `hue * 10` binding, I think the issue is that the _expression_ is basically one way. If you use a simple identifier, Polymer sets up a two-way binding, but if you have a more complicated expression, it doesn't. (In this case, you can guess what the user wants to do, but if you consider an expression like `hue * multiplier`, there's no way for the library to guess what you'd want to assign.

With filters, you can define a reversible transformation by specifying a `toModel` function. See:

http://plnkr.co/edit/XzCRMxxd30Zu2ssSjJbg?p=preview

@davidmaxwaterman, `reflect` is different from two-way data binding. `reflect` causes the corresponding attribute to be set whenever the property value changes. That's useful primarily if you want to style (or querySelect) based on an attribute value. 

For more, see: 

https://www.polymer-project.org/docs/polymer/polymer.html#attrreflection

And finally, @pflannery is correct that dependencies need to be defined before they're used. Otherwise, data binding may not get set up correctly.

**Comment by davidmaxwaterman** [comment] 2015-02-27 22:33
:+1: I was suspicious of the *10 :) anyway, great explanations - thanks guys.

**Comment by tjsavage** [comment] 2015-10-23 23:33
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:33 UTC
Labels: 0.5
