### ISSUE TITLE
Array mutation events are fired twice when changing the last item in an array when the item is a paper-toggle-button.

### ISSUE THREAD

**Issue by beckula** [Polymer/polymer#2515] opened 2015-10-01 19:02 UTC
This may not be limited to paper-toggle-button (may be related to boolean data types).

Whenever I use Polymer.Base to add a new record to a two-way bound array of objects, and I toggle a paper-toggle-item bound to one of the fields in the last item in the array, the change is fired twice.  Future toggles of the same item only fire once.

Reproduced here:
http://jsbin.com/varucanica/edit?html,console,output

**Comment by kevinpschaaf** [comment] 2015-10-12 17:28
This is an element-specific side-effect of known issue https://github.com/Polymer/polymer/issues/2360.

Note in the example, the model for the added checkbox is not equivalent to the initial models: whereas the initial models have either `state: true` or `state: false`, the newly added model has an `undefined` state (this is important for the repro).  Issue https://github.com/Polymer/polymer/issues/2360 covers the problem with binding `checked={{item.state}}` where `state` is undefined resulting in the `checked` property being undefined despite having a default value of `false`.

The reason the observer is fired twice when toggling the button is due to an element-specific implementation detail:

* in response to the `down` event, the element syncs the `checked` value to the `active` value, causing the still false `active` value to be set to `checked`, resulting in an `undefined` --> `false` change sent to the observer
* in response to the `tap` event, the element sets the `checked` value to `true`, resulting in another call to the observer

If you click the element slowly, you can notice the observers fire on different events (down vs. up).

If the repro is modified so that the `state` property is valued when pushing a new object, the issue is avoided:

```
  addThing: function(e) {
    this.push('listOfThings', {state: false});
  },
```

That would be the suggested workaround for now until the underlying issue is resolved (which is relatively high priority for us).

**Comment by beckula** [comment] 2015-10-12 18:40
Kevin thanks for the write up.  I'll give the workaround a try.

**Comment by azakus** [comment] 2015-11-07 00:38
Closing as duplicate of #2360

**Closed by azakus** 2015-11-07 00:38 UTC
Labels: code-yellow
