### ISSUE TITLE
Feature: model capturing items on outer levels in dom-repeat

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#1919] opened 2015-06-19 12:11 UTC
quote from [Handling events in dom-repeat templates](https://www.polymer-project.org/1.0/docs/devguide/templates.html#handling-events)
##### 
##### 
##### When you add a declarative event handler inside the <dom-repeat> template, the repeater adds a model property to each event sent to the listener. The model is the scope data used to generate the template instance, so the item data is model.item

This feature seems to support only one (the inner-most) level. `i` in the following example is not captured. Please click on `<input>`'s to experiment:

```
<!DOCTYPE html>
<html>
  <head>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="proto-element.html">
  </head>
  <body>
    <proto-element></proto-element>
  </body>
</html>

<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/iron-input/iron-input.html">
<dom-module id="proto-element">
    <template>
        <template is="dom-repeat" items="{{rows}}" as="row" index-as="i">
            <template is="dom-repeat" items="{{row}}" as="column" index-as="j">
                <input is="iron-input" bind-value="[[column]]" on-tap="clicked">
            </template>
        </template>
    </template>
</dom-module>
<script>
    Polymer({
        is: "proto-element",
        properties:{
            rows:{
                type:Array,
                value:function(){ return [[1,2],[3,4]]; }
            }
        },
        clicked:function(e){
            alert(e.model.i+"->"+e.model.j);
        }
    });
</script>
```

**Comment by arthurevans** [comment] 2015-06-19 18:18
I can repro this issue, but I'm not sure if it's a documentation issue, a code issue, or both.

Here's the breakdown: examining the results, it appears that e.model only includes the values that are bound _in that scope_. Since the inner template repeat doesn't bind to `{{i}}`, it doesn't get attached to the model object.

Binding `i` in the inner scope fixes this:

http://jsbin.com/tinuda/1/edit?html,output

However, binding `i` in the outer scope doesn't make it available in e.model in the inner scope.

It seems to me that this is probably incorrect, and that perhaps we should take index-as and item-as as cues that the data is interesting even if it's not bound. 

As a workaround, you can assign an ID to the outer `dom-repeat`, and then use `indexForElement`, like this:

            var outerIndex = this.$.outerDomRepeat.indexForElement(e.target);

http://jsbin.com/tinuda/5/edit?html,output

@kevinpschaaf, is the current behavior WAI? If so, it seems like the docs should be updated to note that _only paths bound in the current scope are available in e.model._ Please advise.

**Comment by kevinpschaaf** [comment] 2015-06-22 19:27
Right now it is working as intended, although I acknowledge the use case presented that we don't cover.

For performance reasons, only notifications for properties actually used in inner scope are forwarded in, hence the inner instance not having access to outer scope properties that were not referenced in bindings.

The workaround @arthurevans provided works well for two nested `dom-repeats`, where you can access the outer `dom-repeat` by id.  More generally, you could do something like bind the outer `i` to the inner `dom-repeat`, and access that from `event.model.dataHost` (where `dataHost` of the `model` will be that `dom-repeat` that created it):

```html
        <template is="dom-repeat" items="{{rows}}" as="row" index-as="i">
            <template is="dom-repeat" items="{{row}}" as="column" index-as="j" outer-index="{{i}}>
                <input is="iron-input" bind-value="[[column]]" on-tap="clicked">
            </template>
        </template>
```

```js
        clicked:function(e){
            alert(e.model.dataHost.outerIndex + "->" + e.model.j);
        }
```

We'll keep this issue open to consider better API to meet this use case.

**Comment by masaoliou** [comment] 2015-06-26 06:23
@kevinpschaaf I fail to figure out the reason that the following `alert()` yields the first two `undefined,undefined`:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="bower_components/iron-input/iron-input.html">
    <dom-module id="proto-element">
        <template>
    		<table>
            <template is="dom-repeat" items="{{rows}}" as="row" index-as="i">
    			<tr>
                <template is="dom-repeat" items="{{row}}" as="column" index-as="j" row-index="[[i]]">
    				<td>
    					<template is="dom-if" if="[[yes()]]">
    						<input is="iron-input" bind-value="[[column]]" on-tap="clicked" data-row-index$="[[i]]">
    					</template>
    				</td>
                </template>
    			</tr>
            </template>
    		</table>
        </template>
    </dom-module>
    <script>
        Polymer({
            is: "proto-element",
            properties:{
                rows:{
                    type:Array,
                    value:function(){ return [[1,2],[3,4]]; }
                }
            },
    		yes:function(){
    			return true;
    		},
            clicked:function(e){
                alert(e.model.dataHost.rowIndex+","+e.model.j+","+e.target.getAttribute("data-row-index"));
            }
        });
    </script>

**Comment by masaoliou** [comment] 2015-11-11 13:33
Perhaps this issue is relative to [this issue](https://github.com/Polymer/polymer/issues/1865).

My recent workaround for this missing feature is adding *data-index* attributes to dom-repeat children. Then the script can find its own position by referencing to these attributes like this:

       <template is="dom-repeat" items="{{rows}}" as="row" index-as="i">
            <template is="dom-repeat" items="{{row}}" as="column" index-as="j">
                        <input is="iron-input" bind-value="[[column]]" on-tap="clicked" data-row-index$="[[i]]" data-column-index$="[[j]]">
            </template>
        </template>

        clicked:function(e){
                console.log(e.target.getAttribute("data-row-index"),e.target.getAttribute("data-column-index"));
        }

**Comment by yingqiaogit** [comment] 2016-02-20 15:53
I used event.model.dataHost.dataHost.<item>.<field> in an on-click function inside the inner dom-if template to retrieve the <item>.<field> in the dom-repeat template. It works!

**Comment by dlsso** [comment] 2016-07-11 15:51
Thanks yingqiaogit, good find!

**Comment by TimvdLippe** [comment] 2017-11-28 20:04
Given the performance characteristics of `<dom-repeat>`, the workaround as posted by @yingqiaogit is the trade-off we have to make. We have considered exposing explicit API for this use-case, but we are not convinced there are a lot of benefits to that API, other than the current workaround. Therefore I am closing this issue.

**Closed by TimvdLippe** 2017-11-28 20:04 UTC
Labels: 1.x, dom-repeat, enhancement, p3
