### ISSUE TITLE
paper dialog demo

### ISSUE THREAD

**Issue by elodiebq** [Polymer/polymer#1218] opened 2015-02-24 21:22 UTC
https://www.polymer-project.org/components/paper-dialog/demo.html
when click "Colors", it doesn't work, when click "Size & Position", it will show colors and size&position effects.

**Comment by davidmaxwaterman** [comment] 2015-02-24 21:53
wfm with chrome Version 41.0.2272.63 beta (64-bit)....any browser detail?

**Comment by elodiebq** [comment] 2015-02-25 02:17
version: 40.0.2214.115 (64-bit)

2015-02-24 16:53 GMT-05:00 Max Waterman <notifications@github.com>:

> wfm with chrome Version 41.0.2272.63 beta (64-bit)....any browser detail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/1218#issuecomment-75854572>.
>



-- 
李碧萩 Rachel Li

北京外国语大学 计算机系
Department of Computer Science , Beijing Foreign Studies University

Mobile:15201314701

**Comment by winhowes** [comment] 2015-02-25 03:21
Works for me too on Chrome version: 40.0.2214.115 (64-bit)

**Comment by pflannery** [comment] 2015-02-25 04:37
I see the same issue
- click colors then click away
- click size&position then click away
- click size&position and the colors is shown instead

chrome Version 40.0.2214.115 m

**Comment by winhowes** [comment] 2015-02-25 04:58
The issue is that the `<paper-dialogue>` element is removed from it's parent and inserted in the `<overlay-host>`'s shadow DOM. When the dialogue/overlay is closed the `<paper-dialogue>` is appended into its original parent.  The button when clicked, looks for the next element and calls `toggle()` on it.  Because the `<paper-dialogue>` is appended into it's original parent and not inserted after the button (where it originally was), clicking the button fails/causes unexpected behavior. This happens in more than just the color/size&position case

**Comment by Nevraeka** [comment] 2015-02-27 11:53
@winhowes or @davidmaxwaterman are you working on a PR for this?

**Comment by winhowes** [comment] 2015-02-28 00:50
Yeah, I am

**Comment by tjsavage** [comment] 2015-10-23 23:36
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Closed by tjsavage** 2015-10-23 23:36 UTC
Labels: 0.5
