### ISSUE TITLE
Attribute to properties{} mapping fails with single letter between two dashes

### ISSUE THREAD

**Issue by richcirminello** [Polymer/polymer#3397] opened 2016-02-10 00:26 UTC
Polymer: documentation says dashes in names of attributes map to camelCase in the properties object. 
However I could not get this to work:

collapse-y-axes : collapseYAxes

However, these attribute : properties{} mappings worked just fine:
collapse-y : collapseY 
collapse-ya-axes : colllapseYaAxes
collapse-yaxes : collapseYaxes 
collapse-axes-y : collapseAxesY
 
It appears that it only fails when there is a single letter between dashes which would cause a double camel hump.

Expected behavior:
collapse-y-axes in HTML should map to collapseYAxes in properties{}

**Comment by azakus** [comment] 2016-02-10 01:09
This sounds like a duplicate of #3206, which was fixed in master with #3279. It will be in the next release of Polymer.

**Closed by azakus** 2016-02-10 01:09 UTC
