### ISSUE TITLE
horizontal scrollbar for proto-element.html does not work on quick tour page when switching demo tab to index.html and back

### ISSUE THREAD

**Issue by dyoo** [Polymer/polymer#2599] opened 2015-10-20 01:00 UTC
In the "Register an element" section of the quick tour, at

    https://www.polymer-project.org/1.0/docs/start/quick-tour.html

For the demo-tabs element, I see horizontal scroll bars for the source code of proto-element.html, which appear to work initially.  However, if I click the index.html tab, and then click back onto the proto-element.html tab, then I can't click the scroll bar to see the rest of the content any more.

**Comment by arthurevans** [comment] 2015-10-20 19:58
I think this is a duplicate of https://github.com/Polymer/docs/issues/1071, which I haven't been able to reproduce.

Can you please comment there and add the following information:

- Browser name & version
- OS
- Scrolling device (mouse, trackpad, touchscreen, etc.)

Thanks!

**Comment by arthurevans** [comment] 2015-10-20 19:59
Closing as duplicate of https://github.com/Polymer/docs/issues/1071.

**Closed by arthurevans** 2015-10-20 19:59 UTC
