### ISSUE TITLE
Custom Elements added to DOM are not immediately associated with their class

### ISSUE THREAD

**Issue by rjsteinert** [Polymer/polymer#5290] opened 2018-07-16 20:58 UTC
Is this perhaps a recent regression in Chrome?

<img width="1280" alt="screen shot 2018-07-16 at 4 56 45 pm" src="https://user-images.githubusercontent.com/156575/42783248-6bbd5be4-8919-11e8-97fd-b10c8eb2607b.png">

**Comment by rjsteinert** [comment] 2018-07-17 01:38
Looks like it might not be a Chrome issue but somehow related to extending PolymerElement? Spinning up a vanilla JS example Chrome gets it right.

<img width="1440" alt="screen shot 2018-07-16 at 9 36 20 pm" src="https://user-images.githubusercontent.com/156575/42791809-6b287ff2-8940-11e8-96ba-925fc1642830.png">

**Comment by rjsteinert** [comment] 2018-07-17 01:55
Moving back to the original demo I made, this is happening also when extending HTMLElement. I also then took out the web component loader in case that could be interfering but it's the same results. 

<img width="1280" alt="screen shot 2018-07-16 at 9 52 41 pm" src="https://user-images.githubusercontent.com/156575/42792367-e24c55e8-8942-11e8-8a61-934755e6dd20.png">

Is this somehow related to the bundler? Interestingly, if it is, I'm also seeing the same behavior in the Webpack bundler that the Angular framework gives you out of the box.

**Comment by rjsteinert** [comment] 2018-07-17 01:58
I uploaded my example to [here](https://github.com/rjsteinert/custom-element-with-missing-class). It's a standard new polymer 3 element project with modifications made to the demo/index.html file and the extended class in the foo-element.js file changed to HTMLElement.

**Comment by web-padawan** [comment] 2018-07-17 16:11
You must usein closing tag for custom elements, according to the spec. Using only opening tag, or "self-closing" is not supported, and will most likely ignored, and this is what seems to happen in your case.

**Comment by rjsteinert** [comment] 2018-07-17 19:54
@web-padawan Win! 

<img width="1280" alt="screen shot 2018-07-17 at 3 52 21 pm" src="https://user-images.githubusercontent.com/156575/42841874-6ff0705a-89d9-11e8-8da0-3e0745573034.png">

Unfortunately that's not the root of the issue causing this to happen elsewhere for me when including tangy-form in an Angular app. I wonder what else could cause this.

**Comment by M4FFS** [comment] 2018-07-20 15:02
Try surrounding window.container.innerHTML = "..." with a Polymer.dom() function:

Polymer.dom(window.container.innerHTML = "<foo...">);

Can't tell you why, but that works for me

**Comment by kevinpschaaf** [comment] 2018-07-23 21:08
When custom elements upgrade is a simple function of when the element is defined (`customElements.define`) and when an element is created (e.g. `innerHTML`, `createElement`, etc.):
* An element created before definition will upgrade synchronously to the `customElements.define` call as long as it is connected to the document (if not, it will upgrade synchronously to the call that connects it, i.e. `appendChild`).
* An element created after the `customElements.define` call will upgrade synchronously to the method that creates the element.

If you are seeing something different, you need to pinpoint when these two events (define & create) are occurring. You have not provided a repro, so it's not possible for us to explain the behavior your are seeing.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and **be sure to include a live reproduction** so that the team can debug or understand your issue.  You can start from [this glitch template](https://glitch.com/edit/#!/polymer-element-example?path=index.html) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!

**Closed by kevinpschaaf** 2018-07-23 21:08 UTC
