### ISSUE TITLE
stopPropagation on value-changed event

### ISSUE THREAD

**Issue by JMuratha** [Polymer/polymer#3822] opened 2016-07-28 13:43 UTC
if you call `stopPropagation()` of a `value-changed` event once, you will never ever receive a `value-changed` event again. I guess this happens because a cached version of the event is used.

**Comment by kaste** [comment] 2016-08-06 19:55
These events do not bubble, so calling stopPropagation wouldn't do anything anyway. Is this documented, @arthurevans?

**Comment by JMuratha** [comment] 2016-08-08 06:09
Oh i didn't see that they are not bubbling, but then there is another problem: when i have a custom element which has a value property and contains a `paper-input`, and you add a `value-changed` listener to the custom element, then there will fire 3 `value-changed` events (2 from the `paper-input`, 1 from my own custom element). 
And the bad thing is in the event listener function you can't even distinquish where this event is coming from.

**Comment by kaste** [comment] 2016-08-08 14:37
Good example +1. It works under _shady_ as expected.  Is this a duplicate of <paper-input> issue -> https://github.com/PolymerElements/paper-input/issues/66 ? @notwaldorf

**Comment by notwaldorf** [comment] 2016-08-08 18:02
I think PolymerElements/paper-input#66 is maybe the opposite? In that one, you have two behaviours that define a `value` property with `notify:true`, an element that implements both behaviours, and gets 2 sets of notifications

**Comment by JMuratha** [comment] 2016-08-09 05:28
I don't think this issue is related to the `paper-input` one, but more like #3226 . Since the problem here doesn't seem to be multiple property definitions (since my custom element on the example has the value property only defined once, but not thrice). The problem seems to be that events with `bubbles: false` are bubbling, since two value changed-events are emitted by the `paper-input` and are passing through my custom element, which i really don't want to.

**Comment by kaste** [comment] 2016-08-09 22:21
Yes, seems like this is a dupe of #3226 and #3403 (both closed) in combination with PolymerElements/paper-input#66

Since you cannot use `stopPropagation` anymore https://github.com/Polymer/polymer/issues/2815#issuecomment-176360187 you could check against `event.path` as a workaround. That seems pretty annoying, @azakus ?

**Comment by kaste** [comment] 2016-08-11 15:55
Polymer itself uses `_isEventBogus` https://github.com/Polymer/polymer/blob/e614e811fa151d105239b1d5d5521fd2322700f1/src/lib/bind/accessors.html#L210-L212 called like https://github.com/Polymer/polymer/blob/366b82d5397943d25d33c3df835e2c33d4f81d0f/src/standard/configure.html#L211 to filter these events.

**Comment by TimvdLippe** [comment] 2017-08-16 02:22
Closing this as I can not reproduce the issue at http://jsbin.com/cuzalesesu/edit?html,console,output Please reopen this issue with a JSBin which shows the issue.

**Closed by TimvdLippe** 2017-08-16 02:22 UTC
Labels: 1.x
