### ISSUE TITLE
build results in dist/polymer.html missing polymer-mini import

### ISSUE THREAD

**Issue by mfrost66** [Polymer/polymer#2679] opened 2015-11-04 06:00 UTC
Attempted to build polymer to test a pending PR.  I was unable to find a guide or notes, so I did a gulp build (`npm run build`).  The build created a ./dist folder with vulcanized files.  However, use of the files (replace my bower files with these) failed - the polymer.html file appears to be missing an import of poymer-mini.

If this isn't a bug, I'd appreciate a pointer in the right direction.

**Comment by azakus** [comment] 2015-11-06 18:29
Did you copy all of the files, `polymer.html`, `polymer-mini.html`, and `polymer-micro.html` ?

**Comment by mfrost66** [comment] 2015-11-08 23:29
Yes.  The issue is that the generated polymer.html file doesn't have an
include statement.

Not worth my time to troubleshoot w/o build documentation

**Comment by azakus** [comment] 2015-11-09 21:58
Are you on Windows by any chance?
I just confirmed our build works for Linux and Mac, but I haven't bothered to test it on Windows.

**Comment by mfrost66** [comment] 2015-11-09 22:05
I am.  The build "works" in that it doesn't fail.  The result files in dist
are vulcanized, its just that the polymer.html doesn't include the mini and
thus fails on use.

I'm assuming that the dist folder is the correct output, and that the files
are meant to be used stand-alone.

Top few lines from polymer.html - note the missing include:
```html
<!--
@license
Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at
http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at
http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at
http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at
http://polymer.github.io/PATENTS.txt
--><!--
@license
Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at
http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at
http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at
http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at
http://polymer.github.io/PATENTS.txt
--><script>Polymer.DomModule = document.createElement('dom-module');
Polymer.Base._addFeature({
_registerFeatures: function () {
```

**Comment by azakus** [comment] 2015-11-09 22:43
Looks like the exclusions in the build aren't working on Windows.
Not super surprised, I did that pretty quick.
Even when built, polymer should include polymer-mini, which should include polymer-micro.

**Comment by TimvdLippe** [comment] 2018-05-13 19:53
Closing this issue as `polymer-micro` no longer exists.

**Closed by TimvdLippe** 2018-05-13 19:53 UTC
Labels: 1.x, p2, tools
