### ISSUE TITLE
Console warnings contain no relevant information %c[%s::%s]

### ISSUE THREAD

**Issue by MarkDurbin104** [Polymer/polymer#1883] opened 2015-06-16 12:00 UTC
e.g. An undefined click handler on a button: 
*on-click="createDBss"*
issues:
*%c[%s::%s]: (12:54:06:597 | warning)
  at public_html/bower_components/polymer/polymer.html:350*
when clicked.
When using an IDE showing console log.  However, the log entries show correctly within chrome debugging

**Comment by kevinpschaaf** [comment] 2015-06-16 17:04
Polymer is using `console.log` [string substitution](https://developer.mozilla.org/en-US/docs/Web/API/console#Using_string_substitutions), which is widely supported in browsers.  The problem is in your IDE, which likely hooks the embedded browser's `console.log` so that it can output in the IDE, but doesn't comply to the full `console.log` spec.

What IDE are you using, and can you run `console.log(navigator.userAgent);` and let us know what is reported in the IDE console?  I'm assuming there's probably not much we can do here, but worth a look.

**Comment by kevinpschaaf** [comment] 2015-07-01 01:19
@MarkDurbin104 As noted above, there's probably little we can do if the IDE does not implement the `console.log` string substitution API. I'm going to go ahead and close this.

**Closed by kevinpschaaf** 2015-07-01 01:19 UTC
Labels: pending-response

**Comment by MarkDurbin104** [comment] 2015-07-01 07:49
Sorry, I didn't see you response of 15 days ago!  Thanks. The IDE is NetBeans BTW.
