### ISSUE TITLE
@apply(--paper-font-common-base); failed for :root

### ISSUE THREAD

**Issue by Mygod** [Polymer/polymer#2113] opened 2015-07-18 14:19 UTC
This works:

    :root * {
        @apply(--paper-font-common-base);
    }

While this don't:

    :root {
        @apply(--paper-font-common-base);
    }

Is this an expected behavior?

**Comment by Mygod** [comment] 2015-07-18 15:02
It seems this is a better solution:

    body {
        @apply(--paper-font-common-base);
    }

**Comment by timeu** [comment] 2015-07-18 17:18
Just to make sure: 
Did you put your `:root` selector inside a ` <style is="custom-style">` as mentioned in the [docs](https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-style) ?

**Comment by Mygod** [comment] 2015-07-19 00:04
Yes I did. (otherwise none of them would work IMO)

**Comment by sorvell** [comment] 2015-07-21 01:28
I'm not able to reproduce this issue. For example, the following works fine:

http://jsbin.com/narasahace/edit?html,output

I've also tried this directly with `paper-styles` and don't see the issue. Can you provide a test case that shows the issue? Thanks.

**Comment by sorvell** [comment] 2015-07-21 01:29
Please note that the `custom-style` that uses `--paper-font-common-base` must be after the import that defines the variable, in this case `paper-styles\typography.html`.

**Comment by Mygod** [comment] 2015-07-21 15:43
It turns out the other line I put before `@apply` seems to be the problem. Reordered the lines and the problem seem to be gone.

Here's an example: http://jsbin.com/lehutolebi/edit?html,output

**Comment by sorvell** [comment] 2015-07-29 17:15
Thanks. We've tracked this down and it should be fixed in the next release.

**Closed** 2015-07-30 17:40 UTC
Labels: p1
