### ISSUE TITLE
delete method

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#3379] opened 2016-02-05 14:53 UTC
There is a set of methods to manipulate data object like `set, get, splice, arrayDelete` even methods to notify after the change like `notifyPath, notifySplices`, but there is no method to remove an object/property.
We can `set('that.property', undefined)` but setting undefined is not the same as `delete that.property`, what's more this is not a valid JSON value, what hurts when we use data shared with other apps.

I think it would be nice to have such methods, plus it would make the API consistent, as now we can delete array elements, but we cannot remove others.

**Comment by TimvdLippe** [comment] 2016-02-05 14:59
This is a dupe of #2565

**Closed** 2016-02-07 22:23 UTC
