### ISSUE TITLE
Observer of Date property fires even when there is no change

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer#3454] opened 2016-02-23 07:27 UTC
Tracking down a cause of recursion in my app, I wrote this little test harness.  You will notice I write the same value back to the property that I take out of it, for both a number and a date.  With the number the observer doesn't fire, for the date it does.

```
<html>
<head>
  <script src="components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="components/polymer/polymer.html">
  <script type="text/javascript">
    Polymer({
      is: 'date-tester',
      properties: {
        date: {
          type: Date,
          value: function() {
            var now = new Date();
            return new Date(
              now.getFullYear(),
              now.getMonth() - 1,
              1,
              6,0,0
            );
          },
          observer: 'dateChanged'
        },
        num: {
          type: Number,
          value: 200,
          observer: 'numberChanged'
        }
      },
      attached: function() {
        this.async(function() {
          var value = this.date.getTime();
          var n = this.num;
          this.async(function() {
            this.date = new Date(value);
            this.num = n;
          },10);
        },10);
      },
      dateChanged: function(newDate,oldDate) {
        if (typeof oldDate !== 'undefined') {
          console.log('Old Date: ' + oldDate.toUTCString());
          console.log('new Date: ' + newDate.toUTCString());
          console.log('Millisecond Diff: ' + (newDate.getTime() - oldDate.getTime()).toString());
        }
      },
      numberChanged: function(newNo,oldNo) {
        if(typeof oldNo !== 'undefined') {
          console.log('Old Number ' + oldNo.toString());
          console.log('New Number ' + newNo.toString());
        }
      }
    })
  </script>
  </head>
  <body>
    <template id="app" is="dom-bind">
      <date-tester></date-tester>
    </template>
  </body>
</html>
```

**Comment by timeu** [comment] 2016-02-23 08:36
If I am not mistaken this is by design. 
The `date` property is an object and thus the observer will fire when you create a new instance (the equality check will return false), while numbers are primitives and the equality check is based on the value of the number.

**Comment by akc42** [comment] 2016-02-23 10:31
I checked the developers guide to see what it said, and it didn't say that.  It says when the "value" of the property changes the Observer is fired.  That is why my test case deliberately created a new value

**Comment by zoechi** [comment] 2016-02-23 10:43
The "value" of the property actually has changed. Only the value of the "value" of the property is the same, but that isn't what Polymer checks.

**Comment by kaste** [comment] 2016-02-23 12:33
When #3238 lands, you can make this work.

**Comment by azakus** [comment] 2016-02-25 23:16
Yep, this is a dupe of #2719

**Closed by azakus** 2016-02-25 23:16 UTC
